"""Fix test_wifi_bridge_stream.py schema frame tests."""
import struct

with open('ground_station/comm/tests/test_wifi_bridge_stream.py', 'r', encoding='utf-8') as f:
    content = f.read()

# ---- Fix 1: test_pending_ranges_cleared_by_schema_frame ----
old1 = (
    '    def test_pending_ranges_cleared_by_schema_frame(self):\n'
    '        """_handle_schema_frame clears _pending_schema_ranges[slot] after processing."""\n'
    '        # Pre-populate pending ranges\n'
    '        self.bridge._pending_schema_ranges[0] = ("var1", "var2")\n'
    '        self.assertIn(0, self.bridge._pending_schema_ranges)\n'
    '        # 0x08 uses XOR-CRC (byte-wise XOR), NOT CRC16-CCITT.\n'
    '        from ground_station.livewatch.transport import _xor_crc\n'
    '        n_ranges = 0\n'
    '        divider = 4\n'
    '        transport = 1\n'
    '        slot = 0\n'
    '        total_bytes = 0\n'
    '        # Schema payload fields after N_RANGES: divider(1)+transport(1)+slot(1)+total_hi(1)+total_lo(1) = 5 bytes\n'
    '        payload = bytes([n_ranges, divider, transport, slot,\n'
    '                         (total_bytes >> 8) & 0xFF, total_bytes & 0xFF])\n'
    '        # LEN field = actual payload bytes after LEN = 6 (N_RANGES through TOTAL_LO)\n'
    '        payload_len = len(payload)  # = 6\n'
    '        len_hi = (payload_len >> 8) & 0xFF\n'
    '        len_lo = payload_len & 0xFF\n'
    '        header = bytes([0xAA, 0xBB, 0x08, len_hi, len_lo])\n'
    '        # XOR-CRC over bytes [2..-1] = [0x08] + payload\n'
    '        crc_byte = _xor_crc(bytes([0x08]) + payload)\n'
    '        frame = header + payload + bytes([crc_byte])\n'
    '        # total_len = 6 + payload_len + 1 = 6 + 6 + 1 = 13 bytes (but the\n'
    '        # LEN field itself is 2 bytes; the actual payload bytes = 6)\n'
    '        # Wait \u2014 the LEN field IS included in the length; len=6 means 6 bytes\n'
    '        # after the LEN field, i.e. N_RANGES..TOTAL_LO = 6 bytes.\n'
    '        # So actual frame = sync(2)+type(1)+len(2)+payload(6)+crc(1) = 12 bytes.\n'
    '        # Check: 6 + 6 + 1 = 13 \u2192 expects 13 but we have 12.\n'
    '        # The LEN field is 2 bytes; len=6 means 6 payload bytes AFTER the len field.\n'
    '        # sync(2) + type(1) + len(2) = 5 bytes before payload.\n'
    '        # payload_len from frame[3:5] = 6. Formula: 5 + 6 + 1 = 12.\n'
    '        self.assertEqual(len(frame), 12)\n'
    '        result = self.bridge._handle_schema_frame(frame)\n'
    '        self.assertEqual(result, slot)\n'
    '        # Pending ranges are cleared after schema response\n'
    '        self.assertNotIn(0, self.bridge._pending_schema_ranges)'
)
new1 = (
    '    def test_pending_ranges_cleared_by_schema_frame(self):\n'
    '        """_handle_schema_frame clears _pending_schema_ranges[slot] after processing."""\n'
    '        # Pre-populate pending ranges\n'
    '        self.bridge._pending_schema_ranges[0] = ("var1", "var2")\n'
    '        self.assertIn(0, self.bridge._pending_schema_ranges)\n'
    '        # Build a correct 0x08 frame with 1 range.\n'
    '        # Config=5 B, one range=8 B \u2192 total_bytes=4, payload_len=14.\n'
    '        # CRC covers TYPE+LEN+config+range = raw[2:-1].\n'
    '        from ground_station.livewatch.transport import _xor_crc\n'
    '        n_ranges = 1\n'
    '        divider = 4\n'
    '        transport = 1\n'
    '        slot = 0\n'
    '        total_bytes = 4\n'
    '        # Config (5 B): n_ranges, divider, transport, slot, total_hi, total_lo\n'
    '        config = bytes([n_ranges, divider, transport, slot,\n'
    '                        (total_bytes >> 8) & 0xFF, total_bytes & 0xFF])\n'
    '        # Range (8 B): address=0x20000000, size=4, count=1\n'
    '        rng = struct.pack("<IHH", 0x20000000, 4, 1)\n'
    '        payload = config + rng  # 14 B total\n'
    '        payload_len = len(payload)  # 14\n'
    '        crc_body = bytes([0x08]) + payload\n'
    '        frame = (bytes([0xAA, 0xBB, 0x08,\n'
    '                       (payload_len >> 8) & 0xFF, payload_len & 0xFF])\n'
    '                 + payload\n'
    '                 + bytes([_xor_crc(crc_body)]))\n'
    '        # Length check: 6 + payload_len + 1 = 21 B\n'
    '        self.assertEqual(len(frame), 6 + payload_len + 1)\n'
    '        result = self.bridge._handle_schema_frame(frame)\n'
    '        self.assertEqual(result, slot)\n'
    '        # Pending ranges are cleared after schema response\n'
    '        self.assertNotIn(0, self.bridge._pending_schema_ranges)'
)

if old1 not in content:
    print('OLD1 NOT FOUND')
else:
    content = content.replace(old1, new1)
    print('Fixed test_pending_ranges_cleared_by_schema_frame')

# ---- Fix 2: test_schema_frame_transitions_sent_to_schema_received ----
# This test references undefined variables 'header', 'payload', 'slot'
old2 = (
    '    def test_schema_frame_transitions_sent_to_schema_received(self):\n'
    '        """_handle_schema_frame advances slot state from \'sent\' to \'schema_received\'."""\n'
    '        # Set up: send a request \u2192 state is \'sent\'.\n'
    '        # Pass a valid StreamRange so build_stream_request does not reject empty payload.\n'
    '        self.bridge._send_subscribe_bytes(\n'
    '            slot=1, divider=4,\n'
    '            ranges=[StreamRange(address=0x20000000, size=4, count=1, name="test.x")],\n'
    '            transport=1, request_id=5,\n'
    '        )\n'
    '        self.assertEqual(self.bridge._slot_states[1], "sent")\n'
    '        # Simulate receiving a 0x08 schema reply (0 ranges, divider 4).\n'
    '        # XOR-CRC over bytes [2..-1] = [0x08] + payload\n'
    '        crc_byte = _xor_crc(bytes([0x08]) + payload)\n'
    '        frame = header + payload + bytes([crc_byte])\n'
    '        # total_len = 6 + payload_len + 1 = 6 + 6 + 1 = 13 bytes\n'
    '        self.assertEqual(len(frame), 13)\n'
    '        result = self.bridge._handle_schema_frame(frame)\n'
    '        self.assertEqual(result, slot)\n'
    '        self.assertEqual(self.bridge._slot_states[1], "schema_received")'
)
new2 = (
    '    def test_schema_frame_transitions_sent_to_schema_received(self):\n'
    '        """_handle_schema_frame advances slot state from \'sent\' to \'schema_received\'."""\n'
    '        # Set up: send a request \u2192 state is \'sent\'.\n'
    '        self.bridge._send_subscribe_bytes(\n'
    '            slot=1, divider=4,\n'
    '            ranges=[StreamRange(address=0x20000000, size=4, count=1, name="test.x")],\n'
    '            transport=1, request_id=5,\n'
    '        )\n'
    '        self.assertEqual(self.bridge._slot_states[1], "sent")\n'
    '        # Simulate receiving a 0x08 schema reply with 1 range.\n'
    '        # Config=5 B, one range=8 B \u2192 payload_len=14.\n'
    '        from ground_station.livewatch.transport import _xor_crc\n'
    '        n_ranges = 1\n'
    '        divider = 4\n'
    '        transport = 1\n'
    '        slot = 1\n'
    '        total_bytes = 4\n'
    '        config = bytes([n_ranges, divider, transport, slot,\n'
    '                        (total_bytes >> 8) & 0xFF, total_bytes & 0xFF])\n'
    '        rng = struct.pack("<IHH", 0x20000000, 4, 1)\n'
    '        payload = config + rng  # 14 B\n'
    '        payload_len = len(payload)  # 14\n'
    '        crc_body = bytes([0x08]) + payload\n'
    '        frame = (bytes([0xAA, 0xBB, 0x08,\n'
    '                       (payload_len >> 8) & 0xFF, payload_len & 0xFF])\n'
    '                 + payload\n'
    '                 + bytes([_xor_crc(crc_body)]))\n'
    '        self.assertEqual(len(frame), 6 + payload_len + 1)\n'
    '        result = self.bridge._handle_schema_frame(frame)\n'
    '        self.assertEqual(result, slot)\n'
    '        self.assertEqual(self.bridge._slot_states[1], "schema_received")'
)

if old2 not in content:
    print('OLD2 NOT FOUND')
else:
    content = content.replace(old2, new2)
    print('Fixed test_schema_frame_transitions_sent_to_schema_received')

# ---- Fix 3: test_schema_frame_unknown_slot_is_ignored ----
old3 = (
    '    def test_schema_frame_unknown_slot_is_ignored(self):\n'
    '        """A 0x08 for a slot with no pending request is dropped."""\n'
    '        # Send a schema for slot 2 with no pending ranges\n'
    '        from ground_station.livewatch.transport import _xor_crc\n'
    '        n_ranges = 1\n'
    '        divider = 4\n'
    '        transport = 1\n'
    '        slot = 2\n'
    '        total_bytes = 4\n'
    '        payload = bytes([n_ranges, divider, transport, slot,\n'
    '                         (total_bytes >> 8) & 0xFF, total_bytes & 0xFF,\n'
    '                         0x00, 0x10, 0x00, 0x00,   # address 0x100000\n'
    '                         0x04, 0x00, 0x01, 0x00])  # size=4, count=1\n'
    '        payload_len = len(payload)\n'
    '        len_hi = (payload_len >> 8) & 0xFF\n'
    '        len_lo = payload_len & 0xFF\n'
    '        header = bytes([0xAA, 0xBB, 0x08, len_hi, len_lo])\n'
    '        crc_byte = _xor_crc(bytes([0x08]) + payload)\n'
    '        frame = header + payload + bytes([crc_byte])\n'
    '        result = self.bridge._handle_schema_frame(frame)\n'
    '        # The schema is still registered (the firmware replied, so it\'s valid)\n'
    '        self.assertEqual(result, 2)\n'
    '        self.assertIsNotNone(self.bridge._stream_schemas.get(2))\n'
    '        # But pending ranges for other slots are unaffected\n'
    '        self.assertNotIn(0, self.bridge._pending_schema_ranges)'
)
new3 = (
    '    def test_schema_frame_unknown_slot_is_ignored(self):\n'
    '        """A 0x08 for a slot with no pending request is still registered.\n'
    '        The firmware can reply for any slot; pending ranges are only a hint\n'
    '        for name re-attachment, not a gate.\n'
    '        """\n'
    '        # Send a schema for slot 2 with no pending ranges\n'
    '        from ground_station.livewatch.transport import _xor_crc\n'
    '        n_ranges = 1\n'
    '        divider = 4\n'
    '        transport = 1\n'
    '        slot = 2\n'
    '        total_bytes = 4\n'
    '        config = bytes([n_ranges, divider, transport, slot,\n'
    '                        (total_bytes >> 8) & 0xFF, total_bytes & 0xFF])\n'
    '        rng = struct.pack("<IHH", 0x20000000, 4, 1)\n'
    '        payload = config + rng  # 14 B\n'
    '        payload_len = len(payload)\n'
    '        crc_body = bytes([0x08]) + payload\n'
    '        frame = (bytes([0xAA, 0xBB, 0x08,\n'
    '                       (payload_len >> 8) & 0xFF, payload_len & 0xFF])\n'
    '                 + payload\n'
    '                 + bytes([_xor_crc(crc_body)]))\n'
    '        self.assertEqual(len(frame), 6 + payload_len + 1)\n'
    '        result = self.bridge._handle_schema_frame(frame)\n'
    '        # Schema is still registered (firmware replied with valid slot)\n'
    '        self.assertEqual(result, 2)\n'
    '        self.assertIsNotNone(self.bridge._stream_schemas.get(2))\n'
    '        # Pending ranges for other slots are unaffected\n'
    '        self.assertNotIn(0, self.bridge._pending_schema_ranges)'
)

if old3 not in content:
    print('OLD3 NOT FOUND')
else:
    content = content.replace(old3, new3)
    print('Fixed test_schema_frame_unknown_slot_is_ignored')

# ---- Fix 4: test_reconnect_drops_frames_with_old_schema ----
old4 = (
    '    def test_reconnect_drops_frames_with_old_schema(self):\n'
    '        """After a reconnect, stale schemas cannot corrupt fresh data.\n\n'
    '        The reconnect sequence is:\n'
    '          1. send new 0x21 \u2192 clears old schema and stats\n'
    '          2. receive 0x08 \u2192 registers fresh schema\n'
    '          3. receive 0x09 frames \u2192 decoded with fresh schema\n\n'
    '        Frames decoded BEFORE step 2 arrive with no schema (or the old\n'
    '        one); they decode as positional channels. After step 2, they\n'
    '        decode with names.\n'
    '        """\n'
    '        self.bridge._stream_schemas[0] = FakeSchema(ranges=(StreamRange(\n'
    '            address=0x20000000, size=4, count=1, name="old_addr", fmt="f"),))\n'
    '        self.bridge._stream_stats[0] = {"received": 5, "dropped": 0, "crc_errors": 0, "last_seq": 4}\n'
    '        self.bridge._wifi_send = MagicMock()\n'
    '        # Step 1: new subscribe clears old schema\n'
    '        self.bridge._send_subscribe_bytes(\n'
    '            slot=0, divider=4,\n'
    '            ranges=[StreamRange(address=0x20001000, size=4, count=1, name="new_addr", fmt="f")],\n'
    '            transport=1, request_id=10,\n'
    '        )\n'
    '        self.assertIsNone(self.bridge._stream_schemas.get(0))\n'
    '        self.assertIsNone(self.bridge._stream_stats.get(0))\n'
    '        # Step 2: fresh schema registered\n'
    '        from ground_station.livewatch.transport import _xor_crc\n'
    '        n_ranges = 1\n'
    '        divider = 4\n'
    '        transport = 1\n'
    '        slot = 0\n'
    '        total_bytes = 4\n'
    '        payload = bytes([n_ranges, divider, transport, slot,\n'
    '                         (total_bytes >> 8) & 0xFF, total_bytes & 0xFF,\n'
    '                         0x00, 0x10, 0x00, 0x20,   # address 0x20001000\n'
    '                         0x04, 0x00, 0x01, 0x00])  # size=4, count=1\n'
    '        payload_len = len(payload)\n'
    '        len_hi = (payload_len >> 8) & 0xFF\n'
    '        len_lo = payload_len & 0xFF\n'
    '        header = bytes([0xAA, 0xBB, 0x08, len_hi, len_lo])\n'
    '        crc_byte = _xor_crc(bytes([0x08]) + payload)\n'
    '        frame = header + payload + bytes([crc_byte])\n'
    '        result = self.bridge._handle_schema_frame(frame)\n'
    '        self.assertEqual(result, 0)\n'
    '        self.assertIsNotNone(self.bridge._stream_schemas.get(0))\n'
    '        # Step 3: data frame decoded with new schema\n'
    '        data_frame = _build_stream_frame(slot=0, seq=0, t_ms=1000, values=[3.14])\n'
    '        decoded = self.bridge._decode_stream_frame(0, data_frame)\n'
    '        self.assertIsNotNone(decoded)\n'
    '        # The fresh schema resolves the channel name\n'
    '        self.assertEqual(decoded["names"][0], "new_addr")'
)
new4 = (
    '    def test_reconnect_drops_frames_with_old_schema(self):\n'
    '        """After a reconnect, stale schemas cannot corrupt fresh data.\n\n'
    '        The reconnect sequence is:\n'
    '          1. send new 0x21 \u2192 clears old schema and stats\n'
    '          2. receive 0x08 \u2192 registers fresh schema\n'
    '          3. receive 0x09 frames \u2192 decoded with fresh schema\n'
    '        """\n'
    '        self.bridge._stream_schemas[0] = FakeSchema(ranges=(StreamRange(\n'
    '            address=0x20000000, size=4, count=1, name="old_addr", fmt="f"),))\n'
    '        self.bridge._stream_stats[0] = {"received": 5, "dropped": 0, "crc_errors": 0, "last_seq": 4}\n'
    '        self.bridge._wifi_send = MagicMock()\n'
    '        # Step 1: new subscribe clears old schema\n'
    '        self.bridge._send_subscribe_bytes(\n'
    '            slot=0, divider=4,\n'
    '            ranges=[StreamRange(address=0x20001000, size=4, count=1, name="new_addr", fmt="f")],\n'
    '            transport=1, request_id=10,\n'
    '        )\n'
    '        self.assertIsNone(self.bridge._stream_schemas.get(0))\n'
    '        self.assertIsNone(self.bridge._stream_stats.get(0))\n'
    '        # Step 2: fresh schema registered (correct 1-range frame)\n'
    '        from ground_station.livewatch.transport import _xor_crc\n'
    '        n_ranges = 1\n'
    '        divider = 4\n'
    '        transport = 1\n'
    '        slot = 0\n'
    '        total_bytes = 4\n'
    '        config = bytes([n_ranges, divider, transport, slot,\n'
    '                        (total_bytes >> 8) & 0xFF, total_bytes & 0xFF])\n'
    '        rng = struct.pack("<IHH", 0x20001000, 4, 1)  # address=0x20001000\n'
    '        payload = config + rng  # 14 B\n'
    '        payload_len = len(payload)  # 14\n'
    '        crc_body = bytes([0x08]) + payload\n'
    '        frame = (bytes([0xAA, 0xBB, 0x08,\n'
    '                       (payload_len >> 8) & 0xFF, payload_len & 0xFF])\n'
    '                 + payload\n'
    '                 + bytes([_xor_crc(crc_body)]))\n'
    '        self.assertEqual(len(frame), 6 + payload_len + 1)\n'
    '        result = self.bridge._handle_schema_frame(frame)\n'
    '        self.assertEqual(result, 0)\n'
    '        self.assertIsNotNone(self.bridge._stream_schemas.get(0))\n'
    '        # Step 3: data frame decoded with new schema\n'
    '        data_frame = _build_stream_frame(slot=0, seq=0, t_ms=1000, values=[3.14])\n'
    '        decoded = self.bridge._decode_stream_frame(0, data_frame)\n'
    '        self.assertIsNotNone(decoded)\n'
    '        # The fresh schema resolves the channel name\n'
    '        self.assertEqual(decoded["names"][0], "new_addr")'
)

if old4 not in content:
    print('OLD4 NOT FOUND')
else:
    content = content.replace(old4, new4)
    print('Fixed test_reconnect_drops_frames_with_old_schema')

with open('ground_station/comm/tests/test_wifi_bridge_stream.py', 'w', encoding='utf-8') as f:
    f.write(content)
print('All fixes applied.')
