"""Turn a Jupyter notebook into a plain .py text file that agents can grep.

Markdown cells become ``#`` comments, code cells are copied verbatim, text
outputs are kept as ``# >>`` comments truncated to MAX_OUT_LINES lines, and
image outputs are dropped. Every cell gets a ``# %% [cell N]`` header where N is
the 0-based index into the notebook's ``cells`` list, so digests can cite it.

    python -m ground_station.research.notebooks.extract NOTEBOOK.ipynb OUT.py
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

MAX_OUT_LINES = 20
_ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")


def _text(src) -> str:
    return "".join(src) if isinstance(src, list) else (src or "")


def _output_lines(out: dict) -> list[str]:
    kind = out.get("output_type")
    if kind == "stream":
        return _text(out.get("text")).splitlines()
    if kind in ("execute_result", "display_data"):
        data = out.get("data", {})
        lines = []
        if any(k.startswith("image/") for k in data):
            lines.append("[image dropped]")
        if "text/plain" in data:
            lines += _text(data["text/plain"]).splitlines()
        return lines
    if kind == "error":
        return [_ANSI.sub("", f"{out.get('ename', '')}: {out.get('evalue', '')}")]
    return []


def extract(nb: dict, source: str = "") -> str:
    parts = [f"# Extract of {source}" if source else "# Notebook extract",
             "# Generated by ground_station/research/notebooks/extract.py; do not edit.", ""]
    for i, cell in enumerate(nb.get("cells", [])):
        ctype = cell.get("cell_type", "code")
        src = _text(cell.get("source"))
        parts.append(f"# %% [cell {i}] {ctype}")
        if ctype == "code":
            parts.append(src)
            lines = []
            for out in cell.get("outputs", []):
                lines += _output_lines(out)
            if lines:
                extra = len(lines) - MAX_OUT_LINES
                parts += [f"# >> {ln}".rstrip() for ln in lines[:MAX_OUT_LINES]]
                if extra > 0:
                    parts.append(f"# >> [... {extra} more output lines truncated]")
        else:
            parts += [f"# {ln}".rstrip() for ln in src.splitlines()]
        parts.append("")
    return "\n".join(parts) + "\n"


def extract_file(nb_path: Path, out_path: Path) -> None:
    nb = json.loads(Path(nb_path).read_text(encoding="utf-8"))
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(extract(nb, Path(nb_path).name), encoding="utf-8")


def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("notebook")
    ap.add_argument("out")
    args = ap.parse_args(argv)
    extract_file(Path(args.notebook), Path(args.out))


if __name__ == "__main__":
    main()
