"""Tests for terminal manager wiring and health endpoint RSS metric.

Covers:
- TerminalManager is passed from the service builder through to ApiServer.
- Token file path resolves inside the repo (.agent_state/terminal-token).
- Token is 32 hex chars generated by `secrets` (verified via monkeypatch).
- GET /health includes `process_rss_mb`.
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path
from unittest.mock import patch, MagicMock

from ground_station.livewatch.stream import StreamRange, StreamSchema
from ground_station.service.api import ApiServer
from ground_station.service.core import GroundStationService
from ground_station.service.storage import SessionStore


def _get_json(url):
    """GET a URL and return (status_code, parsed_json)."""
    import http.client
    from urllib.parse import urlparse

    parsed = urlparse(url)
    host, port = parsed.hostname, parsed.port or 80
    path = parsed.path or "/"
    if parsed.query:
        path += "?" + parsed.query
    conn = http.client.HTTPConnection(host, port)
    conn.connect()
    conn.request("GET", path)
    resp = conn.getresponse()
    body = resp.read()
    try:
        body_json = json.loads(body)
    except Exception:
        body_json = {"raw": body.decode(errors="replace")}
    return resp.status, body_json


# -----------------------------------------------------------------------
# 1. Service builder passes a TerminalManager
# -----------------------------------------------------------------------


def test_service_builder_passes_terminal_manager():
    """ApiServer has a terminal_manager when constructed with one."""
    schema = StreamSchema(1, 1, 4,
                          (StreamRange(0x20000000, 4, 1, "altitude", "f"),), 0)
    service = GroundStationService(store=SessionStore(), schemas=[schema], source="sim")
    service.start()

    from ground_station.service.terminal import TerminalManager
    with tempfile.TemporaryDirectory() as td:
        tm = TerminalManager(state_dir=Path(td))
        api = ApiServer(service, host="127.0.0.1", port=0, terminal_manager=tm)
        api.start()
        try:
            assert api.terminal_manager is not None
            assert api.terminal_manager is tm
        finally:
            api.stop()
            service.stop()


def test_start_shell_passes_terminal_manager():
    """start_shell forwards terminal_manager to ApiServer."""
    from ground_station.platform.shell import start_shell
    from ground_station.service.terminal import TerminalManager

    schema = StreamSchema(1, 1, 4,
                          (StreamRange(0x20000000, 4, 1, "altitude", "f"),), 0)
    service = GroundStationService(store=SessionStore(), schemas=[schema], source="sim")
    service.start()

    with tempfile.TemporaryDirectory() as td:
        tm = TerminalManager(state_dir=Path(td))
        api = start_shell(service, port=0, terminal_manager=tm)
        try:
            assert api.terminal_manager is not None
            assert api.terminal_manager is tm
        finally:
            api.stop()
            service.stop()


# -----------------------------------------------------------------------
# 2. Token path resolves inside the repo
# -----------------------------------------------------------------------


def test_token_path_resolves_inside_repo():
    """_DEFAULT_STATE_DIR points into the repo, not above it."""
    from ground_station.service.terminal import _DEFAULT_STATE_DIR
    repo_root = Path(__file__).resolve().parents[3]  # tests -> service -> ground_station -> repo
    expected = repo_root / ".agent_state"
    assert _DEFAULT_STATE_DIR == expected, (
        f"expected {_DEFAULT_STATE_DIR!r} to be {expected!r}"
    )


def test_token_file_lives_in_state_dir():
    """_token_file returns the correct path inside _DEFAULT_STATE_DIR."""
    from ground_station.service.terminal import _token_file, _DEFAULT_STATE_DIR
    tf = _token_file()
    assert tf.name == "terminal-token"
    assert tf.parent == _DEFAULT_STATE_DIR


# -----------------------------------------------------------------------
# 3. Token is 32 hex chars and comes from `secrets`
# -----------------------------------------------------------------------


def test_token_is_32_hex_chars_from_secrets():
    """A freshly generated token is 32 hex characters from secrets.token_hex(16)."""
    from ground_station.service.terminal import _ensure_token
    with tempfile.TemporaryDirectory() as td:
        state_dir = Path(td)
        # Monkey-patch secrets.token_hex to return a known value
        with patch("ground_station.service.terminal.secrets.token_hex", return_value="a" * 32):
            token = _ensure_token(state_dir)
            assert len(token) == 32
            assert all(c in "0123456789abcdef" for c in token), "token must be hex"


def test_reloaded_token_matches_stored():
    """Reading back the token file returns the same value."""
    from ground_station.service.terminal import _ensure_token
    with tempfile.TemporaryDirectory() as td:
        state_dir = Path(td)
        with patch("ground_station.service.terminal.secrets.token_hex", return_value="deadbeef" * 4):
            t1 = _ensure_token(state_dir)
        t2 = _ensure_token(state_dir)
        assert t1 == t2


# -----------------------------------------------------------------------
# 4. GET /health includes process_rss_mb
# -----------------------------------------------------------------------


def test_health_has_process_rss_mb():
    """GET /health returns a process_rss_mb field (number or None)."""
    schema = StreamSchema(1, 1, 4,
                          (StreamRange(0x20000000, 4, 1, "altitude", "f"),), 0)
    service = GroundStationService(store=SessionStore(), schemas=[schema], source="sim")
    service.start()
    api = ApiServer(service, host="127.0.0.1", port=0)
    api.start()
    try:
        port = api.address[1]
        base = "http://127.0.0.1:%d" % port
        status, body = _get_json(base + "/health")
        assert status == 200
        assert "process_rss_mb" in body
        val = body["process_rss_mb"]
        # With psutil it is a float rounded to 1 decimal; without it is None.
        assert val is None or isinstance(val, (int, float)), f"got {val!r}"
    finally:
        api.stop()
        service.stop()
