"""Tests for terminal manager wiring and health endpoint RSS metric.

Covers:
- TerminalManager is passed from the service builder through to ApiServer.
- Token file path resolves inside the repo (.agent_state/terminal-token).
- Token is 32 hex chars generated by `secrets` (verified via monkeypatch).
- GET /health includes `process_rss_mb`.
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path
from unittest.mock import patch, MagicMock

from ground_station.livewatch.stream import StreamRange, StreamSchema
from ground_station.service.api import ApiServer
from ground_station.service.core import GroundStationService
from ground_station.service.storage import SessionStore


def _get_json(url):
    """GET a URL and return (status_code, parsed_json)."""
    import http.client
    from urllib.parse import urlparse

    parsed = urlparse(url)
    host, port = parsed.hostname, parsed.port or 80
    path = parsed.path or "/"
    if parsed.query:
        path += "?" + parsed.query
    conn = http.client.HTTPConnection(host, port)
    conn.connect()
    conn.request("GET", path)
    resp = conn.getresponse()
    body = resp.read()
    try:
        body_json = json.loads(body)
    except Exception:
        body_json = {"raw": body.decode(errors="replace")}
    return resp.status, body_json


# -----------------------------------------------------------------------
# 1. Service builder passes a TerminalManager
# -----------------------------------------------------------------------


def test_service_builder_passes_terminal_manager():
    """ApiServer has a terminal_manager when constructed with one."""
    schema = StreamSchema(1, 1, 4,
                          (StreamRange(0x20000000, 4, 1, "altitude", "f"),), 0)
    service = GroundStationService(store=SessionStore(), schemas=[schema], source="sim")
    service.start()

    from ground_station.service.terminal import TerminalManager
    with tempfile.TemporaryDirectory() as td:
        tm = TerminalManager(state_dir=Path(td))
        api = ApiServer(service, host="127.0.0.1", port=0, terminal_manager=tm)
        api.start()
        try:
            assert api.terminal_manager is not None
            assert api.terminal_manager is tm
        finally:
            api.stop()
            service.stop()


def test_start_shell_passes_terminal_manager():
    """start_shell forwards terminal_manager to ApiServer."""
    from ground_station.platform.shell import start_shell
    from ground_station.service.terminal import TerminalManager

    schema = StreamSchema(1, 1, 4,
                          (StreamRange(0x20000000, 4, 1, "altitude", "f"),), 0)
    service = GroundStationService(store=SessionStore(), schemas=[schema], source="sim")
    service.start()

    with tempfile.TemporaryDirectory() as td:
        tm = TerminalManager(state_dir=Path(td))
        api = start_shell(service, port=0, terminal_manager=tm)
        try:
            assert api.terminal_manager is not None
            assert api.terminal_manager is tm
        finally:
            api.stop()
            service.stop()


# -----------------------------------------------------------------------
# 2. Token path resolves inside the repo
# -----------------------------------------------------------------------


def test_token_path_resolves_inside_repo():
    """_DEFAULT_STATE_DIR points into the repo, not above it."""
    from ground_station.service.terminal import _DEFAULT_STATE_DIR
    repo_root = Path(__file__).resolve().parents[3]  # tests -> service -> ground_station -> repo
    expected = repo_root / ".agent_state"
    assert _DEFAULT_STATE_DIR == expected, (
        f"expected {_DEFAULT_STATE_DIR!r} to be {expected!r}"
    )


def test_token_file_lives_in_state_dir():
    """_token_file returns the correct path inside _DEFAULT_STATE_DIR."""
    from ground_station.service.terminal import _token_file, _DEFAULT_STATE_DIR
    tf = _token_file()
    assert tf.name == "terminal-token"
    assert tf.parent == _DEFAULT_STATE_DIR


# -----------------------------------------------------------------------
# 3. Token is 32 hex chars and comes from `secrets`
# -----------------------------------------------------------------------


def test_token_is_32_hex_chars_from_secrets():
    """A freshly generated token is 32 hex characters from secrets.token_hex(16)."""
    from ground_station.service.terminal import _ensure_token
    with tempfile.TemporaryDirectory() as td:
        state_dir = Path(td)
        # Monkey-patch secrets.token_hex to return a known value
        with patch("ground_station.service.terminal.secrets.token_hex", return_value="a" * 32):
            token = _ensure_token(state_dir)
            assert len(token) == 32
            assert all(c in "0123456789abcdef" for c in token), "token must be hex"


def test_reloaded_token_matches_stored():
    """Reading back the token file returns the same value."""
    from ground_station.service.terminal import _ensure_token
    with tempfile.TemporaryDirectory() as td:
        state_dir = Path(td)
        with patch("ground_station.service.terminal.secrets.token_hex", return_value="deadbeef" * 4):
            t1 = _ensure_token(state_dir)
        t2 = _ensure_token(state_dir)
        assert t1 == t2


# -----------------------------------------------------------------------
# 4. GET /health includes process_rss_mb
# -----------------------------------------------------------------------


def test_health_has_process_rss_mb():
    """GET /health returns a process_rss_mb field (number or None)."""
    schema = StreamSchema(1, 1, 4,
                          (StreamRange(0x20000000, 4, 1, "altitude", "f"),), 0)
    service = GroundStationService(store=SessionStore(), schemas=[schema], source="sim")
    service.start()
    api = ApiServer(service, host="127.0.0.1", port=0)
    api.start()
    try:
        port = api.address[1]
        base = "http://127.0.0.1:%d" % port
        status, body = _get_json(base + "/health")
        assert status == 200
        assert "process_rss_mb" in body
        val = body["process_rss_mb"]
        # With psutil it is a float rounded to 1 decimal; without it is None.
        assert val is None or isinstance(val, (int, float)), f"got {val!r}"
    finally:
        api.stop()
        service.stop()


# -----------------------------------------------------------------------
# 5. Terminal WS handshake regression — T12b
# -----------------------------------------------------------------------

def _http_request(host, port, method="GET", path="/", headers=None, body=None):
    """Send a raw HTTP request and return (status, headers_dict, body_bytes)."""
    import http.client
    hdrs = headers or {}
    if body:
        hdrs["Content-Length"] = str(len(body))
    conn = http.client.HTTPConnection(host, port, timeout=5)
    conn.request(method, path, body=body, headers=hdrs)
    resp = conn.getresponse()
    rb = resp.read()
    rh = {k.lower(): v for k, v in resp.getheaders()}
    conn.close()
    return resp.status, rh, rb


def _ws_handshake(host, port, token):
    """Open a raw socket, send a WebSocket upgrade request, return (accept_header, raw_socket)."""
    import socket
    key = "dGhlIHNhbXBsZSBub25jZQ=="  # RFC 6455 example
    req = (
        f"GET /api/terminal/ws?token={token} HTTP/1.1\r\n"
        f"Host: 127.0.0.1:{port}\r\n"
        f"Upgrade: websocket\r\n"
        f"Connection: Upgrade\r\n"
        f"Sec-WebSocket-Key: {key}\r\n"
        f"Sec-WebSocket-Version: 13\r\n"
        f"\r\n"
    ).encode()
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(5)
    sock.connect((host, port))
    sock.sendall(req)
    response = b""
    while b"\r\n\r\n" not in response:
        chunk = sock.recv(4096)
        if not chunk:
            sock.close()
            raise RuntimeError("handshake: no response headers")
        response += chunk
    lines = response.decode("utf-8", errors="replace").split("\r\n")
    status_line = lines[0]
    status = int(status_line.split(" ")[1])
    accept_hdr = ""
    for line in lines[1:]:
        if line.lower().startswith("sec-websocket-accept:"):
            accept_hdr = line.split(":", 1)[1].strip()
    return status, accept_hdr, sock


def _ws_send_text(sock, text):
    """Send a WebSocket text frame (masked, client→server)."""
    import struct
    data = text.encode("utf-8")
    length = len(data)
    import secrets
    mask_key = secrets.token_bytes(4)
    frame = b"\x81"
    if length < 126:
        frame += bytes([0x80 | length])
    elif length < 65536:
        frame += bytes([0x80 | 126]) + struct.pack("!H", length)
    else:
        frame += bytes([0x80 | 127]) + struct.pack("!Q", length)
    frame += mask_key
    masked = bytes(d ^ mask_key[i % 4] for i, d in enumerate(data))
    frame += masked
    sock.sendall(frame)


def _ws_recv_text(sock):
    """Receive one WebSocket text frame (unmasked, server→client)."""
    import struct
    header = sock.recv(2)
    if len(header) < 2:
        return ""
    fin = header[0] & 0x80
    opcode = header[0] & 0x0F
    length = header[1] & 0x7F
    if length == 126:
        ldata = sock.recv(2)
        length = struct.unpack("!H", ldata)[0]
    elif length == 127:
        ldata = sock.recv(8)
        length = struct.unpack("!Q", ldata)[0]
    # Server frames are NOT masked (no mask bit)
    payload = b""
    while len(payload) < length:
        chunk = sock.recv(min(4096, length - len(payload)))
        if not chunk:
            break
        payload += chunk
    if opcode == 1:
        return payload.decode("utf-8", errors="replace")
    return ""


def test_terminal_ws_401_without_token():
    """No token → 401 response."""
    from ground_station.service.terminal import TerminalManager
    schema = StreamSchema(1, 1, 4,
                          (StreamRange(0x20000000, 4, 1, "alt", "f"),), 0)
    service = GroundStationService(store=SessionStore(), schemas=[schema], source="sim")
    service.start()
    with tempfile.TemporaryDirectory() as td:
        tm = TerminalManager(state_dir=Path(td))
        api = ApiServer(service, host="127.0.0.1", port=0, terminal_manager=tm)
        api.start()
        try:
            port = api.address[1]
            status, _, _ = _http_request(
                "127.0.0.1", port,
                path="/api/terminal/ws?token=bad",
                headers={
                    "Host": f"127.0.0.1:{port}",
                    "Upgrade": "websocket",
                    "Connection": "Upgrade",
                    "Sec-WebSocket-Key": "dGhlIHNhbXBsZSBub25jZQ==",
                    "Sec-WebSocket-Version": "13",
                },
            )
            assert status == 401, f"expected 401, got {status}"
        finally:
            api.stop()
            service.stop()


def test_terminal_ws_401_bad_token():
    """Bad token → 401 response."""
    from ground_station.service.terminal import TerminalManager
    schema = StreamSchema(1, 1, 4,
                          (StreamRange(0x20000000, 4, 1, "alt", "f"),), 0)
    service = GroundStationService(store=SessionStore(), schemas=[schema], source="sim")
    service.start()
    with tempfile.TemporaryDirectory() as td:
        tm = TerminalManager(state_dir=Path(td))
        api = ApiServer(service, host="127.0.0.1", port=0, terminal_manager=tm)
        api.start()
        try:
            port = api.address[1]
            status, _, _ = _http_request(
                "127.0.0.1", port,
                path=f"/api/terminal/ws?token=wrongtoken",
                headers={
                    "Host": f"127.0.0.1:{port}",
                    "Upgrade": "websocket",
                    "Connection": "Upgrade",
                    "Sec-WebSocket-Key": "dGhlIHNhbXBsZSBub25jZQ==",
                    "Sec-WebSocket-Version": "13",
                },
            )
            assert status == 401, f"expected 401, got {status}"
        finally:
            api.stop()
            service.stop()


def test_terminal_ws_101_good_token():
    """Good token → 101 Switching Protocols with valid Sec-WebSocket-Accept."""
    from ground_station.service.terminal import TerminalManager
    schema = StreamSchema(1, 1, 4,
                          (StreamRange(0x20000000, 4, 1, "alt", "f"),), 0)
    service = GroundStationService(store=SessionStore(), schemas=[schema], source="sim")
    service.start()
    with tempfile.TemporaryDirectory() as td:
        tm = TerminalManager(state_dir=Path(td))
        api = ApiServer(service, host="127.0.0.1", port=0, terminal_manager=tm)
        api.start()
        try:
            port = api.address[1]
            token = tm.get_token()
            status, accept_hdr, sock = _ws_handshake("127.0.0.1", port, token)
            try:
                assert status == 101, f"expected 101, got {status}"
                assert accept_hdr, "missing Sec-WebSocket-Accept header"
                # Verify the accept value matches the RFC 6455 formula
                import hashlib, base64
                guide = "258EAFA5-E914-47DA-95CA-5AB5DC59B3FF"
                expected = base64.b64encode(
                    hashlib.sha1(("dGhlIHNhbXBsZSBub25jZQ==" + guide).encode()).digest()
                ).decode()
                assert accept_hdr == expected, (
                    f"accept mismatch: {accept_hdr!r} != {expected!r}"
                )
            finally:
                # Close the socket to end the PTY session
                try:
                    sock.close()
                except Exception:
                    pass
        finally:
            api.stop()
            service.stop()


def test_terminal_ws_echo_t12b_ok():
    """Good token -> 101, verify full handshake + shell I/O.

    On Windows without PTY the fallback is a pipe-backed shell.  The full
    echo test is skipped on Windows where pipe-based PTY support is limited;
    the 101 handshake test already validates the core protocol.
    """
    from ground_station.service.terminal import TerminalManager, _IS_WINDOWS
    schema = StreamSchema(1, 1, 4,
                          (StreamRange(0x20000000, 4, 1, "alt", "f"),), 0)
    service = GroundStationService(store=SessionStore(), schemas=[schema], source="sim")
    service.start()
    with tempfile.TemporaryDirectory() as td:
        tm = TerminalManager(state_dir=Path(td))
        api = ApiServer(service, host="127.0.0.1", port=0, terminal_manager=tm)
        api.start()
        try:
            port = api.address[1]
            token = tm.get_token()
            status, _, sock = _ws_handshake("127.0.0.1", port, token)
            try:
                assert status == 101
                # On Unix with PTY, do the full echo test.
                # On Windows the pipe-based fallback is limited, so just
                # verify the handshake completed successfully.
                if not _IS_WINDOWS:
                    import time
                    time.sleep(0.5)
                    _ws_send_text(sock, "echo t12b-ok\n")
                    sock.settimeout(10)
                    response = _ws_recv_text(sock)
                    assert "t12b-ok" in response, (
                        f"expected 't12b-ok' in response, got: {response!r}"
                    )
            finally:
                try:
                    sock.close()
                except Exception:
                    pass
        finally:
            api.stop()
            service.stop()
