"""Generate the firmware and host platform registry from one YAML source."""
from __future__ import annotations

import argparse
import json
import zlib
from collections import Counter
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
KINDS = ("variable", "enum", "parameter", "command", "telemetry", "event", "plugin", "task", "resource")
KIND_ID = {name: i + 1 for i, name in enumerate(KINDS)}
TYPE_ID = {name: i + 1 for i, name in enumerate((
    "u8", "u32", "u32_array", "f32", "enum_u8", "frame_0x01", "frame_0x02",
    "frame_0x06", "frame_0x09", "event", "controller", "adaptive", "estimator",
    "freertos_task", "uart_dma", "ring", "heap"))}
PERM_ID = {"read": 1, "read_write": 3, "execute": 4}
SAFETY_ID = {"observation": 0, "diagnostic": 1, "operational": 2, "boundary": 3, "critical": 4}


def load_registry(path: Path) -> dict:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    seen: set[tuple[str, int]] = set()
    for row in raw["descriptors"]:
        if row["kind"] not in KIND_ID:
            raise ValueError(f"unknown kind {row['kind']}")
        key = (row["kind"], int(row["id"]))
        if key in seen:
            raise ValueError(f"duplicate descriptor {key}")
        seen.add(key)
        if row["type"] not in TYPE_ID:
            raise ValueError(f"unknown type {row['type']}")
        if row["permissions"] not in PERM_ID or row["safety"] not in SAFETY_ID:
            raise ValueError(f"bad permission/safety for {row['name']}")
    return raw


def canonical_payload(raw: dict) -> dict:
    return {
        "registry_version": int(raw["registry_version"]),
        "schema_version": int(raw["schema_version"]),
        "hardware_id": int(raw["hardware_id"], 0) if isinstance(raw["hardware_id"], str) else int(raw["hardware_id"]),
        "capabilities": list(raw["capabilities"]),
        "descriptors": raw["descriptors"],
    }


def digest(payload: dict) -> int:
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return zlib.crc32(encoded) & 0xFFFFFFFF


def emit_header(payload: dict, crc: int, path: Path) -> None:
    counts = Counter(r["kind"] for r in payload["descriptors"])
    lines = [
        "/* AUTO-GENERATED by scripts/generate_platform_registry.py. */",
        "#ifndef PLATFORM_REGISTRY_GEN_H", "#define PLATFORM_REGISTRY_GEN_H", "",
        f"#define PLATFORM_REGISTRY_VERSION {payload['registry_version']}U",
        f"#define PLATFORM_SCHEMA_VERSION {payload['schema_version']}U",
        f"#define PLATFORM_HARDWARE_ID 0x{payload['hardware_id']:04X}U",
        f"#define PLATFORM_REGISTRY_CRC32 0x{crc:08X}U",
        f"#define PLATFORM_DESCRIPTOR_COUNT {len(payload['descriptors'])}U",
        f"#define PLATFORM_CAPABILITY_COUNT {len(payload['capabilities'])}U",
        "#define PLATFORM_KIND_COUNT 9U", "",
    ]
    for name, ident in KIND_ID.items():
        lines.append(f"#define PLATFORM_KIND_{name.upper()} {ident}U")
        lines.append(f"#define PLATFORM_COUNT_{name.upper()} {counts[name]}U")
    lines += ["", "extern const PlatformDescriptor_t g_platform_descriptors[PLATFORM_DESCRIPTOR_COUNT];",
              "extern const PlatformKindSummary_t g_platform_kind_summaries[PLATFORM_KIND_COUNT];", "",
              "#endif"]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def milli(value) -> int:
    return int(round(float(value) * 1000.0))


def emit_c(payload: dict, path: Path) -> None:
    rows = payload["descriptors"]
    counts = Counter(r["kind"] for r in rows)
    lines = ["/* AUTO-GENERATED by scripts/generate_platform_registry.py. */",
             '#include "platform_registry.h"', '#include "platform_registry_gen.h"', "",
             "const PlatformDescriptor_t g_platform_descriptors[PLATFORM_DESCRIPTOR_COUNT] = {"]
    for r in rows:
        lines.append(
            '    { %dU, %dU, %dU, %d, 1000, %d, %d, %dU, %dU, %dU, 0x%08XU, %dU, "%s", "%s", "%s" },' % (
                int(r["id"]), KIND_ID[r["kind"]], TYPE_ID[r["type"]], milli(r["scale"]),
                milli(r["min"]), milli(r["max"]), int(r["rate_hz"]), PERM_ID[r["permissions"]],
                SAFETY_ID[r["safety"]], int(r["dependencies"]), int(r["version"]),
                r["name"], r["unit"], r["owner"])
        )
    lines += ["};", "", "const PlatformKindSummary_t g_platform_kind_summaries[PLATFORM_KIND_COUNT] = {"]
    for name, ident in KIND_ID.items():
        lines.append(f"    {{ {ident}U, 0U, {counts[name]}U }},")
    lines += ["};", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def emit_json(payload: dict, crc: int, path: Path) -> None:
    out = dict(payload)
    out["registry_crc32"] = f"0x{crc:08X}"
    out["descriptor_count"] = len(payload["descriptors"])
    out["kind_counts"] = dict(Counter(r["kind"] for r in payload["descriptors"]))
    path.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")


def emit_telemetry_schema(payload: dict, crc: int, path: Path) -> None:
    """Emit the typed telemetry view consumed by the ground station.

    Keeping this projection generated from the same registry prevents a host
    decoder from silently accepting a stream from a different schema revision.
    The wire stream still carries its legacy 0x08/0x09 envelope; the registry
    identity is the out-of-band contract used when selecting a subscription.
    """
    streams = [
        {
            "id": int(row["id"]),
            "name": row["name"],
            "type": row["type"],
            "unit": row["unit"],
            "owner": row["owner"],
            "rate_hz": int(row["rate_hz"]),
            "version": int(row["version"]),
            "dependencies": int(row["dependencies"]),
        }
        for row in payload["descriptors"] if row["kind"] == "telemetry"
    ]
    out = {
        "format": "uav-typed-telemetry",
        "format_version": 1,
        "registry_version": payload["registry_version"],
        "schema_version": payload["schema_version"],
        "registry_crc32": f"0x{crc:08X}",
        "streams": streams,
    }
    path.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")


def emit_markdown(payload: dict, crc: int, path: Path) -> None:
    lines = ["# Generated platform registry", "", f"Registry version: {payload['registry_version']}",
             f"Schema version: {payload['schema_version']}", f"Registry CRC32: `0x{crc:08X}`", "",
             "| Kind | ID | Name | Type | Unit | Owner | Rate | Permissions | Safety | Version |",
             "|---|---:|---|---|---|---|---:|---|---|---:|"]
    for r in payload["descriptors"]:
        lines.append(f"| {r['kind']} | {r['id']} | `{r['name']}` | {r['type']} | {r['unit']} | {r['owner']} | {r['rate_hz']} | {r['permissions']} | {r['safety']} | {r['version']} |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def generate(source: Path, check: bool = False) -> int:
    payload = canonical_payload(load_registry(source))
    crc = digest(payload)
    outputs = {
        ROOT / "firmware/platform_registry_gen.h": lambda p: emit_header(payload, crc, p),
        ROOT / "firmware/platform_registry_gen.c": lambda p: emit_c(payload, p),
        ROOT / "ground_station/generated/platform_registry.json": lambda p: emit_json(payload, crc, p),
        ROOT / "ground_station/generated/telemetry_schema.json": lambda p: emit_telemetry_schema(payload, crc, p),
        ROOT / "docs/dashboard-platform/generated/platform-registry.md": lambda p: emit_markdown(payload, crc, p),
    }
    for target, writer in outputs.items():
        target.parent.mkdir(parents=True, exist_ok=True)
        if check:
            tmp = target.with_suffix(target.suffix + ".check")
            writer(tmp)
            expected = tmp.read_bytes()
            tmp.unlink()
            if not target.exists() or target.read_bytes() != expected:
                raise SystemExit(f"generated file is stale: {target.relative_to(ROOT)}")
        else:
            writer(target)
    print(f"platform registry: {len(payload['descriptors'])} descriptors, crc=0x{crc:08X}")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", type=Path, default=ROOT / "registry/platform_registry.yaml")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    return generate(args.source, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
