# Extract of Adaptive_Control_Tutorial.ipynb
# Generated by ground_station/research/notebooks/extract.py; do not edit.

# %% [cell 0] code
# fixed gain example (no adptation)

ft = 20 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 1 # initial state
w = 5 # unknown weight

#k = 5.1 # fixed gain
#k = 6 
k = 10

x_rec = [] # state record
u_rec = [] # control record
t_rec = [] # time record

for t in range(int(ft/dt)):
    time = t*dt
    u = -k*x # control law
    x = x + dt*(w*x + u) # system dynamics

    # record data
    x_rec.append(x)
    u_rec.append(u)
    t_rec.append(time)

# plot results
import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.subplot(2,1,1)
plt.plot(t_rec, x_rec)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.grid()
plt.subplot(2,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()
plt.tight_layout()

# >> [image dropped]
# >> <Figure size 1000x500 with 2 Axes>

# %% [cell 1] code
# Adaptive gain example

ft = 20 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 1 # initial state
what = 0
w = 5 # unknown weight

#gamma = 1 # adaptation gain
#gamma = 5 # adaptation gain
gamma = 25 # adaptation gain

x_rec = [] # state record
u_rec = [] # control record
t_rec = [] # time record


for t in range(int(ft/dt)):
    u = -what*x # control law
    what = what + dt*gamma*x*x # weight adaptation
    x = x + dt*(w*x + u) # system dynamics

    # record data
    x_rec.append(x)
    u_rec.append(u)
    t_rec.append(t)
# plot results
import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.subplot(2,1,1)
plt.plot(t_rec, x_rec)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.grid()
plt.subplot(2,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()
plt.tight_layout()
# >> [image dropped]
# >> <Figure size 1000x500 with 2 Axes>

# %% [cell 2] code
# Point reference adaptive gain example

ft = 20 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 0 # initial state
what = 0
w = 1 # unknown weight

alp = 2 # nominal control gain
gamma = 50 # adaptation gain

x_rec = [] # state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record

for t in range(int(ft/dt)):
    time = t*dt
    xr = 1 # reference point
    if time <= 5 :
        c = 1
    else :
        c = -1
    e = x - c # tracking error
    u = -alp*e - what*x # control law
    what = what + dt*gamma*x*e # weight adaptation
    x = x + dt*(w*x + u) # system dynamics

    # record data
    x_rec.append(x)
    u_rec.append(u)
    t_rec.append(time)
    w_rec.append(what)

# plot results
import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))
plt.subplot(3,1,1)
plt.plot(t_rec, x_rec, label='State x')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=5, color='k', linestyle=':', alpha=0.5)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.legend()
plt.grid()

plt.subplot(3,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(3,1,3)
plt.plot(t_rec, w_rec)
plt.title('Estimated Weight over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weight ŵ')
plt.grid()

plt.tight_layout()
# >> [image dropped]
# >> <Figure size 1000x800 with 3 Axes>

# %% [cell 3] code
# reference model adaptive gain example

ft = 20 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 0 # initial state
xr = 0 # reference model state
what = 0
w = 1 # unknown weight

alp = 2 # nominal control gain
gamma = 50 # adaptation gain

x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record

for t in range(int(ft/dt)):
    time = t*dt

    if time <= 5 :
        c = 1
    else :
        c = -1

    xr = xr + dt*(-alp*(xr - c)) # reference model update
    u = -alp*(x-c) - what*x # control law
    what = what + dt*gamma*x*(x - xr) # weight adaptation
    x = x + dt*(w*x + u) # system dynamics

    # record data
    x_rec.append(x)
    xr_rec.append(xr)
    u_rec.append(u)
    t_rec.append(time)
    w_rec.append(what)

# plot results
import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))
plt.subplot(3,1,1)
plt.plot(t_rec, x_rec, label='State x')
plt.plot(t_rec, xr_rec, label='Reference Model x_r', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=5, color='k', linestyle=':', alpha=0.5)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.legend()
plt.grid()

plt.subplot(3,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(3,1,3)
plt.plot(t_rec, w_rec)
plt.title('Estimated Weight over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weight ŵ')
plt.grid()

plt.tight_layout()
# >> [image dropped]
# >> <Figure size 1000x800 with 3 Axes>

# %% [cell 4] code
# Projection operator example
import numpy as np
import matplotlib.pyplot as plt

ft = 10 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 0 # initial state
xr = 0 # reference model state
what = 0 # initial weight

alp = 2 # nominal control gain
gam = 50 # adaptation gain
wbd = 5 # weight bound max and min
eps = 0.2 # projection tolerance

x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record
w_true_rec = [] # true weight record

for t in range(int(ft/dt)):
    time = t*dt
    w = 1.5 + 0.25 * np.cos(0.5*time) # time-varying unknown weight

    if time <= 5 :
        c = 1
    else :
        c = -1

    u = -alp*(x - c) - what*x # control law
    xr = xr + dt*(-alp*(xr - c)) # reference model update

    # weight adaptation with projection
    PR = x*(x - xr)
    if what > wbd - eps and PR > 0:
        PR = (wbd - what)/eps * PR
    elif what < -wbd + eps and PR < 0:
        PR = (what + wbd)/eps * PR
    what = what + dt*gam*PR

    x = x + dt*(w*x + u) # system dynamics

    # record data
    x_rec.append(x)
    xr_rec.append(xr)
    u_rec.append(u)
    t_rec.append(time)
    w_rec.append(what)
    w_true_rec.append(w)

# plot results
import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))
plt.subplot(3,1,1)
plt.plot(t_rec, x_rec, label='State x')
plt.plot(t_rec, xr_rec, label='Reference Model x_r', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=5, color='k', linestyle=':', alpha=0.5)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.legend()
plt.grid()

plt.subplot(3,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(3,1,3)
plt.plot(t_rec, w_rec)
plt.plot(t_rec, w_true_rec, label='True Weight w', linestyle='--')
plt.title('Estimated Weight over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weight ŵ')
plt.grid()

plt.tight_layout()
# >> [image dropped]
# >> <Figure size 1000x800 with 3 Axes>

# %% [cell 5] code
# sigma modification example
import numpy as np
import matplotlib.pyplot as plt

ft = 10 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 0 # initial state
xr = 0 # reference model state
what = 0 # initial weight

alp = 2 # nominal control gain
gam = 50 # adaptation gain
sigma = 0.5 # sigma modification gain
wbd = 2 # weight bound max and min
eps = 0.2 # projection tolerance

x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record
w_true_rec = [] # true weight record

for t in range(int(ft/dt)):
    time = t*dt
    w = 1.5 + 0.25 * np.cos(0.5*time) # time-varying unknown weight

    if time <= 5 :
        c = 1
    else :
        c = -1

    u = -alp*(x - c) - what*x # control law
    xr = xr + dt*(-alp*(xr - c)) # reference model update

    # weight adaptation with sigma leakage
    what = what + dt*(gamma*(x*(x-xr) - sigma*what))


    x = x + dt*(w*x + u) # system dynamics

    # record data
    x_rec.append(x)
    xr_rec.append(xr)
    u_rec.append(u)
    t_rec.append(time)
    w_rec.append(what)
    w_true_rec.append(w)

# plot results
import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))
plt.subplot(3,1,1)
plt.plot(t_rec, x_rec, label='State x')
plt.plot(t_rec, xr_rec, label='Reference Model x_r', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=5, color='k', linestyle=':', alpha=0.5)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.legend()
plt.grid()

plt.subplot(3,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(3,1,3)
plt.plot(t_rec, w_rec)
plt.plot(t_rec, w_true_rec, label='True Weight w', linestyle='--')
plt.title('Estimated Weight over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weight ŵ')
plt.grid()

plt.tight_layout()


# >> [image dropped]
# >> <Figure size 1000x800 with 3 Axes>

# %% [cell 6] code
# e modification example
import numpy as np
import matplotlib.pyplot as plt

ft = 10 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 0 # initial state
xr = 0 # reference model state
what = 0 # initial weight

alp = 2 # nominal control gain
gam = 50 # adaptation gain
sigma = 2 # sigma modification gain
wbd = 2 # weight bound max and min
eps = 0.2 # projection tolerance

x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record
w_true_rec = [] # true weight record

for t in range(int(ft/dt)):
    time = t*dt
    w = 1.5 + 0.25 * np.cos(0.5*time) # time-varying unknown weight

    if time <= 5 :
        c = 1
    else :
        c = -1

    u = -alp*(x - c) - what*x # control law
    xr = xr + dt*(-alp*(xr - c)) # reference model update

    # weight adaptation with sigma leakage
    what = what + dt*(gam*(x*(x-xr) - sigma*abs(x-xr)*what))


    x = x + dt*(w*x + u) # system dynamics

    # record data
    x_rec.append(x)
    xr_rec.append(xr)
    u_rec.append(u)
    t_rec.append(time)
    w_rec.append(what)
    w_true_rec.append(w)

# plot results
import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))
plt.subplot(3,1,1)
plt.plot(t_rec, x_rec, label='State x')
plt.plot(t_rec, xr_rec, label='Reference Model x_r', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=5, color='k', linestyle=':', alpha=0.5)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.legend()
plt.grid()

plt.subplot(3,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(3,1,3)
plt.plot(t_rec, w_rec)
plt.plot(t_rec, w_true_rec, label='True Weight w', linestyle='--')
plt.title('Estimated Weight over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weight ŵ')
plt.grid()

plt.tight_layout()

# >> [image dropped]
# >> <Figure size 1000x800 with 3 Axes>

# %% [cell 7] code
# Neuro-adaptive control example 6 neurons with sigma modification
import numpy as np
import matplotlib.pyplot as plt

ft = 20 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 0 # initial state
xr = 0 # reference model state
what = np.zeros((6,1)) # initial weight

alp = 2 # nominal control gain
gam = 50 # adaptation gain
sigma = 0.2 # sigma modification gain

def rbf(x, d1, d2):
    return np.exp(-d1*abs(x - d2)**2)
    
x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record
ua_rec = [] # neural network control record
delta_rec = [] # nonlinearity record


for t in range(int(ft/dt)):
    time = t*dt
    
    delta = 1 + x**2 + np.sin(x)*x**3 + np.cos(x)*x**4 # unknown nonlinearity

    if time <= 5 :
        c = 1
    elif 5 < time <= 10 :
        c = -1
    elif 10 < time <= 15 :
        c = 1
    else :
        c = -1

    theta = np.zeros_like(what)
    for i in range(len(what)):
        theta[i] = rbf(x, 0.1, -5 + i*2) # RBFs centered at -5, -3, -1, 1, 3, 5

    un = -alp*(x - c) # nominal control
    ua = -what.T @ theta # neural network control
    u = un + ua # total control input
    xr = xr + dt*(-alp*(xr - c)) # reference model update

    what = what + dt*(gam*(theta*(x - xr) - sigma*what)) # weight adaptation with sigma leakage

    x = x + dt*(delta + u) # system dynamics

    # record data
    x_rec.append(float(x))
    xr_rec.append(xr)
    u_rec.append(float(u))
    t_rec.append(time)
    w_rec.append(what.flatten())
    ua_rec.append(float(ua))
    delta_rec.append(float(delta))

# plot results
plt.figure(figsize=(10,12))
plt.subplot(4,1,1)
plt.plot(t_rec, x_rec, label='State x')
plt.plot(t_rec, xr_rec, label='Reference Model x_r', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=5, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=15, color='k', linestyle=':', alpha=0.5)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.legend()
plt.grid()

plt.subplot(4,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(4,1,3)
for i in range(len(what)):
    w_i = [w[i] for w in w_rec]
    plt.plot(t_rec, w_i, label=f'Weight ŵ[{i}]')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights ŵ')
plt.legend()
plt.grid()

plt.subplot(4,1,4)
plt.plot(t_rec, [-u for u in ua_rec], label='Estimated Nonlinearity (-u_a)')
plt.plot(t_rec, delta_rec, label='True Nonlinearity delta', linestyle='--')
plt.title('Nonlinearity Estimation vs True Nonlinearity')
plt.xlabel('Time [s]')
plt.ylabel('Value')
plt.legend()
plt.grid()

plt.tight_layout()
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1496885924.py:56: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   x_rec.append(float(x))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1496885924.py:58: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   u_rec.append(float(u))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1496885924.py:61: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   ua_rec.append(float(ua))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1496885924.py:62: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   delta_rec.append(float(delta))
# >> [image dropped]
# >> <Figure size 1000x1200 with 4 Axes>

# %% [cell 8] code
# Neuro-adaptive control example 6 neurons with bias term
import numpy as np
import matplotlib.pyplot as plt

ft = 20 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 0 # initial state
xr = 0 # reference model state
what = np.zeros((7,1)) # initial weight

alp = 2 # nominal control gain
gam = 50 # adaptation gain
sigma = 0.2 # sigma modification gain

def rbf(x, d1, d2):
    return np.exp(-d1*abs(x - d2)**2)
    
x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record
ua_rec = [] # neural network control record
delta_rec = [] # nonlinearity record


for t in range(int(ft/dt)):
    time = t*dt
    
    delta = 1 + x**2 + np.sin(x)*x**3 + np.cos(x)*x**4 # unknown nonlinearity

    if time <= 5 :
        c = 1
    elif 5 < time <= 10 :
        c = -1
    elif 10 < time <= 15 :
        c = 1
    else :
        c = -1

    theta = np.zeros_like(what)
    for i in range(len(what)):
        if i < len(what)-1:
            theta[i] = rbf(x, 0.1, -5 + i*2) # RBFs centered at -5, -3, -1, 1, 3, 5
        else:
            theta[i] = 1 # bias term

    un = -alp*(x - c) # nominal control
    ua = -what.T @ theta # neural network control
    u = un + ua # total control input
    xr = xr + dt*(-alp*(xr - c)) # reference model update

    what = what + dt*(gam*(theta*(x - xr) - sigma*what)) # weight adaptation with sigma leakage

    x = x + dt*(delta + u) # system dynamics

    # record data
    x_rec.append(float(x))
    xr_rec.append(xr)
    u_rec.append(float(u))
    t_rec.append(time)
    w_rec.append(what.flatten())
    ua_rec.append(float(ua))
    delta_rec.append(float(delta))

# plot results
plt.figure(figsize=(10,12))
plt.subplot(4,1,1)
plt.plot(t_rec, x_rec, label='State x')
plt.plot(t_rec, xr_rec, label='Reference Model x_r', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=5, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=15, color='k', linestyle=':', alpha=0.5)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.legend()
plt.grid()

plt.subplot(4,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(4,1,3)
for i in range(len(what)):
    w_i = [w[i] for w in w_rec]
    plt.plot(t_rec, w_i, label=f'Weight ŵ[{i}]')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights ŵ')
plt.legend()
plt.grid()

plt.subplot(4,1,4)
plt.plot(t_rec, [-u for u in ua_rec], label='Estimated Nonlinearity (-u_a)')
plt.plot(t_rec, delta_rec, label='True Nonlinearity delta', linestyle='--')
plt.title('Nonlinearity Estimation vs True Nonlinearity')
plt.xlabel('Time [s]')
plt.ylabel('Value')
plt.legend()
plt.grid()

plt.tight_layout()
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\2390978168.py:59: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   x_rec.append(float(x))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\2390978168.py:61: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   u_rec.append(float(u))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\2390978168.py:64: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   ua_rec.append(float(ua))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\2390978168.py:65: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   delta_rec.append(float(delta))
# >> [image dropped]
# >> <Figure size 1000x1200 with 4 Axes>

# %% [cell 9] code
# Neuro-adaptive control example with 12 neurons and bias term
import numpy as np
import matplotlib.pyplot as plt

ft = 20 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 0 # initial state
xr = 0 # reference model state
what = np.zeros((12,1)) # initial weight

alp = 2 # nominal control gain
gam = 50 # adaptation gain
sigma = 0.2 # sigma modification gain

def rbf(x, d1, d2):
    return np.exp(-d1*abs(x - d2)**2)
    
x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record
ua_rec = [] # neural network control record
delta_rec = [] # nonlinearity record


for t in range(int(ft/dt)):
    time = t*dt
    
    delta = 1 + x**2 + np.sin(x)*x**3 + np.cos(x)*x**4 # unknown nonlinearity

    if time <= 5 :
        c = 1
    elif 5 < time <= 10 :
        c = -1
    elif 10 < time <= 15 :
        c = 1
    else :
        c = -1

    theta = np.zeros_like(what)
    for i in range(len(what)):
        if i < len(what)-1:
            theta[i] = rbf(x, 0.1, -5 + i*2) # RBFs centered at -5, -3, -1, 1, 3, 5
        else:
            theta[i] = 1 # bias term

    un = -alp*(x - c) # nominal control
    ua = -what.T @ theta # neural network control
    u = un + ua # total control input
    xr = xr + dt*(-alp*(xr - c)) # reference model update

    what = what + dt*(gam*(theta*(x - xr) - sigma*what)) # weight adaptation with sigma leakage

    x = x + dt*(delta + u) # system dynamics

    # record data
    x_rec.append(float(x))
    xr_rec.append(xr)
    u_rec.append(float(u))
    t_rec.append(time)
    w_rec.append(what.flatten())
    ua_rec.append(float(ua))
    delta_rec.append(float(delta))

# plot results
plt.figure(figsize=(10,12))
plt.subplot(4,1,1)
plt.plot(t_rec, x_rec, label='State x')
plt.plot(t_rec, xr_rec, label='Reference Model x_r', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=5, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=15, color='k', linestyle=':', alpha=0.5)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.legend()
plt.grid()

plt.subplot(4,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(4,1,3)
for i in range(len(what)):
    w_i = [w[i] for w in w_rec]
    plt.plot(t_rec, w_i, label=f'Weight ŵ[{i}]')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights ŵ')
plt.legend()
plt.grid()

plt.subplot(4,1,4)
plt.plot(t_rec, [-u for u in ua_rec], label='Estimated Nonlinearity (-u_a)')
plt.plot(t_rec, delta_rec, label='True Nonlinearity delta', linestyle='--')
plt.title('Nonlinearity Estimation vs True Nonlinearity')
plt.xlabel('Time [s]')
plt.ylabel('Value')
plt.legend()
plt.grid()

plt.tight_layout()
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\2605645300.py:59: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   x_rec.append(float(x))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\2605645300.py:61: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   u_rec.append(float(u))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\2605645300.py:64: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   ua_rec.append(float(ua))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\2605645300.py:65: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   delta_rec.append(float(delta))
# >> [image dropped]
# >> <Figure size 1000x1200 with 4 Axes>

# %% [cell 10] code
# Neuro-adaptive control example with 21 neurons and bias term
import numpy as np
import matplotlib.pyplot as plt

ft = 20 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 0 # initial state
xr = 0 # reference model state
what = np.zeros((22,1)) # initial weight

alp = 2 # nominal control gain
gam = 50 # adaptation gain
sigma = 0.2 # sigma modification gain

def rbf(x, d1, d2):
    return np.exp(-d1*abs(x - d2)**2)
    
x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record
ua_rec = [] # neural network control record
delta_rec = [] # nonlinearity record


for t in range(int(ft/dt)):
    time = t*dt
    
    delta = 1 + x**2 + np.sin(x)*x**3 + np.cos(x)*x**4 # unknown nonlinearity

    if time <= 5 :
        c = 1
    elif 5 < time <= 10 :
        c = -1
    elif 10 < time <= 15 :
        c = 1
    else :
        c = -1

    theta = np.zeros_like(what)
    for i in range(len(what)):
        if i < len(what)-1:
            theta[i] = rbf(x, 0.25, -5 + i*0.5) # RBFs centered at -5, -4.5, ..., 5
        else:
            theta[i] = 2 # bias term

    un = -alp*(x - c) # nominal control
    ua = -what.T @ theta # neural network control
    u = un + ua # total control input
    xr = xr + dt*(-alp*(xr - c)) # reference model update

    what = what + dt*(gam*(theta*(x - xr) - sigma*what)) # weight adaptation with sigma leakage

    x = x + dt*(delta + u) # system dynamics

    # record data
    x_rec.append(float(x))
    xr_rec.append(xr)
    u_rec.append(float(u))
    t_rec.append(time)
    w_rec.append(what.flatten())
    ua_rec.append(float(ua))
    delta_rec.append(float(delta))

# plot results
plt.figure(figsize=(10,12))
plt.subplot(4,1,1)
plt.plot(t_rec, x_rec, label='State x')
plt.plot(t_rec, xr_rec, label='Reference Model x_r', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=5, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=15, color='k', linestyle=':', alpha=0.5)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.legend()
plt.grid()

plt.subplot(4,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(4,1,3)
for i in range(len(what)):
    w_i = [w[i] for w in w_rec]
    #plt.plot(t_rec, w_i, label=f'Weight ŵ[{i}]')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights ŵ')
plt.legend()
plt.grid()

plt.subplot(4,1,4)
plt.plot(t_rec, [-u for u in ua_rec], label='Estimated Nonlinearity (-u_a)')
plt.plot(t_rec, delta_rec, label='True Nonlinearity delta', linestyle='--')
plt.title('Nonlinearity Estimation vs True Nonlinearity')
plt.xlabel('Time [s]')
plt.ylabel('Value')
plt.legend()
plt.grid()

plt.tight_layout()
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1882671299.py:59: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   x_rec.append(float(x))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1882671299.py:61: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   u_rec.append(float(u))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1882671299.py:64: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   ua_rec.append(float(ua))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1882671299.py:65: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   delta_rec.append(float(delta))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1882671299.py:97: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
# >>   plt.legend()
# >> [image dropped]
# >> <Figure size 1000x1200 with 4 Axes>

# %% [cell 11] code
# Neuro-adaptive control example 6 neurons with sigma modification and Performance recovery
import numpy as np
import matplotlib.pyplot as plt

ft = 20 # simulation time in seconds
dt = 0.005 # time step in seconds

x = 0 # initial state
xr = 0 # reference model + recovery signal initial state
xri = 0 # reference model initial state
psi = 0 # time domain performance recovery signal initial state
what = np.zeros((6,1)) # initial weight

alp = 2 # nominal control gain
gam = 50 # adaptation gain
sigma = 0.2 # sigma modification gain
lam = 5 # performance recovery gain

def rbf(x, d1, d2):
    return np.exp(-d1*abs(x - d2)**2)
    
x_rec = [] # state record
xr_rec = [] # reference model state record
xri_rec = [] # ideal reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record
ua_rec = [] # neural network control record
delta_rec = [] # nonlinearity record
v_rec = [] # recovery control record
psi_rec = [] # performance recovery signal record


for t in range(int(ft/dt)):
    time = t*dt
    
    delta = 1 + x**2 + np.sin(x)*x**3 + np.cos(x)*x**4 # unknown nonlinearity

    if time <= 5 :
        c = 1
    elif 5 < time <= 10 :
        c = -1
    elif 10 < time <= 15 :
        c = 1
    else :
        c = -1

    theta = np.zeros_like(what)
    for i in range(len(what)):
        theta[i] = rbf(x, 0.1, -5 + i*2) # RBFs centered at -5, -3, -1, 1, 3, 5

    un = -alp*(x - c) # nominal control
    ua = -what.T @ theta # neural network control
    psi = psi + dt*(-lam*(psi - (x-xr))) # performance recovery signal update
    v = lam*psi - (alp + lam)*(x - xr) # recovery control term
    u = un + ua + v # total control input + the recovery term
    xr = xr + dt*(-alp*(xr - c) + v ) # reference model update
    xri = xri + dt*(-alp*(xri - c)) # ideal reference model update

    what = what + dt*(gam*(theta*(x - xr) - sigma*what)) # weight adaptation with sigma leakage

    x = x + dt*(delta + u) # system dynamics

    # record data
    x_rec.append(float(x))
    xr_rec.append(float(xr))
    xri_rec.append(float(xri))
    u_rec.append(float(u))
    t_rec.append(time)
    w_rec.append(what.flatten())
    ua_rec.append(float(ua))
    delta_rec.append(float(delta))
    v_rec.append(float(v))
    psi_rec.append(float(psi))

# plot results
plt.figure(figsize=(10,15))
plt.subplot(5,1,1)
plt.plot(t_rec, x_rec, label='State x')
plt.plot(t_rec, xri_rec, label='Reference Model x_r', linestyle='--')
plt.plot(t_rec, xr_rec, label='Performance Recovery Model x_{r+}', linestyle=':')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=5, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=15, color='k', linestyle=':', alpha=0.5)
plt.title('State over Time')
plt.xlabel('Time [s]')
plt.ylabel('State x')
plt.legend()
plt.grid()

plt.subplot(5,1,2)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(5,1,3)
for i in range(len(what)):
    w_i = [w[i] for w in w_rec]
    plt.plot(t_rec, w_i, label=f'Weight ŵ[{i}]')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights ŵ')
plt.legend()
plt.grid()

plt.subplot(5,1,4)
plt.plot(t_rec, [-u for u in ua_rec], label='Estimated Nonlinearity (-u_a)')
plt.plot(t_rec, delta_rec, label='True Nonlinearity delta', linestyle='--')
plt.title('Nonlinearity Estimation vs True Nonlinearity')
plt.xlabel('Time [s]')
plt.ylabel('Value')
plt.legend()
plt.grid()

plt.subplot(5,1,5)
plt.plot(t_rec, v_rec, label='Recovery Control v')
plt.plot(t_rec, psi_rec, label='Performance Recovery Signal ψ', linestyle='--')
plt.title('Recovery Control over Time')
plt.xlabel('Time [s]')
plt.ylabel('Value')
plt.legend()
plt.grid()

plt.tight_layout()
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1226108390.py:65: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   x_rec.append(float(x))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1226108390.py:68: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   u_rec.append(float(u))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1226108390.py:71: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   ua_rec.append(float(ua))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1226108390.py:66: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   xr_rec.append(float(xr))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1226108390.py:72: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   delta_rec.append(float(delta))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1226108390.py:73: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   v_rec.append(float(v))
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_10116\1226108390.py:74: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
# >>   psi_rec.append(float(psi))
# >> [image dropped]
# >> <Figure size 1000x1500 with 5 Axes>

# %% [cell 12] code
# Mass-spring-damper system with adaptive control 2 dimensions
import numpy as np
import control as ct
import matplotlib.pyplot as plt

ft = 40 # simulation time in seconds
dt = 0.005 # time step in seconds

mass = 5.0 # mass
alpha = 2.5 # Spring constant
beta = 1.0 # Damping coefficient
A = np.array([[0, 1], [0, 0]]) # A matrix of the system
B = np.array([[0], [1]]) # B matrix of the system
Lam = np.array([[1/mass]]) # Lambda
# True weight vector - represents the true parameters -alpha and -beta
# Uncertainty is W0.T @ x = -alpha*x - beta*v
W0 = np.array([[ -alpha ], [ -beta ]]) 
x = np.array([[0.], [0.]]) # initial state

K1, S, E = ct.lqr(A, B, np.eye(2), np.eye(1)*0.1) # LQR gain
# Note: K1 from ct.lqr might be matrix or array, ensure shape
K1 = np.asarray(K1)

# Feedforward gain
# Ar = A - B K1
Ar = A - B @ K1 # reference model A matrix
# K2 = -1 / (C Ar^-1 B) for C = [1 0]
C = np.array([[1, 0]])
K2 = -1.0 / (C @ np.linalg.inv(Ar) @ B).item()

Br = B * K2 # reference model B matrix
xr = np.array([[0.], [0.]]) # reference model initial state

gam = 10 # adaptation gain
# Solve Lyapunov for Ar^T P + P Ar = -I
P = ct.lyap(Ar.T, np.eye(2)) 
What = np.zeros((3,1)) # initial weight estimate - matches regressor size

x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record

for t in range(int(ft/dt)):
    time = t*dt

    if time <= 10 :
        c = 1
    elif 10 < time <= 20 :
        c = -1
    elif 20 < time <= 30 :
        c = 1
    else :
        c = -1

    
    un = -K1 @ x + K2 * c # nominal control   
    # Regressor is just the state [position, velocity**3, un]
    phi = np.vstack((x[0], x[1]**3, un))
    phi_r = np.vstack((xr[0], xr[1]**3))
    # Adaptive control law
    ua = -What.T @ phi 
    u = un + ua 


    # Reference model update
    xr = xr + dt*(Ar @ xr + Br * c)
    e = x - xr
    # Weights adaptation update
    What = What + dt*(gam * phi @ (e.T @ P @ B)) 


    # System dynamics (True Equation)
    # xdot = A x + B Lam (u + W0.T @ phi)
    # This corresponds to mass*xdd = u - alpha*x - beta*v
    x = x + dt*(A @ x + B @ Lam @ (u + W0.T @ phi_r)) 

    # record data
    x_rec.append(x.flatten())
    xr_rec.append(xr.flatten())
    u_rec.append(u.item())
    t_rec.append(time)
    w_rec.append(What.flatten())

# plot results
plt.figure(figsize=(10,12))
plt.subplot(4,1,1)
plt.plot(t_rec, [x[0] for x in x_rec], label='Position x[0]')
plt.plot(t_rec, [xr[0] for xr in xr_rec], label='Reference Model x_r[0]', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Position over Time')
plt.xlabel('Time [s]')
plt.ylabel('Position x[0]')
plt.legend()
plt.grid()
plt.subplot(4,1,2)
plt.plot(t_rec, [x[1] for x in x_rec], label='Velocity x[1]')
plt.plot(t_rec, [xr[1] for xr in xr_rec], label='Reference Model x_r[1]', linestyle='--')
plt.axhline(y=0, color='k', linestyle='--')
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Velocity over Time')
plt.xlabel('Time [s]')
plt.ylabel('Velocity x[1]')
plt.legend()
plt.grid()

plt.subplot(4,1,3)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(4,1,4)
for i in range(len(What)):
    w_i = [w[i] for w in w_rec]
    plt.plot(t_rec, w_i, label=f'Weight Ŵ[{i}]')
plt.hlines([-alpha, -beta], t_rec[0], t_rec[-1], colors='r', linestyles='--', label='True Weights')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights Ŵ')
plt.legend()
plt.grid()

plt.tight_layout()
# >> [image dropped]
# >> <Figure size 1000x1200 with 4 Axes>

# %% [cell 13] code
# Mass-spring-damper system with adaptive control 2 dimensions 
# with 5 neurons RBF for each state plus a bias term
import numpy as np
import control as ct
import matplotlib.pyplot as plt

ft = 40 # simulation time in seconds
dt = 0.005 # time step in seconds

A = np.array([[0, 1], [0, 0]]) # A matrix of the system (Double Integrator)
B = np.array([[0], [1]]) # B matrix of the system
Lam = np.array([[0.75]]) # True Lambda (Input Gain)
x = np.array([[0.], [0.]]) # initial state

# LQR Design for Reference Model
K1, S, E = ct.lqr(A, B, np.eye(2), 0.1) 
K1 = np.asarray(K1)

# Reference Model Matrices: Ar = A - B*K1
Ar = A - B @ K1 
# Feedforward Gain K2 to ensure DC gain is 1
C = np.array([[1, 0]])
K2 = -1.0 / (C @ np.linalg.inv(Ar) @ B).item()
Br = B * K2 

xr = np.array([[0.], [0.]]) # reference model initial state

gam = 10 # adaptation gain
sig = 0.1 # sigma modification gain
P = ct.lyap(Ar.T, np.eye(2)) # Solve Lyapunov Equation

# Neural Network (RBF) Setup
# 12 Weights: 1 Bias + 5 for Position + 5 for Velocity + 1 for Input (Lambda adaptation)
What = np.zeros((12,1)) 

def rbf(x, c, width):
    return np.exp(-width * abs(x - c)**2)

x_rec = [] 
xr_rec = []
u_rec = [] 
t_rec = [] 
w_rec = [] 
unc_rec = [] 
ua_rec = []

for t in range(int(ft/dt)):
    time = t*dt

    # Reference Command
    if time <= 10 :
        c = 0.5
    elif 10 < time <= 20 :
        c = -0.5
    elif 20 < time <= 30 :
        c = 0.5
    else :
        c = -0.5
    
    un = -K1 @ x + K2 * c # nominal control

    # Construct Regressor (theta)
    theta = np.zeros((12, 1))
    
    # 0: Bias term
    theta[0] = 1.0 
    
    # 1-5: Position RBFs (Centered at 2, 1, 0, -1, -2 to match MATLAB)
    for i in range(5):
        center = 2.0 - i  # 2, 1, 0, -1, -2
        theta[i+1] = rbf(x[0], center, 0.25)
        
    # 6-10: Velocity RBFs (Centered at 2, 1, 0, -1, -2 to match MATLAB)
    for i in range(5):
        center = 2.0 - i  # 2, 1, 0, -1, -2
        theta[i+6] = rbf(x[1], center, 0.25)
        
    # 11: Control Input term (Compensates for Gain Uncertainty)
    theta[11] = un

    ua = -What.T @ theta # adaptive control
    u = un + ua # total control input

    xr = xr + dt*(Ar @ xr + Br * c) # reference model update
    What = What + dt*(gam * theta @ (x - xr).T @ P @ B - gam * sig * What) # weight adaptation with sigma modification


    x0 = x[0]
    x1 = x[1]
    # Arbitrary nonlinearity 
    uncertainty = 1.0 + x0**2 + x0**2 * x1**2 + np.sin(x0) * x1**3 + np.cos(x1) * x0**4
    
    x = x + dt * (A @ x + B * Lam * (u + uncertainty))

    # record data
    x_rec.append(x.flatten())
    xr_rec.append(xr.flatten())
    u_rec.append(u.item())
    t_rec.append(time)
    w_rec.append(What.flatten())
    unc_rec.append(uncertainty)
    ua_rec.append(ua.item())

# plot results
plt.figure(figsize=(10,15))
plt.subplot(5,1,1)
plt.plot(t_rec, [x[0] for x in x_rec], label='Position x[0]')
plt.plot(t_rec, [xr[0] for xr in xr_rec], label='Reference Model x_r[0]', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Position over Time')
plt.xlabel('Time [s]')
plt.ylabel('Position x[0]')
plt.legend()
plt.grid()

plt.subplot(5,1,2)
plt.plot(t_rec, [x[1] for x in x_rec], label='Velocity x[1]')
plt.plot(t_rec, [xr[1] for xr in xr_rec], label='Reference Model x_r[1]', linestyle='--')
plt.axhline(y=0, color='k', linestyle='--')
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Velocity over Time')
plt.xlabel('Time [s]')
plt.ylabel('Velocity x[1]')
plt.legend()
plt.grid()

plt.subplot(5,1,3)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(5,1,4)
for i in range(len(What)):
    w_i = [w[i] for w in w_rec]
    plt.plot(t_rec, w_i, label=f'Weight Ŵ[{i}]')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights Ŵ')
#plt.legend()
plt.grid()

plt.subplot(5,1,5)
plt.plot(t_rec, [-u for u in ua_rec], label='Estimated Uncertainty (-u_a)')
plt.plot(t_rec, unc_rec, label='True Uncertainty', linestyle='--')
plt.title('Uncertainty Estimation vs True Uncertainty')
plt.xlabel('Time [s]')
plt.ylabel('Value')
plt.legend()
plt.grid()

plt.tight_layout()

# >> [image dropped]
# >> <Figure size 1000x1500 with 5 Axes>

# %% [cell 14] code
# Mass-spring-damper system with adaptive control 2 dimensions 
# with 5 neurons joint RBF for each state plus a bias term

import numpy as np
import control as ct
import matplotlib.pyplot as plt

ft = 40 # simulation time in seconds
dt = 0.005 # time step in seconds

A = np.array([[0, 1], [0, 0]]) # A matrix of the system (Double Integrator)
B = np.array([[0], [1]]) # B matrix of the system
Lam = np.array([[0.75]]) # True Lambda (Input Gain)
x = np.array([[0.], [0.]]) # initial state

# LQR Design for Reference Model
K1, S, E = ct.lqr(A, B, np.eye(2), 0.1) 
K1 = np.asarray(K1)

# Reference Model Matrices: Ar = A - B*K1
Ar = A - B @ K1 
# Feedforward Gain K2 to ensure DC gain is 1
C = np.array([[1, 0]])
K2 = -1.0 / (C @ np.linalg.inv(Ar) @ B).item()
Br = B * K2 

xr = np.array([[0.], [0.]]) # reference model initial state

gam = 10 # adaptation gain
sig = 0.1 # sigma modification gain
P = ct.lyap(Ar.T, np.eye(2)) # Solve Lyapunov Equation

# Neural Network (RBF) Setup
# 27 Weights: 1 Bias + 5x5=25 coupled RBFs + 1 for Input (Lambda adaptation)
n_centers = 5
What = np.zeros((1 + n_centers*n_centers + 1, 1)) 

def rbf(x0, x1, c0, c1, width):
    return np.exp(-width * ((x0 - c0)**2 + (x1 - c1)**2))

x_rec = [] 
xr_rec = []
u_rec = [] 
t_rec = [] 
w_rec = [] 
unc_rec = [] 
ua_rec = []

for t in range(int(ft/dt)):
    time = t*dt

    # Reference Command
    if time <= 10 :
        c = 0.5
    elif 10 < time <= 20 :
        c = -0.5
    elif 20 < time <= 30 :
        c = 0.5
    else :
        c = -0.5
    
    un = -K1 @ x + K2 * c # nominal control

    # Construct Regressor (theta)
    theta = np.zeros_like(What)
    
    # 0: Bias term
    theta[0] = 1.0 
    
    # 1-25: Joint RBFs for Position and Velocity (5x5 grid)
    idx = 1
    for i in range(n_centers):
        center_x0 = 2.0 - i  # 2, 1, 0, -1, -2
        for j in range(n_centers):
            center_x1 = 2.0 - j  # 2, 1, 0, -1, -2
            theta[idx] = rbf(x[0], x[1], center_x0, center_x1, 0.01)
            idx += 1
        
    # 26: Control Input term (Compensates for Gain Uncertainty)
    theta[-1] = un

    ua = -What.T @ theta # adaptive control
    u = un + ua # total control input

    xr = xr + dt*(Ar @ xr + Br * c) # reference model update
    What = What + dt*(gam * theta @ (x - xr).T @ P @ B - gam * sig * What) # weight adaptation with sigma modification


    x0 = x[0]
    x1 = x[1]
    # Arbitrary nonlinearity 
    uncertainty = 1.0 + x0**2 + x0**2 * x1**2 + np.sin(x0) * x1**3 + np.cos(x1) * x0**4
    
    x = x + dt * (A @ x + B * Lam * (u + uncertainty))

    # record data
    x_rec.append(x.flatten())
    xr_rec.append(xr.flatten())
    u_rec.append(u.item())
    t_rec.append(time)
    w_rec.append(What.flatten())
    unc_rec.append(uncertainty)
    ua_rec.append(ua.item())

# plot results
plt.figure(figsize=(10,15))
plt.subplot(5,1,1)
plt.plot(t_rec, [x[0] for x in x_rec], label='Position x[0]')
plt.plot(t_rec, [xr[0] for xr in xr_rec], label='Reference Model x_r[0]', linestyle='--')
plt.axhline(y=0.5, color='r', linestyle='--', alpha=0.5)
plt.axhline(y=-0.5, color='r', linestyle='--', alpha=0.5)
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Position over Time')
plt.xlabel('Time [s]')
plt.ylabel('Position x[0]')
plt.legend()
plt.grid()

plt.subplot(5,1,2)
plt.plot(t_rec, [x[1] for x in x_rec], label='Velocity x[1]')
plt.plot(t_rec, [xr[1] for xr in xr_rec], label='Reference Model x_r[1]', linestyle='--')
plt.axhline(y=0, color='k', linestyle='--')
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Velocity over Time')
plt.xlabel('Time [s]')
plt.ylabel('Velocity x[1]')
plt.legend()
plt.grid()

plt.subplot(5,1,3)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(5,1,4)
for i in range(len(What)):
    w_i = [w[i] for w in w_rec]
    plt.plot(t_rec, w_i, label=f'Weight Ŵ[{i}]')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights Ŵ')
#plt.legend()
plt.grid()

plt.subplot(5,1,5)
plt.plot(t_rec, [-u for u in ua_rec], label='Estimated Uncertainty (-u_a)')
plt.plot(t_rec, unc_rec, label='True Uncertainty', linestyle='--')
plt.title('Uncertainty Estimation vs True Uncertainty')
plt.xlabel('Time [s]')
plt.ylabel('Value')
plt.legend()
plt.grid()

plt.tight_layout()

# >> [image dropped]
# >> <Figure size 1000x1500 with 5 Axes>

# %% [cell 15] code
# Mass-spring-damper system with adaptive control 2 dimensions with 9 neurons RBF for each state plus a bias term
import numpy as np
import control as ct
import matplotlib.pyplot as plt

ft = 40 # simulation time in seconds
dt = 0.005 # time step in seconds

A = np.array([[0, 1], [0, 0]]) # A matrix of the system (Double Integrator)
B = np.array([[0], [1]]) # B matrix of the system
Lam = np.array([[0.75]]) # True Lambda (Input Gain)
x = np.array([[0.], [0.]]) # initial state

# LQR Design for Reference Model
K1, S, E = ct.lqr(A, B, np.eye(2), 0.1) 
K1 = np.asarray(K1)

# Reference Model Matrices: Ar = A - B*K1
Ar = A - B @ K1 
# Feedforward Gain K2 to ensure DC gain is 1
C = np.array([[1, 0]])
K2 = -1.0 / (C @ np.linalg.inv(Ar) @ B).item()
Br = B * K2 

xr = np.array([[0.], [0.]]) # reference model initial state

gam = 1 # adaptation gain
sig = 0.1 # sigma modification gain
P = ct.lyap(Ar.T, np.eye(2)) # Solve Lyapunov Equation

# Neural Network (RBF) Setup
# 20 weight
n_centers = 5
What = np.zeros((n_centers * n_centers + 2,1)) 

def rbf(x, c, width):
    return np.exp(-width * abs(x - c)**2)

x_rec = [] 
xr_rec = []
u_rec = [] 
t_rec = [] 
w_rec = [] 
unc_rec = [] 
ua_rec = []

for t in range(int(ft/dt)):
    time = t*dt

    # Reference Command
    if time <= 10 :
        c = 0.5
    elif 10 < time <= 20 :
        c = -0.5
    elif 20 < time <= 30 :
        c = 0.5
    else :
        c = -0.5
    
    un = -K1 @ x + K2 * c # nominal control

    # Construct Regressor (theta)
    theta = np.zeros_like(What)
    
    # 0: Bias term
    theta[0] = 1.0 
    
    # 1-5: Position RBFs (Centered at -2, -1, 0, 1, 2)
    for i in range(len(What)-2):
        center_x0 = -2
        
    # 11: Control Input term (Compensates for Gain Uncertainty)
    theta[11] = un

    ua = -What.T @ theta # adaptive control
    u = un + ua # total control input

    xr = xr + dt*(Ar @ xr + Br * c) # reference model update
    What = What + dt*(gam * theta @ (x - xr).T @ P @ B - gam * sig * What) # weight adaptation with sigma modification


    x0 = x[0]
    x1 = x[1]
    # Arbitrary nonlinearity 
    uncertainty = 1.0 + x0**2 + x0**2 * x1**2 + np.sin(x0) * x1**3 + np.cos(x1) * x0**4
    
    x = x + dt * (A @ x + B * Lam * (u + uncertainty))

    # record data
    x_rec.append(x.flatten())
    xr_rec.append(xr.flatten())
    u_rec.append(u.item())
    t_rec.append(time)
    w_rec.append(What.flatten())
    unc_rec.append(uncertainty)
    ua_rec.append(ua.item())

# plot results
plt.figure(figsize=(10,15))
plt.subplot(5,1,1)
plt.plot(t_rec, [x[0] for x in x_rec], label='Position x[0]')
plt.plot(t_rec, [xr[0] for xr in xr_rec], label='Reference Model x_r[0]', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Position over Time')
plt.xlabel('Time [s]')
plt.ylabel('Position x[0]')
plt.legend()
plt.grid()

plt.subplot(5,1,2)
plt.plot(t_rec, [x[1] for x in x_rec], label='Velocity x[1]')
plt.plot(t_rec, [xr[1] for xr in xr_rec], label='Reference Model x_r[1]', linestyle='--')
plt.axhline(y=0, color='k', linestyle='--')
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Velocity over Time')
plt.xlabel('Time [s]')
plt.ylabel('Velocity x[1]')
plt.legend()
plt.grid()

plt.subplot(5,1,3)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(5,1,4)
for i in range(len(What)):
    w_i = [w[i] for w in w_rec]
    plt.plot(t_rec, w_i, label=f'Weight Ŵ[{i}]')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights Ŵ')
#plt.legend()
plt.grid()

plt.subplot(5,1,5)
plt.plot(t_rec, [-u for u in ua_rec], label='Estimated Uncertainty (-u_a)')
plt.plot(t_rec, unc_rec, label='True Uncertainty', linestyle='--')
plt.title('Uncertainty Estimation vs True Uncertainty')
plt.xlabel('Time [s]')
plt.ylabel('Value')
plt.legend()
plt.grid()

plt.tight_layout()
# >> [image dropped]
# >> <Figure size 1000x1500 with 5 Axes>

# %% [cell 16] code
# Mass-spring-damper system with adaptive control 2 dimensions with 5 neurons RBF for each state plus a bias term
import numpy as np
import control as ct
import matplotlib.pyplot as plt

ft = 40 # simulation time in seconds
dt = 0.005 # time step in seconds

A = np.array([[0, 1], [0, 0]]) # A matrix of the system (Double Integrator)
B = np.array([[0], [1]]) # B matrix of the system
Lam = np.array([[0.75]]) # True Lambda (Input Gain)
x = np.array([[0.], [0.]]) # initial state

# LQR Design for Reference Model
K1, S, E = ct.lqr(A, B, np.eye(2), 0.1) 
K1 = np.asarray(K1)

# Reference Model Matrices: Ar = A - B*K1
Ar = A - B @ K1 
# Feedforward Gain K2 to ensure DC gain is 1
C = np.array([[1, 0]])
K2 = -1.0 / (C @ np.linalg.inv(Ar) @ B).item()
Br = B * K2 

xr = np.array([[0.], [0.]]) # reference model initial state

gam = 10 # adaptation gain
sig = 0.1 # sigma modification gain
P = ct.lyap(Ar.T, np.eye(2)) # Solve Lyapunov Equation

# Neural Network (RBF) Setup
# 12 Weights: 1 Bias + 5 for Position + 5 for Velocity + 1 for Input (Lambda adaptation)
What = np.zeros((12,1)) 

def rbf(x, c, width):
    # MATLAB formula: exp(-width*(abs(x-c))^2)
    return np.exp(-width * abs(x - c)**2)

x_rec = [] 
xr_rec = []
u_rec = [] 
t_rec = [] 
w_rec = [] 
unc_rec = [] 
ua_rec = []

for t in range(int(ft/dt)):
    time = t*dt

    # Reference Command
    if time <= 10 :
        c = 0.5
    elif 10 < time <= 20 :
        c = -0.5
    elif 20 < time <= 30 :
        c = 0.5
    else :
        c = -0.5
    
    un = -K1 @ x + K2 * c # nominal control

    # Construct Regressor (theta) - matching MATLAB exactly
    theta = np.zeros((12, 1))
    
    # 0: Bias term
    theta[0] = 1.0 
    
    # 1-5: Position RBFs (Centered at 2, 1, 0, -1, -2 to match MATLAB)
    for i in range(5):
        center = 2.0 - i  # 2, 1, 0, -1, -2
        theta[i+1] = rbf(x[0], center, 0.25)
        
    # 6-10: Velocity RBFs (Centered at 2, 1, 0, -1, -2 to match MATLAB)
    for i in range(5):
        center = 2.0 - i  # 2, 1, 0, -1, -2
        theta[i+6] = rbf(x[1], center, 0.25)
        
    # 11: Control Input term (Compensates for Gain Uncertainty)
    theta[11] = un

    ua = -What.T @ theta # adaptive control
    u = un + ua # total control input

    xr = xr + dt*(Ar @ xr + Br * c) # reference model update
    What = What + dt*(gam * theta @ (x - xr).T @ P @ B - gam * sig * What) # weight adaptation with sigma modification


    x0 = x[0]
    x1 = x[1]
    # Arbitrary nonlinearity (with correct coefficient 2)
    uncertainty = 1.0 + x0**2 + 2*x0**2 * x1**2 + np.sin(x0) * x1**3 + np.cos(x1) * x0**4
    
    x = x + dt * (A @ x + B * Lam * (u + uncertainty))

    # record data
    x_rec.append(x.flatten())
    xr_rec.append(xr.flatten())
    u_rec.append(u.item())
    t_rec.append(time)
    w_rec.append(What.flatten())
    unc_rec.append(uncertainty)
    ua_rec.append(ua.item())

# plot results
plt.figure(figsize=(10,15))
plt.subplot(5,1,1)
plt.plot(t_rec, [x[0] for x in x_rec], label='Position x[0]')
plt.plot(t_rec, [xr[0] for xr in xr_rec], label='Reference Model x_r[0]', linestyle='--')
plt.axhline(y=0.5, color='r', linestyle='--', alpha=0.5)
plt.axhline(y=-0.5, color='r', linestyle='--', alpha=0.5)
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Position over Time')
plt.xlabel('Time [s]')
plt.ylabel('Position x[0]')
plt.legend()
plt.grid()

plt.subplot(5,1,2)
plt.plot(t_rec, [x[1] for x in x_rec], label='Velocity x[1]')
plt.plot(t_rec, [xr[1] for xr in xr_rec], label='Reference Model x_r[1]', linestyle='--')
plt.axhline(y=0, color='k', linestyle='--')
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Velocity over Time')
plt.xlabel('Time [s]')
plt.ylabel('Velocity x[1]')
plt.legend()
plt.grid()

plt.subplot(5,1,3)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(5,1,4)
for i in range(len(What)):
    w_i = [w[i] for w in w_rec]
    plt.plot(t_rec, w_i, label=f'Weight Ŵ[{i}]')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights ŵ')
#plt.legend()
plt.grid()

plt.subplot(5,1,5)
plt.plot(t_rec, [-u for u in ua_rec], label='Estimated Uncertainty (-u_a)')
plt.plot(t_rec, unc_rec, label='True Uncertainty', linestyle='--')
plt.title('Uncertainty Estimation vs True Uncertainty')
plt.xlabel('Time [s]')
plt.ylabel('Value')
plt.legend()
plt.grid()

plt.tight_layout()

# >> [image dropped]
# >> <Figure size 1000x1500 with 5 Axes>

# %% [cell 17] code
# Mass-spring-damper system with adaptive control 2 dimensions 
# With performance recovery
import numpy as np
import control as ct
import matplotlib.pyplot as plt

ft = 40 # simulation time in seconds
dt = 0.005 # time step in seconds

mass = 5.0 # mass
alpha = 10 # Spring constant
beta = 15 # Damping coefficient
A = np.array([[0, 1], [0, 0]]) # A matrix of the system
B = np.array([[0], [1]]) # B matrix of the system
Lam = np.array([[1/mass]]) # Lambda
# True weight vector - represents the true parameters -alpha and -beta
# Uncertainty is W0.T @ x = -alpha*x - beta*v
W0 = np.array([[ -alpha ], [ -beta ]]) 
x = np.array([[0.], [0.]]) # initial state

K1, S, E = ct.lqr(A, B, np.eye(2), 0.1) # LQR gain
# Note: K1 from ct.lqr might be matrix or array, ensure shape
K1 = np.asarray(K1)

# Feedforward gain
# Ar = A - B K1
Ar = A - B @ K1 # reference model A matrix
# K2 = -1 / (C Ar^-1 B) for C = [1 0]
C = np.array([[1, 0]])
K2 = -1.0 / (C @ np.linalg.inv(Ar) @ B).item()

Br = B * K2 # reference model B matrix
xr = np.array([[0.], [0.]]) # reference model initial state
xri = np.array([[0.], [0.]]) # integral of reference model error
c = 0 # reference command
f = np.array([[0.], [0.]]) # filtered error

gam = 1 # adaptation gain
lam = 1 # performance recovery gain
# Solve Lyapunov for Ar^T P + P Ar = -I
P = ct.lyap(Ar.T, np.eye(2)) 
What = np.zeros((4,1)) # initial weight estimate - matches regressor size

x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record

for t in range(int(ft/dt)):
    time = t*dt

    if time <= 10 :
        cc = 1
    elif 10 < time <= 20 :
        cc = -1
    elif 20 < time <= 30 :
        cc = 1
    else :
        cc = -1

    c = c + dt * (-4*(c - cc)) # first order filter for command

    f = f + dt * (-lam * (f - (x - xr)))
    g = lam * f +(Ar - lam * np.eye(2)) @ (x - xr)
    v = np.linalg.inv(B.T @ B)@ B.T @ g
    un = -K1 @ x + K2 * c + v # nominal control   
    # Regressor is just the state [position, velocity**3, un, v]
    phi = np.vstack((x[0], x[1]**3, un, v))
    phi_r = np.vstack((x[0], x[1]**3))
    # Adaptive control law
    ua = -What.T @ phi 
    u = un + ua 


    # Reference model update
    xr = xr + dt*(Ar @ xr + Br * c + B * v) 
    xri = xri + dt * (Ar @ xri + Br * c) # for plotting only
    # Tracking error
    e = x - xr
    # Weights adaptation update
    What = What + dt*(gam * phi @ (e.T @ P @ B)) 


    # System dynamics (True Equation)
    # xdot = A x + B Lam (u + W0.T @ phi)
    # This corresponds to mass*xdd = u - alpha*x - beta*v
    x = x + dt*(A @ x + B @ Lam @ (u + W0.T @ phi_r)) 

    # record data
    x_rec.append(x.flatten())
    xr_rec.append(xr.flatten())
    u_rec.append(u.item())
    t_rec.append(time)
    w_rec.append(What.flatten())

# plot results
plt.figure(figsize=(10,12))
plt.subplot(4,1,1)
plt.plot(t_rec, [x[0] for x in x_rec], label='Position x[0]')
plt.plot(t_rec, [xr[0] for xr in xr_rec], label='Reference Model x_r[0]', linestyle='--')
plt.axhline(y=1, color='r', linestyle='--', label='Reference c=1')
plt.axhline(y=-1, color='g', linestyle='--', label='Reference c=-1')
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Position over Time')
plt.xlabel('Time [s]')
plt.ylabel('Position x[0]')
plt.legend()
plt.grid()
plt.subplot(4,1,2)
plt.plot(t_rec, [x[1] for x in x_rec], label='Velocity x[1]')
plt.plot(t_rec, [xr[1] for xr in xr_rec], label='Reference Model x_r[1]', linestyle='--')
plt.axhline(y=0, color='k', linestyle='--')
plt.axvline(x=10, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=20, color='k', linestyle=':', alpha=0.5)
plt.axvline(x=30, color='k', linestyle=':', alpha=0.5)
plt.title('Velocity over Time')
plt.xlabel('Time [s]')
plt.ylabel('Velocity x[1]')
plt.legend()
plt.grid()

plt.subplot(4,1,3)
plt.plot(t_rec, u_rec)
plt.title('Control Input over Time')
plt.xlabel('Time [s]')
plt.ylabel('Control u')
plt.grid()

plt.subplot(4,1,4)
for i in range(len(What)):
    w_i = [w[i] for w in w_rec]
    plt.plot(t_rec, w_i, label=f'Weight Ŵ[{i}]')
plt.hlines([-alpha, -beta], t_rec[0], t_rec[-1], colors='r', linestyles='--', label='True Weights')
plt.title('Estimated Weights over Time')
plt.xlabel('Time [s]')
plt.ylabel('Estimated Weights Ŵ')
plt.legend()
plt.grid()

plt.tight_layout()
# >> [image dropped]
# >> <Figure size 1000x1200 with 4 Axes>

