# Extract of Adaptive_Control_Tutorial_2.ipynb
# Generated by ground_station/research/notebooks/extract.py; do not edit.

# %% [cell 0] markdown
# # Adaptive Control Tutorial for Beginners
#
# This notebook demonstrates three different **adaptive control** techniques for a simple mechanical system.
#
# ## What is Adaptive Control?
#
# Imagine you're trying to control a drone, but:
# - You don't know exactly how heavy it is
# - The weight changes as the battery drains
# - Wind conditions keep changing
#
# **Adaptive control** is a smart control system that *learns* these unknowns while flying, adjusting itself automatically to maintain good performance.
#
# ## The System We're Controlling
#
# We're working with a **mass-spring-damper** system - think of it like:
# - A mass on a spring (like a car's suspension)
# - With some friction/damping (like a shock absorber)
#
# The goal: Make the mass follow a commanded position, even though we don't know the exact spring stiffness or damping coefficient.
#
# ## Three Control Approaches in This Notebook
#
# 1. **Integral Adaptive Control** - Uses an integral term to eliminate steady-state errors
# 2. **PID Adaptive Control** - Combines Proportional-Integral-Derivative control with adaptation
# 3. **Derivative-Free Adaptive Control** - A simpler method that doesn't need velocity measurements or calculations
#
# Let's explore each one!

# %% [cell 1] code
# Integral nominal control for a mass-spring-damper 2D system 
from time import time
import numpy as np
import control as ct
import matplotlib.pyplot as plt

ft = 40 # simulation time in seconds
dt = 0.005 # time step in seconds

mass = 5.0 # mass
alpha = 2.5 # Spring constant
beta = 1.0 # Damping coefficient
A = np.array([[0, 1], [0, 0]]) # A matrix of the system
B = np.array([[0], [1]]) # B matrix of the system
Lam = np.array([[1/mass]]) # Lambda
# True weight vector - represents the true parameters -alpha and -beta
# Uncertainty is W0.T @ x = -alpha*x - beta*v
W0 = np.array([[ -alpha ], [ -beta ]]) 
x = np.array([[0.], [0.]]) # initial state


E = np.array([[1, 0]]) # output matrix (as row vector)
Aa = np.block([[A, np.zeros((2,1))], [E, 0]]) # augmented A matrix
Ba = np.block([[B], [0]]) # augmented B matrix

K, S, Eigs = ct.lqr(Aa, Ba, np.eye(3), 0.1) # LQR gain
# Note: K1 from ct.lqr might be matrix or array, ensure shape
K1 = K[0, :2].reshape(1, 2)
K2 = K[0, 2]


Ar = np.block([[A-B @ K1, -B * K2], [E, np.array([[0]])]])
Br = np.array([[0.], [0.], [-1.]]) # reference model B matrix

z = np.array([[0.]]) # augmented state initial condition
xir = np.zeros((3,1)) # reference model state initial condition

gam = 10 # adaptation gain
# Solve Lyapunov for Ar^T P + P Ar = -I
P = ct.lyap(Ar.T, np.eye(3)) 
What = np.zeros((3,1)) # initial weight estimate - matches regressor size

x_rec = [] # state record
xir_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record
c_rec = [] # reference command record
z_rec = [] # integral state record

for t in np.arange(0, ft, dt):
    # Reference Command
    if t <= 10 :
        c = 1.0
    elif 10 < t <= 20 :
        c = -1.0
    elif 20 < t <= 30 :
        c = 1.0
    else :
        c = -1.0
    
    un = -K1 @ x - K2 * z # nominal control
    z = z + dt * (E @ x - c) # integral state update
    theta_un = np.vstack((x[0,0], x[1,0]**3, un)) # regressor vector
    theta = np.vstack((x[0,0], x[1,0]**3)) # regressor vector for uncertainty
    ua = -What.T @ theta_un # adaptive control
    u = un + ua # total control

    xi = np.vstack((x, z)) # augmented state
    xir = xir + dt * (Ar @ xir + Br * c) # reference model update
    What = What + dt *(gam * theta_un @ (xi - xir).T @ P @ Ba) # weight update

    x = x + dt * (A @ x + B * Lam *(u + W0.T @ theta)) # state update

    # Record data
    x_rec.append(x.flatten())
    xir_rec.append(xir.flatten())
    u_rec.append(u.flatten())
    t_rec.append(t)
    w_rec.append(What.flatten())
    c_rec.append(c)
    z_rec.append(z.flatten())

# Convert lists to numpy arrays for easier plotting
x_rec = np.array(x_rec)
xir_rec = np.array(xir_rec)
u_rec = np.array(u_rec)
t_rec = np.array(t_rec)
w_rec = np.array(w_rec)
c_rec = np.array(c_rec)
z_rec = np.array(z_rec)

# Plotting
fig, axes = plt.subplots(5, 1, figsize=(12, 14))

# Plot position tracking
axes[0].plot(t_rec, x_rec[:, 0], label='Actual Position', linewidth=2)
axes[0].plot(t_rec, xir_rec[:, 0], '--', label='Reference Position', linewidth=2)
axes[0].plot(t_rec, c_rec, ':', label='Command', linewidth=1.5, alpha=0.7)
axes[0].set_ylabel('Position')
axes[0].set_xlabel('Time (s)')
axes[0].set_title('Position Tracking')
axes[0].legend()
axes[0].grid(True)

# Plot velocity tracking
axes[1].plot(t_rec, x_rec[:, 1], label='Actual Velocity', linewidth=2)
axes[1].plot(t_rec, xir_rec[:, 1], '--', label='Reference Velocity', linewidth=2)
axes[1].set_ylabel('Velocity')
axes[1].set_xlabel('Time (s)')
axes[1].set_title('Velocity Tracking')
axes[1].legend()
axes[1].grid(True)

# Plot integral state
axes[2].plot(t_rec, z_rec[:, 0], label='Integral State z', linewidth=2, color='green')
axes[2].plot(t_rec, xir_rec[:, 2], '--', label='Reference Integral State', linewidth=2, color='darkgreen')
axes[2].set_ylabel('Integral State')
axes[2].set_xlabel('Time (s)')
axes[2].set_title('Integral State')
axes[2].legend()
axes[2].grid(True)

# Plot control input
axes[3].plot(t_rec, u_rec[:, 0], label='Control Input', linewidth=2)
axes[3].set_ylabel('Control u')
axes[3].set_xlabel('Time (s)')
axes[3].set_title('Control Input')
axes[3].legend()
axes[3].grid(True)

# Plot weight estimates
axes[4].plot(t_rec, w_rec[:, 0], label='What[0] (position-related)', linewidth=2)
axes[4].plot(t_rec, w_rec[:, 1], label='What[1] (velocity^3-related)', linewidth=2)
axes[4].plot(t_rec, w_rec[:, 2], label='What[2] (control-related)', linewidth=2)
axes[4].axhline(y=-alpha, color='C0', linestyle=':', alpha=0.5, label=f'True -alpha = {-alpha}')
axes[4].axhline(y=-beta, color='C1', linestyle=':', alpha=0.5, label=f'True -beta = {-beta}')
axes[4].set_ylabel('Weight Estimates')
axes[4].set_xlabel('Time (s)')
axes[4].set_title('Adaptive Weight Estimates')
axes[4].legend()
axes[4].grid(True)

plt.tight_layout()
plt.show()

# >> [image dropped]
# >> <Figure size 1200x1400 with 5 Axes>

# %% [cell 2] code
# PID adaptive control for a mass-spring-damper 2D system with measurement noise

ft = 40 # simulation time in seconds
dt = 0.005 # time step in seconds

mass = 5.0 # mass
alpha = 2.5 # Spring constant
beta = 1.0 # Damping coefficient
A = np.array([[0, 1], [0, 0]]) # A matrix of the system
B = np.array([[0], [1]]) # B matrix of the system
Lam = np.array([[1/mass]]) # Lambda
# True weight vector - represents the true parameters -alpha and -beta
# Uncertainty is W0.T @ x = -alpha*x - beta*v
W0 = np.array([[ -alpha ], [ -beta ]]) 
x = np.array([[0.], [0.]]) # initial state

E = np.array([[1, 0]]) # output matrix (as row vector)
K1 = 4.0 # Proportional gain
K2 = 0.5 # Integral gain
K3 = 2.5 # Derivative gain
lambd = 50 # filter constant
F = np.eye(2) + B * K3 @ E
F_inv = np.linalg.inv(F)
G = A - B * K1 @ E
Ba = np.vstack((F_inv @ B , 0)) # augmented B matrix
Ar = np.block([[F_inv @ G , - F_inv @ B * K2], [E, np.array([[0]])]])
Br = np.vstack((F_inv @ B * K1, -1)) # reference model B matrix
z = np.array([[0.]]) # augmented state initial condition
q = np.array([[0.]]) # filtered tracking error initial condition
xir = np.zeros((3,1)) # reference model state initial condition

gam = 10 # adaptation gain
P = ct.lyap(Ar.T, np.eye(3))
What = np.zeros((3,1)) # initial weight estimate - matches regressor size

# Measurement noise parameters
noise_std = 0.05 # standard deviation of measurement noise
np.random.seed(42) # for reproducibility

x_rec = [] # state record
xir_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record
w_rec = [] # weight record
c_rec = [] # reference command record
z_rec = [] # integral state record
q_rec = [] # filtered error record
x_meas_rec = [] # measured state record

for t in np.arange(0, ft, dt):
    # Reference Command
    if t <= 10 :
        c = 1.0
    elif 10 < t <= 20 :
        c = -1.0
    elif 20 < t <= 30 :
        c = 1.0
    else :
        c = -1.0

    # Add measurement noise to state measurements
    noise = np.random.normal(0, noise_std, size=(2, 1))
    x_meas = x  # + noise
    
    y = E @ x_meas # system output with noisy measurement
    q = q + dt * ( -lambd * (q - y)) # filtered tracking error update
    yd = -lambd * (q - y) # derivative of output estimate
    un = -K1 * (y - c) - K2 * z - K3 * yd # nominal control
    z = z + dt * (y - c) # integral state update
    theta_un = np.vstack((x_meas[0,0], x_meas[1,0]**3, un)) # regressor vector with noisy measurements
    theta = np.vstack((x_meas[0,0], x_meas[1,0]**3)) # regressor vector for uncertainty with noisy measurements
    ua = -What.T @ theta_un # adaptive control
    u = un + ua # total control

    xi = np.vstack((x_meas, z)) # augmented state with noisy measurements
    xir = xir + dt * (Ar @ xir + Br * c) # reference model
    What = What + dt *(gam * theta_un @ (xi - xir).T @ P @ Ba) # weight update

    x = x + dt * (A @ x + B * Lam *(u + W0.T @ theta)) # state update (true state)

    # Record data
    x_rec.append(x.flatten())
    x_meas_rec.append(x_meas.flatten())
    xir_rec.append(xir.flatten())
    u_rec.append(u.flatten())
    t_rec.append(t)
    w_rec.append(What.flatten())
    c_rec.append(c)
    z_rec.append(z.flatten())
    q_rec.append(q.flatten())
# Convert lists to numpy arrays for easier plotting
x_rec = np.array(x_rec)
x_meas_rec = np.array(x_meas_rec)
xir_rec = np.array(xir_rec)
u_rec = np.array(u_rec)
t_rec = np.array(t_rec)
w_rec = np.array(w_rec)
c_rec = np.array(c_rec)
z_rec = np.array(z_rec)
q_rec = np.array(q_rec)
# Plotting
fig, axes = plt.subplots(6, 1, figsize=(12, 16))

# Plot position tracking
axes[0].plot(t_rec, x_rec[:, 0], label='True Position', linewidth=2)
axes[0].plot(t_rec, x_meas_rec[:, 0], ':', label='Measured Position', linewidth=1, alpha=0.6)
axes[0].plot(t_rec, xir_rec[:, 0], '--', label='Reference Position', linewidth=2)
axes[0].plot(t_rec, c_rec, '-.', label='Command', linewidth=1.5, alpha=0.7)
axes[0].set_ylabel('Position')
axes[0].set_xlabel('Time (s)')
axes[0].set_title('Position Tracking (with Measurement Noise)')
axes[0].legend()
axes[0].grid(True)

# Plot velocity tracking
axes[1].plot(t_rec, x_rec[:, 1], label='True Velocity', linewidth=2)
axes[1].plot(t_rec, x_meas_rec[:, 1], ':', label='Measured Velocity', linewidth=1, alpha=0.6)
axes[1].plot(t_rec, xir_rec[:, 1], '--', label='Reference Velocity', linewidth=2)
axes[1].set_ylabel('Velocity')
axes[1].set_xlabel('Time (s)')
axes[1].set_title('Velocity Tracking (with Measurement Noise)')
axes[1].legend()
axes[1].grid(True)

# Plot integral state
axes[2].plot(t_rec, z_rec[:, 0], label='Integral State z', linewidth=2, color='green')
axes[2].plot(t_rec, xir_rec[:, 2], '--', label='Reference Integral State', linewidth=2, color='darkgreen')
axes[2].set_ylabel('Integral State')
axes[2].set_xlabel('Time (s)')
axes[2].set_title('Integral State')
axes[2].legend()
axes[2].grid(True)

# Plot filtered tracking error
axes[3].plot(t_rec, q_rec[:, 0], label='Filtered Output q', linewidth=2, color='purple')
axes[3].set_ylabel('Filtered Output')
axes[3].set_xlabel('Time (s)')
axes[3].set_title('Filtered Output')
axes[3].legend()
axes[3].grid(True)

# Plot control input
axes[4].plot(t_rec, u_rec[:, 0], label='Control Input', linewidth=2)
axes[4].set_ylabel('Control u')
axes[4].set_xlabel('Time (s)')
axes[4].set_title('Control Input (with Noisy Measurements)')
axes[4].legend()
axes[4].grid(True)

# Plot weight estimates
axes[5].plot(t_rec, w_rec[:, 0], label='What[0] (position-related)', linewidth=2)
axes[5].plot(t_rec, w_rec[:, 1], label='What[1] (velocity^3-related)', linewidth=2)
axes[5].plot(t_rec, w_rec[:, 2], label='What[2] (control-related)', linewidth=2)
axes[5].axhline(y=-alpha, color='C0', linestyle=':', alpha=0.5, label=f'True -alpha = {-alpha}')
axes[5].axhline(y=-beta, color='C1', linestyle=':', alpha=0.5, label=f'True -beta = {-beta}')
axes[5].set_ylabel('Weight Estimates')
axes[5].set_xlabel('Time (s)')
axes[5].set_title('Adaptive Weight Estimates (with Noisy Measurements)')
axes[5].legend()
axes[5].grid(True)

plt.tight_layout()
plt.show()

# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_3860\1804301809.py:72: RuntimeWarning: overflow encountered in matmul
# >>   ua = -What.T @ theta_un # adaptive control
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_3860\1804301809.py:77: RuntimeWarning: overflow encountered in matmul
# >>   What = What + dt *(gam * theta_un @ (xi - xir).T @ P @ Ba) # weight update
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_3860\1804301809.py:77: RuntimeWarning: invalid value encountered in matmul
# >>   What = What + dt *(gam * theta_un @ (xi - xir).T @ P @ Ba) # weight update
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_3860\1804301809.py:79: RuntimeWarning: invalid value encountered in multiply
# >>   x = x + dt * (A @ x + B * Lam *(u + W0.T @ theta)) # state update (true state)
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_3860\1804301809.py:65: RuntimeWarning: invalid value encountered in matmul
# >>   y = E @ x_meas # system output with noisy measurement
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_3860\1804301809.py:79: RuntimeWarning: invalid value encountered in matmul
# >>   x = x + dt * (A @ x + B * Lam *(u + W0.T @ theta)) # state update (true state)
# >> [image dropped]
# >> <Figure size 1200x1600 with 6 Axes>

# %% [cell 3] markdown
# ## Approach 3: Derivative-Free Adaptive Control
#
# ### What Makes This Special?
#
# The previous methods needed to know or measure the **velocity** of the system. But sometimes:
# - Velocity sensors are noisy or unavailable
# - Taking derivatives amplifies noise
# - We want a simpler, more robust solution
#
# **Derivative-Free MRAC** (Model Reference Adaptive Control) solves this!
#
# ### How It Works (Simple Explanation)
#
# 1. **Reference Model**: We define how we *want* the system to behave
#    - `wn` = Natural frequency (how fast it responds)
#    - `rn` = Damping ratio (how smooth the response is)
#
# 2. **Nominal Controller**: A basic controller designed assuming we know everything perfectly
#    - `K1` = State feedback gain (corrects current errors)
#    - `K2` = Feedforward gain (follows the command)
#
# 3. **Adaptive Part**: Learns what we got wrong and compensates in real-time
#    - `gamma1`, `gamma2` = Learning speeds (how fast it adapts)
#    - `tau` = Filter time constant (smooths out the adaptation)
#
# ### The Key Variables Explained
#
# - **ft** (100 seconds): How long to run the simulation
# - **dt** (0.005 seconds): Time step size (like frame rate in a video)
# - **Switches**: Turn uncertainty and adaptation on/off to see their effects
# - **A, B**: Mathematical description of the system dynamics
# - **Am, Bm**: The "ideal" behavior we want to achieve
# - **P**: A matrix from Lyapunov theory (ensures stability - basically a safety certificate)
#
# ### Why "Derivative-Free"?
#
# Traditional adaptive control calculates velocity by taking the derivative of position. This method uses a clever filter (`tau`) to avoid needing derivatives, making it more robust to noise!

# %% [cell 4] code
# Derivative-free adaptive control for a 2D system with nonlinear uncertainty
ft = 100 # simulation time in seconds
dt = 0.005 # time step in seconds

# Switches
Uncertainty_on = 1
Adaption_on = 1

# A and B matrices
A = np.array([[0, 1], [0, 0]]) # A matrix of the system
B = np.array([[0], [1]]) # B matrix of the system

# Reference model
wn = 0.4 # reference model natural frequency
rn = 0.707 # reference model damping ratio
Am = np.array([[0, 1], [-wn**2, -2*rn*wn]]) # reference model A matrix
Bm = np.array([[0], [wn**2]]) # reference model B matrix

# Nominal Control Gains 
K1 = np.linalg.pinv(B) @ (A - Am) # State feedback gain
K2 = np.linalg.pinv(B) @ Bm # Feedforward gain

# Adaptive control Learning Rate
P = ct.lyap(Am.T, np.eye(2))
gamma1 = 0.9  # between 0 <= gamma1 < 1 , gamma1 = 1 when uncertainty is constant
gamma2 = 10.0
tau = 0.1 # Design parameter for DF-MRAC (filter time constant)

x = np.array([[0.], [0.]]) # initial state
xm = np.array([[0.], [0.]]) # initial reference model state
r = np.array([[0.]]) # initial reference command
What = np.zeros((5,1)) # initial weight estimate - matches regressor size
W_hat_Tau = np.zeros((5,1)) # filtered weight estimate


x_rec = np.array([]) # state record
xm_rec = np.array([]) # reference model state record
u_rec = np.array([]) # control record
t_rec = np.array([]) # time record
What_rec = np.array([]) # weight record
r_rec = np.array([]) # reference command record
W_rec = np.array([]) # true weight record
Wb_rec = np.array([]) # basis function uncertainty record
Wb_est_rec = np.array([]) # basis function estimated uncertainty record
beta_rec = np.array([]) # basis function record


for t in np.arange(0, ft, dt):
    if t <= 20 :
        W = np.array([[0.0], [0.0], [0.0], [0.0], [0.0]])
    else :
        W = np.array([[0.1414*np.sin(2.5*t)], [ 0.5504 ], [ -0.0624 ], [ -0.0095 ], [0.0215]])

    # Reference Command r(t)
    if t <= 25 :
        rs = +30*np.pi/180
    elif 25 < t <= 50 :
        rs = -30*np.pi/180
    elif 50 < t <= 75 :
        rs = +30*np.pi/180
    else :
        rs = -30*np.pi/180
    
    r = r + dt * ( rs - r ) # first-order filter for command

    # Basis Function
    beta = np.array([[x[0,0]], [x[1,0]], [abs(x[0,0])*x[1,0]], [abs(x[1,0])*x[1,0]], [x[0,0]**3]])  

    # Controller
    un = -K1 @ x + K2 * r # nominal control
    uad = What.T @ beta # adaptive control
    u = un - uad*(Adaption_on) # total control

    # Weight Update Law
    What = gamma1 * W_hat_Tau + gamma2 * beta @ (x - xm).T @ P @ B

    # Reference Model Update
    xm = xm + dt * (Am @ xm + Bm * r)

    # Uncertain System
    x = x + dt * (A @ x + B * (u + Uncertainty_on * W.T @ beta))    

    # Save Data
    x_rec = np.vstack((x_rec, (x*180/np.pi).flatten())) if x_rec.size else (x*180/np.pi).flatten()
    xm_rec = np.vstack((xm_rec, (xm*180/np.pi).flatten())) if xm_rec.size else (xm*180/np.pi).flatten()
    u_rec = np.vstack((u_rec, (u*180/np.pi).flatten())) if u_rec.size else (u*180/np.pi).flatten()
    t_rec = np.vstack((t_rec, t)) if t_rec.size else np.array([t])
    What_rec = np.vstack((What_rec, What.flatten())) if What_rec.size else What.flatten()
    r_rec = np.vstack((r_rec, r*180/np.pi)) if r_rec.size else np.array([r.flatten()*180/np.pi])
    W_rec = np.vstack((W_rec, W.flatten())) if W_rec.size else W.flatten()
    Wb_rec = np.vstack((Wb_rec, (W.T @ beta).flatten())) if Wb_rec.size else (W.T @ beta).flatten()
    Wb_est_rec = np.vstack((Wb_est_rec, (What.T @ beta).flatten())) if Wb_est_rec.size else (What.T @ beta).flatten()
    beta_rec = np.vstack((beta_rec, beta.flatten())) if beta_rec.size else beta.flatten()
    
    # Filtered Weight Update - safer implementation
    # Only update when we have enough history (tau seconds worth of data)
    if len(What_rec) >= int(tau/dt):
        W_hat_Tau = What_rec[-int(tau/dt), :].reshape(5,1)
    

# Reshape arrays if they're 1D
if t_rec.ndim == 1:
    t_rec = t_rec.reshape(-1, 1)
if x_rec.ndim == 1:
    x_rec = x_rec.reshape(1, -1)
if xm_rec.ndim == 1:
    xm_rec = xm_rec.reshape(1, -1)
if u_rec.ndim == 1:
    u_rec = u_rec.reshape(-1, 1)
if r_rec.ndim == 1:
    r_rec = r_rec.reshape(-1, 1)

# Calculate tracking error
e_rec = x_rec - xm_rec

# Set matplotlib defaults for better readability
plt.rcParams.update({
    'font.size': 11,
    'axes.titlesize': 13,
    'axes.labelsize': 11,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.titlesize': 14
})

# Plotting - Split into multiple figures for better visibility
# Figure 1: State Tracking (Position and Velocity)
fig1, axes1 = plt.subplots(2, 1, figsize=(16, 10))

axes1[0].plot(t_rec, x_rec[:, 0], label='Actual Position', linewidth=2.5, color='#1f77b4')
axes1[0].plot(t_rec, xm_rec[:, 0], '--', label='Reference Model Position', linewidth=2.5, color='#ff7f0e')
axes1[0].plot(t_rec, r_rec, ':', label='Command', linewidth=2, alpha=0.8, color='#2ca02c')
axes1[0].axvline(x=20, color='red', linestyle='--', alpha=0.4, linewidth=2, label='Uncertainty Start')
axes1[0].set_ylabel('Position (degrees)', fontsize=12)
axes1[0].set_xlabel('Time (s)', fontsize=12)
axes1[0].set_title('Position Tracking - Derivative-Free Adaptive Control', fontsize=14, fontweight='bold')
axes1[0].legend(loc='best', fontsize=11, framealpha=0.9)
axes1[0].grid(True, alpha=0.3)

axes1[1].plot(t_rec, x_rec[:, 1], label='Actual Velocity', linewidth=2.5, color='#1f77b4')
axes1[1].plot(t_rec, xm_rec[:, 1], '--', label='Reference Model Velocity', linewidth=2.5, color='#ff7f0e')
axes1[1].axvline(x=20, color='red', linestyle='--', alpha=0.4, linewidth=2, label='Uncertainty Start')
axes1[1].set_ylabel('Velocity (deg/s)', fontsize=12)
axes1[1].set_xlabel('Time (s)', fontsize=12)
axes1[1].set_title('Velocity Tracking', fontsize=14, fontweight='bold')
axes1[1].legend(loc='best', fontsize=11, framealpha=0.9)
axes1[1].grid(True, alpha=0.3)

plt.tight_layout(pad=3.0)
plt.show()

# Figure 2: Tracking Errors, Control, and Uncertainty Comparison
fig2, axes2 = plt.subplots(3, 1, figsize=(16, 14))

axes2[0].plot(t_rec, e_rec[:, 0], label='Position Error', linewidth=2.5, color='#d62728')
axes2[0].plot(t_rec, e_rec[:, 1], label='Velocity Error', linewidth=2.5, color='#ff7f0e')
axes2[0].axvline(x=20, color='red', linestyle='--', alpha=0.4, linewidth=2, label='Uncertainty Start')
axes2[0].axhline(y=0, color='black', linestyle='-', linewidth=1)
axes2[0].set_ylabel('Tracking Error', fontsize=12)
axes2[0].set_xlabel('Time (s)', fontsize=12)
axes2[0].set_title('Tracking Error (x - xm)', fontsize=14, fontweight='bold')
axes2[0].legend(loc='best', fontsize=11, framealpha=0.9)
axes2[0].grid(True, alpha=0.3)

axes2[1].plot(t_rec, u_rec, label='Total Control', linewidth=2.5, color='#9467bd')
axes2[1].axvline(x=20, color='red', linestyle='--', alpha=0.4, linewidth=2, label='Uncertainty Start')
axes2[1].set_ylabel('Control Input u (degrees)', fontsize=12)
axes2[1].set_xlabel('Time (s)', fontsize=12)
axes2[1].set_title('Control Input', fontsize=14, fontweight='bold')
axes2[1].legend(loc='best', fontsize=11, framealpha=0.9)
axes2[1].grid(True, alpha=0.3)

axes2[2].plot(t_rec, Wb_rec, label='True Uncertainty W^T β', linewidth=2.5, color='#d62728')
axes2[2].plot(t_rec, Wb_est_rec, '--', label='Estimated Uncertainty Ŵ^T β', linewidth=2.5, color='#1f77b4')
axes2[2].axvline(x=20, color='red', linestyle='--', alpha=0.4, linewidth=2, label='Uncertainty Start')
axes2[2].axhline(y=0, color='black', linestyle='-', linewidth=1)
axes2[2].set_ylabel('Uncertainty Value', fontsize=12)
axes2[2].set_xlabel('Time (s)', fontsize=12)
axes2[2].set_title('Uncertainty Comparison: True vs Estimated', fontsize=14, fontweight='bold')
axes2[2].legend(loc='best', fontsize=11, framealpha=0.9)
axes2[2].grid(True, alpha=0.3)

plt.tight_layout(pad=3.0)
plt.show()

# Figure 3: Weight Estimates and Errors
fig3, axes3 = plt.subplots(2, 1, figsize=(16, 12))

weight_labels = ['W[0]: sin term', 'W[1]: constant', 'W[2]: |x1|*x2', 'W[3]: |x2|*x2', 'W[4]: x1³']
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']

for i in range(5):
    axes3[0].plot(t_rec, What_rec[:, i], label=f'Ŵ[{i}]', linewidth=2.5, color=colors[i])
    axes3[0].plot(t_rec, W_rec[:, i], '--', linewidth=2, alpha=0.6, color=colors[i])
axes3[0].axvline(x=20, color='red', linestyle='--', alpha=0.4, linewidth=2, label='Uncertainty Start')
axes3[0].set_ylabel('Weight Values', fontsize=12)
axes3[0].set_xlabel('Time (s)', fontsize=12)
axes3[0].set_title('Adaptive Weight Estimates (solid) vs True Weights (dashed)', fontsize=14, fontweight='bold')
axes3[0].legend(loc='best', ncol=3, fontsize=10, framealpha=0.9)
axes3[0].grid(True, alpha=0.3)

for i in range(5):
    weight_error = What_rec[:, i] - W_rec[:, i]
    axes3[1].plot(t_rec, weight_error, label=weight_labels[i], linewidth=2.5, color=colors[i])
axes3[1].axvline(x=20, color='red', linestyle='--', alpha=0.4, linewidth=2, label='Uncertainty Start')
axes3[1].axhline(y=0, color='black', linestyle='-', linewidth=1)
axes3[1].set_ylabel('Weight Estimation Error', fontsize=12)
axes3[1].set_xlabel('Time (s)', fontsize=12)
axes3[1].set_title('Weight Estimation Errors (Ŵ - W)', fontsize=14, fontweight='bold')
axes3[1].legend(loc='best', ncol=3, fontsize=10, framealpha=0.9)
axes3[1].grid(True, alpha=0.3)

plt.tight_layout(pad=3.0)
plt.show()

# Figure 4: Basis Functions
fig4, ax4 = plt.subplots(1, 1, figsize=(16, 6))

for i in range(5):
    ax4.plot(t_rec, beta_rec[:, i], label=weight_labels[i], linewidth=2.5, color=colors[i])
ax4.axvline(x=20, color='red', linestyle='--', alpha=0.4, linewidth=2, label='Uncertainty Start')
ax4.set_ylabel('Basis Function Values', fontsize=12)
ax4.set_xlabel('Time (s)', fontsize=12)
ax4.set_title('Basis Functions β(x)', fontsize=14, fontweight='bold')
ax4.legend(loc='best', ncol=3, fontsize=10, framealpha=0.9)
ax4.grid(True, alpha=0.3)

plt.tight_layout(pad=2.0)
plt.show()

# Print summary statistics
print("\n=== Derivative-Free Adaptive Control Summary ===")
print(f"Uncertainty turned on at t=20s")
print(f"Final position tracking error: {e_rec[-1, 0]:.4f} deg")
print(f"Final velocity tracking error: {e_rec[-1, 1]:.4f} deg/s")
print(f"Max position error: {np.max(np.abs(e_rec[:, 0])):.4f} deg")
print(f"Max velocity error: {np.max(np.abs(e_rec[:, 1])):.4f} deg/s")
print(f"RMS position error: {np.sqrt(np.mean(e_rec[:, 0]**2)):.4f} deg")
print(f"RMS velocity error: {np.sqrt(np.mean(e_rec[:, 1]**2)):.4f} deg/s")

# >> [image dropped]
# >> <Figure size 1600x1000 with 2 Axes>
# >> [image dropped]
# >> <Figure size 1600x1400 with 3 Axes>
# >> [image dropped]
# >> <Figure size 1600x1200 with 2 Axes>
# >> [image dropped]
# >> <Figure size 1600x600 with 1 Axes>
# >>
# >> === Derivative-Free Adaptive Control Summary ===
# >> Uncertainty turned on at t=20s
# >> Final position tracking error: 0.0215 deg
# >> Final velocity tracking error: 0.0038 deg/s
# >> Max position error: 0.4520 deg
# >> Max velocity error: 0.3258 deg/s
# >> RMS position error: 0.1238 deg
# >> RMS velocity error: 0.0718 deg/s

# %% [cell 5] markdown
# T = 1
# === Derivative-Free Adaptive Control Summary ===
# Uncertainty turned on at t=20s
# Final position tracking error: -0.5515 deg
# Final velocity tracking error: 1.3702 deg/s
# Max position error: 10.6377 deg
# Max velocity error: 5.8542 deg/s
# RMS position error: 3.1957 deg
# RMS velocity error: 1.7734 deg/s
#
# T = 0.1
# === Derivative-Free Adaptive Control Summary ===
# Uncertainty turned on at t=20s
# Final position tracking error: -0.0785 deg
# Final velocity tracking error: 1.2182 deg/s
# Max position error: 8.2297 deg
# Max velocity error: 3.5622 deg/s
# RMS position error: 2.5767 deg
# RMS velocity error: 1.1959 deg/s
#
# gamma2 = 10
# === Derivative-Free Adaptive Control Summary ===
# Uncertainty turned on at t=20s
# Final position tracking error: 0.0188 deg
# Final velocity tracking error: 0.0977 deg/s
# Max position error: 1.4393 deg
# Max velocity error: 0.7964 deg/s
# RMS position error: 0.4232 deg
# RMS velocity error: 0.1895 deg/s
#
# gamma1 = 0.9
# === Derivative-Free Adaptive Control Summary ===
# Uncertainty turned on at t=20s
# Final position tracking error: 0.0215 deg
# Final velocity tracking error: 0.0038 deg/s
# Max position error: 0.4520 deg
# Max velocity error: 0.3258 deg/s
# RMS position error: 0.1238 deg
# RMS velocity error: 0.0718 deg/s

# %% [cell 6] code
# Set-theoretic Neuro-Adaptive control with barier function for a 2D system with nonlinear uncertainty
import numpy as np
import control as ct
import matplotlib.pyplot as plt

ft = 40 # simulation time in seconds
dt = 0.005 # time step in seconds

A = np.array([[0, 1], [0, 0]]) # A matrix of the system
B = np.array([[0], [1]]) # B matrix of the system
C = np.array([[1, 0]]) # output matrix
x = np.array([[0.], [0.]]) # initial state

K1 = ct.lqr(A, B, np.eye(2), 0.1)[0] # LQR gain
K2 = - 1 / (C @ np.linalg.inv(A - B @ K1) @ B)[0, 0] # Feedforward gain
Ar = A - B @ K1 # reference model A matrix
Br = B * K2 # reference model B matrix
xr = np.array([[0.], [0.]]) # initial reference model state

eps = 0.005 # User defined error bound

gam1 = 0.25 # Adaptation gain for What
gam2 = 0.25 # Adaptation gain for qhat
zeta = 0.25 # Leakage gain for qhat

web1L = 10 # Projection lower bound for What
web1U = 10 # Projection upper bound for What
qb1L = 0 # Projection lower bound for qhat
qb1U = 10 # Projection upper bound for qhat
tol = 0.1 # Projection tolerance

P = ct.lyap(Ar.T, np.eye(2)) # Solve Lyapunov for reference model
What = np.zeros((11,1)) # initial weight estimate - matches regressor size
qhat = 1.0 # initial estimate of q
c = 0.0 # initial command

numb_rbf = 11 # number of RBF neurons

def rbf(x, c, width):
    # MATLAB formula: exp(-width*(abs(x-c))^2)
    return np.exp(-width * abs(x - c)**2)

neurons = np.ones((numb_rbf,1)) # RBF neuron output vector

# Data recording arrays
x_rec = [] # state record
xr_rec = [] # reference model state record
c_rec = [] # command record
phid_rec = [] # barrier function derivative record
u_rec = [] # control record
e_rec = [] # tracking error record
t_rec = [] # time record
unc_rec = [] # uncertainty record
uad_rec = [] # adaptive control record



for t in np.arange(0, ft, dt):
    # Reference Command
    if t <= 10 :
        cmd = 0.5
    elif 10 < t <= 20 :
        cmd = -0.5
    elif 20 < t <= 30 :
        cmd = 0.5
    else :
        cmd = -0.5
    c = c + dt*4*(cmd - c) # first-order filter for command

    # Rbf neurons
    # numb_rbf = 11: neuron[0] is constant=1, neurons[1-5] for position, neurons[6-10] for velocity
    num_centers_per_state = (numb_rbf - 1) // 2  # 5 centers per state
    centers_pos = np.linspace(-2, 2, num_centers_per_state)
    centers_vel = np.linspace(-2, 2, num_centers_per_state)
    widths = np.ones(numb_rbf) * 0.25
    
    # neurons[0] stays at 1 (constant bias term)
    # neurons[1-5] use position state with centers_pos
    for i in range(1, num_centers_per_state + 1):
        neurons[i, 0] = rbf(x[0, 0], centers_pos[i-1], widths[i])
    
    # neurons[6-10] use velocity state with centers_vel
    for i in range(num_centers_per_state + 1, numb_rbf):
        neurons[i, 0] = rbf(x[1, 0], centers_vel[i - num_centers_per_state - 1], widths[i])

    
    # tracking error
    e = x - xr 
    # barrier function derivative
    phid = (eps - 0.5*np.sqrt(e.T @ P @ e)) / ((eps -  np.sqrt(e.T @ P @ e)))**2 

    v = np.tanh(phid*B.T @ P @ e) * qhat # barrier function
    u = -K1 @ x + K2 * c - v - What.T @ neurons # control input
    xr = xr + dt * (Ar @ xr + Br * c) # reference model update

    PR = phid * neurons @ e.T @ P @ B # projection regressor
    for i in range(11):
        # Weight update with projection
        if What[i,0] > web1U - tol and PR[i,0] > 0:
            PR[i,0] = (web1U - What[i,0]) * PR[i,0] / tol 
        elif What[i,0] < -web1L + tol and PR[i,0] < 0:
            PR[i,0] = (What[i,0] + web1L) * PR[i,0] / tol

    What = What + dt * (gam1 * PR) # weight update

    PR2 = phid * e.T @ P @ B * np.tanh(phid * B.T @ P @ e) - zeta * qhat# projection regressor for qhat
    if qhat > qb1U - tol and PR2 > 0:
        PR2 = (qb1U - qhat) * PR2 / tol
    elif qhat < -qb1L + tol and PR2 < 0:
        PR2 = (qhat + qb1L) * PR2 / tol
    qhat = qhat + dt * (gam2 * PR2) # qhat update

    x0 = x[0, 0]
    x1 = x[1, 0]
    # Arbitrary nonlinearity
    uncertainty = 1.0 + x0**2 + 2*x0**2 * x1**2 + np.sin(x0) * x1**3 + np.cos(x1) * x0**4

    x = x + dt * (A @ x + B * (u + uncertainty)) # state update

    # Record data
    x_rec.append(x.flatten())
    xr_rec.append(xr.flatten())
    c_rec.append(c)
    phid_rec.append(phid.flatten())
    u_rec.append(u.flatten())
    e_rec.append(np.sqrt(e.T @ P @ e).flatten()) 
    t_rec.append(t)
    unc_rec.append(uncertainty)
    uad_rec.append((- What.T @ neurons).flatten())

# Convert lists to numpy arrays for easier plotting
x_rec = np.array(x_rec)
xr_rec = np.array(xr_rec)
c_rec = np.array(c_rec)
phid_rec = np.array(phid_rec)
u_rec = np.array(u_rec)
e_rec = np.array(e_rec)
t_rec = np.array(t_rec)
unc_rec = np.array(unc_rec)
uad_rec = np.array(uad_rec)

# Set matplotlib defaults for better readability
plt.rcParams.update({
    'font.size': 11,
    'axes.titlesize': 13,
    'axes.labelsize': 11,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.titlesize': 14
})

# Plotting - Split into multiple figures for better visibility
# Figure 1: State Tracking (Position and Velocity)
fig1, axes1 = plt.subplots(2, 1, figsize=(16, 10))

axes1[0].plot(t_rec, x_rec[:, 0], label='Actual Position', linewidth=2.5, color='#1f77b4')
axes1[0].plot(t_rec, xr_rec[:, 0], '--', label='Reference Model Position', linewidth=2.5, color='#ff7f0e')
axes1[0].plot(t_rec, c_rec, ':', label='Command', linewidth=2, alpha=0.8, color='#2ca02c')
axes1[0].set_ylabel('Position', fontsize=12)
axes1[0].set_xlabel('Time (s)', fontsize=12)
axes1[0].set_title('Position Tracking - Set-Theoretic Neuro-Adaptive Control', fontsize=14, fontweight='bold')
axes1[0].legend(loc='best', fontsize=11, framealpha=0.9)
axes1[0].grid(True, alpha=0.3)

axes1[1].plot(t_rec, x_rec[:, 1], label='Actual Velocity', linewidth=2.5, color='#1f77b4')
axes1[1].plot(t_rec, xr_rec[:, 1], '--', label='Reference Model Velocity', linewidth=2.5, color='#ff7f0e')
axes1[1].set_ylabel('Velocity', fontsize=12)
axes1[1].set_xlabel('Time (s)', fontsize=12)
axes1[1].set_title('Velocity Tracking', fontsize=14, fontweight='bold')
axes1[1].legend(loc='best', fontsize=11, framealpha=0.9)
axes1[1].grid(True, alpha=0.3)

plt.tight_layout(pad=3.0)
plt.show()

# Figure 2: Tracking Error and Barrier Function
fig2, axes2 = plt.subplots(2, 1, figsize=(16, 10))

axes2[0].plot(t_rec, e_rec, label='Tracking Error ||e||_P', linewidth=2.5, color='#d62728')
axes2[0].axhline(y=eps, color='red', linestyle='--', alpha=0.6, linewidth=2, label=f'Error Bound ε = {eps}')
axes2[0].set_ylabel('Tracking Error Norm', fontsize=12)
axes2[0].set_xlabel('Time (s)', fontsize=12)
axes2[0].set_title('Lyapunov-based Tracking Error with Prescribed Bound', fontsize=14, fontweight='bold')
axes2[0].legend(loc='best', fontsize=11, framealpha=0.9)
axes2[0].grid(True, alpha=0.3)

axes2[1].plot(t_rec, phid_rec, label='Barrier Function Derivative φ\'', linewidth=2.5, color='#9467bd')
axes2[1].set_ylabel('φ\' Value', fontsize=12)
axes2[1].set_xlabel('Time (s)', fontsize=12)
axes2[1].set_title('Barrier Function Derivative', fontsize=14, fontweight='bold')
axes2[1].legend(loc='best', fontsize=11, framealpha=0.9)
axes2[1].grid(True, alpha=0.3)

plt.tight_layout(pad=3.0)
plt.show()

# Figure 3: Control Inputs and Uncertainty
fig3, axes3 = plt.subplots(3, 1, figsize=(16, 14))

axes3[0].plot(t_rec, u_rec[:, 0], label='Total Control u', linewidth=2.5, color='#1f77b4')
axes3[0].set_ylabel('Control Input u', fontsize=12)
axes3[0].set_xlabel('Time (s)', fontsize=12)
axes3[0].set_title('Total Control Input', fontsize=14, fontweight='bold')
axes3[0].legend(loc='best', fontsize=11, framealpha=0.9)
axes3[0].grid(True, alpha=0.3)

axes3[1].plot(t_rec, uad_rec[:, 0], label='Adaptive Control (-Ŵ^T σ)', linewidth=2.5, color='#ff7f0e')
axes3[1].set_ylabel('Adaptive Control', fontsize=12)
axes3[1].set_xlabel('Time (s)', fontsize=12)
axes3[1].set_title('Neural Network Adaptive Component', fontsize=14, fontweight='bold')
axes3[1].legend(loc='best', fontsize=11, framealpha=0.9)
axes3[1].grid(True, alpha=0.3)

axes3[2].plot(t_rec, unc_rec, label='True Uncertainty', linewidth=2.5, color='#d62728')
axes3[2].plot(t_rec, -uad_rec[:, 0], '--', label='Estimated Uncertainty (-Ŵ^T σ)', linewidth=2.5, color='#1f77b4')
axes3[2].set_ylabel('Uncertainty Value', fontsize=12)
axes3[2].set_xlabel('Time (s)', fontsize=12)
axes3[2].set_title('Nonlinear Uncertainty: True vs RBF Neural Network Estimate', fontsize=14, fontweight='bold')
axes3[2].legend(loc='best', fontsize=11, framealpha=0.9)
axes3[2].grid(True, alpha=0.3)

plt.tight_layout(pad=3.0)
plt.show()

# Print summary statistics
print("\n=== Set-Theoretic Neuro-Adaptive Control Summary ===")
print(f"Prescribed error bound ε: {eps:.4f}")
print(f"Final tracking error ||e||_P: {e_rec[-1]}")
print(f"Max tracking error: {np.max(e_rec):.4f}")
print(f"Error bound violated: {'Yes' if np.max(e_rec) > eps else 'No'}")
print(f"Final position error: {x_rec[-1, 0] - xr_rec[-1, 0]:.4f}")
print(f"Final velocity error: {x_rec[-1, 1] - xr_rec[-1, 1]:.4f}")
print(f"Max control effort: {np.max(np.abs(u_rec)):.4f}")
print(f"RBF neurons: {numb_rbf}")
print(f"Adaptation gains: γ₁={gam1}, γ₂={gam2}")
# >> [image dropped]
# >> <Figure size 1600x1000 with 2 Axes>
# >> [image dropped]
# >> <Figure size 1600x1000 with 2 Axes>
# >> [image dropped]
# >> <Figure size 1600x1400 with 3 Axes>
# >>
# >> === Set-Theoretic Neuro-Adaptive Control Summary ===
# >> Prescribed error bound ε: 0.0050
# >> Final tracking error ||e||_P: [1.87340261e-05]
# >> Max tracking error: 0.0034
# >> Error bound violated: No
# >> Final position error: 0.0000
# >> Final velocity error: -0.0000
# >> Max control effort: 2.4326
# >> RBF neurons: 11
# >> Adaptation gains: γ₁=0.25, γ₂=0.25

# %% [cell 7] code
# Low Frequency learning adaptive control
import numpy as np
import control as ct
import matplotlib.pyplot as plt


ft = 40 # simulation time in seconds
dt = 0.005 # time step in seconds

A = np.array([[0, 1], [0, 0]]) # A matrix of the system
B = np.array([[0], [1]]) # B matrix of the system
C = np.array([[1, 0]]) # output matrix
W = np.array([[1], [-1], [2]]) # true weights for uncertainty
x = np.array([[0.], [0.]]) # initial state

K1 = ct.lqr(A, B, np.eye(2), 0.1)[0] # LQR gain
K2 = - 1 / (C @ np.linalg.inv(A - B @ K1 ) @ B)[0, 0] # Feedforward gain
Ar = A - B @ K1 # reference model A matrix
Br = B * K2 # reference model B matrix
xr = np.array([[0.], [0.]]) # initial reference model state

gam = 250 # High adaptation gain
sigm = 0.1 # Low-frequency learning gain sigma
gamf = 0.5 # Low-frequency learning gain gammaf
P = ct.lyap(Ar.T, np.eye(2)) # Solve Lyapunov for reference model
What = np.zeros((3,1)) # initial weight estimate - matches regressor size
Whatf = np.zeros((3,1)) # initial low-frequency weight estimate
c = 0.0 # initial command


x_rec = [] # state record
xr_rec = [] # reference model state record
u_rec = [] # control record
t_rec = [] # time record

for t in np.arange(0, ft, dt):
        # Reference Command
    if t <= 10 :
        cmd = 1.0
    elif 10 < t <= 20 :
        cmd = -1.0
    elif 20 < t <= 30 :
        cmd = 1.0
    else :
        cmd = -1.0
    c = c + dt*(cmd - c) # first-order filter for command

    un = -K1 @ x + K2 * c # nominal control
    x0 = x[0,0]
    x1 = x[1,0] 
    theta = np.array([[np.sin(x0)*x0], [x1**3], [abs(x0)*x1]]) # regressor
    ua = -What.T @ theta # adaptive control
    u = un + ua # total control

    xr = xr + dt * (Ar @ xr + Br * c) # reference model update
    What = What + dt * ( gam * (theta @ (x - xr).T @ P @ B - sigm * (What - Whatf))) # weight update
    Whatf = Whatf + dt * ( gamf * (What - Whatf)) # low-frequency weight update

    # Uncertain System
    x = x + dt * (A @ x + B * (u + W.T @ theta))

    # Save Data
    x_rec.append(x.flatten())
    xr_rec.append(xr.flatten())
    u_rec.append(u.flatten())
    t_rec.append(t)

# Convert lists to numpy arrays for easier plotting
x_rec = np.array(x_rec)
xr_rec = np.array(xr_rec)
u_rec = np.array(u_rec)
t_rec = np.array(t_rec)
e_rec = x_rec - xr_rec # tracking error

# Set matplotlib defaults for better readability
plt.rcParams.update({
    'font.size': 11,
    'axes.titlesize': 13,
    'axes.labelsize': 11,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.titlesize': 14
})

# Plotting
fig, axes = plt.subplots(3, 1, figsize=(16, 12))

# Plot position tracking
axes[0].plot(t_rec, x_rec[:, 0], label='Actual Position', linewidth=2.5, color='#1f77b4')
axes[0].plot(t_rec, xr_rec[:, 0], '--', label='Reference Position', linewidth=2.5, color='#ff7f0e')
axes[0].set_ylabel('Position', fontsize=12)
axes[0].set_xlabel('Time (s)', fontsize=12)
axes[0].set_title('Position Tracking - Low Frequency Learning Adaptive Control', fontsize=14, fontweight='bold')
axes[0].legend(loc='best', fontsize=11, framealpha=0.9)
axes[0].grid(True, alpha=0.3)

# Plot velocity tracking
axes[1].plot(t_rec, x_rec[:, 1], label='Actual Velocity', linewidth=2.5, color='#1f77b4')
axes[1].plot(t_rec, xr_rec[:, 1], '--', label='Reference Velocity', linewidth=2.5, color='#ff7f0e')
axes[1].set_ylabel('Velocity', fontsize=12)
axes[1].set_xlabel('Time (s)', fontsize=12)
axes[1].set_title('Velocity Tracking', fontsize=14, fontweight='bold')
axes[1].legend(loc='best', fontsize=11, framealpha=0.9)
axes[1].grid(True, alpha=0.3)

# Plot control input
axes[2].plot(t_rec, u_rec[:, 0], label='Control Input', linewidth=2.5, color='#9467bd')
axes[2].set_ylabel('Control u', fontsize=12)
axes[2].set_xlabel('Time (s)', fontsize=12)
axes[2].set_title('Control Input', fontsize=14, fontweight='bold')
axes[2].legend(loc='best', fontsize=11, framealpha=0.9)
axes[2].grid(True, alpha=0.3)

plt.tight_layout(pad=3.0)
plt.show()

# Print summary statistics
print("\n=== Low Frequency Learning Adaptive Control Summary ===")
print(f"Final position error: {e_rec[-1, 0]:.4f}")
print(f"Final velocity error: {e_rec[-1, 1]:.4f}")
print(f"Max position error: {np.max(np.abs(e_rec[:, 0])):.4f}")
print(f"Max velocity error: {np.max(np.abs(e_rec[:, 1])):.4f}")
print(f"RMS position error: {np.sqrt(np.mean(e_rec[:, 0]**2)):.4f}")
print(f"RMS velocity error: {np.sqrt(np.mean(e_rec[:, 1]**2)):.4f}")
print(f"Max control effort: {np.max(np.abs(u_rec)):.4f}")
print(f"Adaptation gain γ: {gam}")
print(f"LF learning gains: σ={sigm}, γf={gamf}")



# >> [image dropped]
# >> <Figure size 1600x1200 with 3 Axes>
# >>
# >> === Low Frequency Learning Adaptive Control Summary ===
# >> Final position error: 0.0134
# >> Final velocity error: -0.0009
# >> Max position error: 0.2221
# >> Max velocity error: 0.1277
# >> RMS position error: 0.0728
# >> RMS velocity error: 0.0407
# >> Max control effort: 1.6191
# >> Adaptation gain γ: 250
# >> LF learning gains: σ=0.1, γf=0.5

