# Extract of Roll_Pitch_Yaw_Adaptive_Control_FFcontroller_Sigma_modification.ipynb
# Generated by ground_station/research/notebooks/extract.py; do not edit.
# ruff: noqa

# %% [cell 0] markdown
# # 3DOF Adaptive Control Simulation
#
# This notebook implements a feedback-feedforward adaptive controller for a quadcopter drone dynamics (Pitch, Roll, Yaw).
# The code has been modularized for better readability and structure.
#
# ## 1. Environment Setup & System Parameters

# %% [cell 1] code
import numpy as np
import control as ct
import matplotlib.pyplot as plt

# ============================================
# SYSTEM PARAMETERS (Physical Drone Properties)
# ============================================

# Simulation Settings
dt = 0.006  # Time step [s]
ft = 100    # Simulation duration [s]

# Approximate moments of inertia [kg·m²]
Jx = 0.01   # Roll moment
Jy = 0.01   # Pitch moment
Jz = 0.02   # Yaw moment

# True inverse inertia matrix (System Control Authority)
# Lambda = diag(1/Jx, 1/Jy, 1/Jz)
Lambda_true = np.diag([1/Jx, 1/Jy, 1/Jz])

print("System Parameters Initialized:")
print(f"  Inertias: Jx={Jx}, Jy={Jy}, Jz={Jz}")
print(f"  Simulation: Total Time={ft}s, dt={dt}s")
# >> System Parameters Initialized:
# >>   Inertias: Jx=0.01, Jy=0.01, Jz=0.02
# >>   Simulation: Total Time=100s, dt=0.006s

# %% [cell 2] markdown
# ## 2. Reference Model Design
# Define the ideal behavior we want the drone to follow. We use a standardized 2nd-order system for each axis.

# %% [cell 3] code
# ============================================
# REFERENCE MODEL DESIGN
# ============================================
# Desired dynamics (2nd order response)
wn = 2.0   # Natural frequency [rad/s]
zeta = 0.8 # Damping ratio

# Single axis reference model state-space: x_dot = Am*x + Bm*r
# State x = [angle, angle_rate]
Am_single_axis = np.array([[0, 1],
                           [-wn**2, -2*zeta*wn]])
Bm_single_axis = np.array([[0], 
                           [wn**2]])

# Full 3-axis decoupled reference model (6 states: pitch, dp, roll, dr, yaw, dy)
Am = np.block([
    [Am_single_axis, np.zeros((2, 4))],
    [np.zeros((2,2)), Am_single_axis, np.zeros((2,2))],
    [np.zeros((2,4)), Am_single_axis]
               ])

Bm = np.block([
    [Bm_single_axis, np.zeros((2,2))],
    [np.zeros((2,1)), Bm_single_axis, np.zeros((2,1))],
    [np.zeros((2,2)), Bm_single_axis]
    ])

print("Reference Model Setup Complete.")
print(f"  Target Dynamics: wn={wn}, zeta={zeta}")
# >> Reference Model Setup Complete.
# >>   Target Dynamics: wn=2.0, zeta=0.8

# %% [cell 4] markdown
# ## 3. Nominal Controller Design
# Calculate the baseline controller gains ($K_1$, $K_2$) that would perfectly control the nominal plant (assuming no uncertainty or disturbances).
#
# Control Law: $u_{nom} = -K_1 x + K_2 r$

# %% [cell 5] code
# ============================================
# NOMINAL CONTROLLER DESIGN
# ============================================

# 1. Define Open-Loop Reduced Plant (Single Axis Integrator Chain)
#    x_dot = [0 1; 0 0]x + [0; 1]u (Torque -> Acceleration -> Angle)
A_single_axis = np.array([[0, 1],
                          [0, 0]])  
B_single_axis = np.array([[0], 
                          [1]])
C_single_axis = np.array([[1, 0]])

# 2. Assemble Full State Matrices
A_full = np.block([
    [A_single_axis, np.zeros((2,4))],
    [np.zeros((2,2)), A_single_axis, np.zeros((2,2))],
    [np.zeros((2,4)), A_single_axis]
])

B_full = np.block([
    [B_single_axis, np.zeros((2,2))],
    [np.zeros((2,1)), B_single_axis, np.zeros((2,1))],
    [np.zeros((2,2)), B_single_axis]
])

# 3. Compute Gains per Axis (Model Matching)
#    We need: A_cl = A - B_eff*K1 = Am
#             B_eff*K2 = Bm
#    Where B_eff includes the inertia term (Torque = I * alpha)

B_eff_pitch = B_single_axis / Jx
B_eff_roll = B_single_axis / Jy
B_eff_yaw = B_single_axis / Jz

K1_pitch = (np.linalg.pinv(B_eff_pitch) @ (A_single_axis - Am_single_axis)).flatten()
K2_pitch = (np.linalg.pinv(B_eff_pitch) @ Bm_single_axis).item()

K1_yaw = (np.linalg.pinv(B_eff_yaw) @ (A_single_axis - Am_single_axis)).flatten()
K2_yaw = (np.linalg.pinv(B_eff_yaw) @ Bm_single_axis).item()

K1_roll = (np.linalg.pinv(B_eff_roll) @ (A_single_axis - Am_single_axis)).flatten()
K2_roll = (np.linalg.pinv(B_eff_roll) @ Bm_single_axis).item()

# 4. Assemble Full Gain Matrices
K1 = np.vstack([
    np.concatenate([K1_pitch, np.zeros(4)]),
    np.concatenate([np.zeros(2), K1_roll, np.zeros(2)]),
    np.concatenate([np.zeros(4), K1_yaw])
])
K2 = np.diag([K2_pitch, K2_roll, K2_yaw])

# 5. Verify Stability
A_cl = A_full - B_full @ Lambda_true @ K1
eigs = np.linalg.eigvals(A_cl)
stable = np.all(np.real(eigs) < -1e-6)

print("Controller Gains Calculated:")
print(f"  Pitch: K1={K1_pitch}, K2={K2_pitch:.2f}")
print(f"  Roll : K1={K1_roll}, K2={K2_roll:.2f}")
print(f"  Yaw  : K1={K1_yaw}, K2={K2_yaw:.2f}")
print("System check:")
print(f"  Closed-loop Stable: {stable}")
print(f"  Max Eigenvalue Re: {np.max(np.real(eigs)):.4f}")

# 6. Lyapunov Matrix for Adaptive Law
P_single_axis = ct.lyap(Am_single_axis.T, np.eye(2))
print("\nLyapunov Matrix P computed.")
# >> Controller Gains Calculated:
# >>   Pitch: K1=[0.04  0.032], K2=0.04
# >>   Roll : K1=[0.04  0.032], K2=0.04
# >>   Yaw  : K1=[0.08  0.064], K2=0.08
# >> System check:
# >>   Closed-loop Stable: True
# >>   Max Eigenvalue Re: -1.6000
# >>
# >> Lyapunov Matrix P computed.

# %% [cell 6] markdown
# ## 4. Configuration & Hyperparameters
# Here we define the behavior of the adaptive controller, including feature flags, learning rates, and stability constraints.

# %% [cell 7] code
# ============================================
# FEATURE FLAGS (Configuration)
# ============================================
class Config:
    # Main Control Loop Switches
    ADAPTATION_ON = True                  # Enable adaptive control loop
    PERFORMANCE_RECOVERY_ON = True        # Enable L1-like performance recovery
    
    # Advanced Adaptive Features
    INCLUDE_CONTROL_IN_REGRESSOR = True   # Compensate for input effectiveness (Lambda)
    USE_LOW_FREQUENCY_LEARNING = True     # Use low-pass filtered learning (L1 adaptive style)
    USE_WEIGHT_NORMALIZATION = True       # Normalize regressor to improves robustness
    
    # Stability Enhancements (DISABLED - these cause overflow when combined)
    USE_ADAPTIVE_DEADZONE = False         # Stop adapting if error is small
    USE_EXPONENTIAL_FORGETTING = False    # Forget weights over time if error is zero
    USE_GAMMA_SCHEDULING = True           # Ramp up learning rate at start
    
    # Safety Limits (DISABLED - conflicts with performance recovery)
    USE_CONTROL_RATE_LIMITING = False     # Prevent actuator spikes
    USE_ADAPTIVE_SATURATION = False       # Limit max adaptive torque
    
    # Simulation Environment
    TIME_VARYING_UNCERTAINTY = True       # Simulate changing environment/disturbances

print("Configuration Loaded.")
# >> Configuration Loaded.

# %% [cell 8] code
# ============================================
# ADAPTIVE & STABILITY PARAMETERS
# ============================================

# 1. Protection Limits
DEADZONE_THRESHOLD = 0.05      # [deg] No adaptation if error is below this
MAX_CONTROL_RATE = {           # [N·m/s] Rate limit for actuators
    'pitch': 5.0,
    'roll': 5.0,
    'yaw': 3.0
}
MAX_ADAPTIVE_TORQUE = {        # [N·m] Max authority for adaptive term
    'pitch': 0.5,
    'roll': 0.5,
    'yaw': 0.3
}

# 2. Adaptive Law Parameters


GAMMA_FINAL = {           # Final learning rate
    'pitch': 350.0,
    'roll': 350.0,
    'yaw': 350.0
}

TAU_GAMMA = 25.0          # [s] Time constant for Gamma ramp-up (Scheduling)

SIGMA = {                 # Leakage/Damping factor
    'pitch': 0.8,
    'roll': 0.8,
    'yaw': 1.0            # Higher damping for Yaw
}

# 3. Forgetting Factor
FORGETTING_TIME_CONSTANT = 30.0  # [s] How fast weights decay when settled
MIN_GAMMA_RATIO = 0.1            # Minimum gamma when fully settled

# 4. Low-Frequency Learning Filter
GAM_F = 4                 # Filter gain for weight low-pass

# 5. Regressor Setup
NUM_BASIS_BASE = 6        # [bias, angle, rate, drag, sin, gyro]
NUM_BASIS = NUM_BASIS_BASE + 2 if Config.INCLUDE_CONTROL_IN_REGRESSOR else NUM_BASIS_BASE

print("Stability & Adaptive parameters defined.")
# >> Stability & Adaptive parameters defined.

# %% [cell 9] code
# ============================================
# PERFORMANCE RECOVERY PARAMETERS
# ============================================
# Theory: lam should be small enough relative to reference dynamics
# Rule of thumb: lam << min(|eig(Am)|) / Lambda_max

class PerfRec:
    # Filter gains (Lambda variable in L1 theory, 'lam' here)
    # CRITICAL: Use a single scalar lam for simplicity (like working version)
    # Rule: lam should be moderate, not too high for high-gain systems
    LAMBDA_SCALAR = 100  # Single value used for all axes
    tau_v_scalar = 0.8
    LAMBDA = {
        'pitch': 100,
        'roll': 100,
        'yaw': 100
    }
    
    # Current filtering (Low pass filter on v)
    USE_FILTERED = True
    TAU_V = {        # Time constant for v-filter [s]
        'pitch': 0.8,
        'roll': 0.8,
        'yaw': 0.8
    }
print("Performance Recovery parameters defined.")
# >> Performance Recovery parameters defined.

# %% [cell 10] markdown
# ## 5. Helper Functions & Math Utilities
# This section contains the core mathematical functions for the adaptive controller, including regressor construction, uncertainty simulation, and signal processing helper functions.

# %% [cell 11] code
# HELPER FUNCTIONS
# ============================================

def get_scheduled_gamma(t, gamma_final, tau):
    """
    Exponential gamma scheduling.
    Starts at 0 and ramps up to gamma_final with time constant tau.
    """
    return gamma_final * (1.0 - np.exp(-t / tau))

def wrap_angle(angle_rad):
    """
    Wraps angle to [-π, π] range.
    Critical for Yaw axis to prevent unbounded angle accumulation.
    Using modulo version (more numerically stable for integration).
    """
    return (angle_rad + np.pi) % (2 * np.pi) - np.pi

def compute_basis(bias, angle, angle_rate, gyroscopic_coupling):
    """
    Computes the base regressor vector (Phi) containing physical features.
    These features represent the structure of the uncertainty we expect.
    """
    # 1. Constant bias (e.g., CoM offset)
    # 2. Angle proportional (e.g., spring-like effects)
    # 3. Rate proportional (e.g., damping)
    # 4. Nonlinear drag (e.g., aerodynamic drag ~ rate^2)
    # 5. Sinusoidal gravity (e.g., pendulum effect)
    # 6. Gyroscopic coupling from other axes
    theta = np.array([
        [bias],
        [angle],
        [angle_rate],
        [angle_rate * np.tanh(angle_rate)], 
        [np.sin(angle)],
        [gyroscopic_coupling]
        ]) 
    return theta

def compute_extended_regressor(theta_base, un_axis, v_axis):
    """
    Extends the base regressor with control signals.
    Allows the adaptive law to compensate for input effectiveness uncertainty (Lambda).
    
    Returns: [theta_base; un; v]
    """
    return np.vstack([theta_base, [[un_axis]], [[v_axis]]])

print("Helper functions defined.")
# >> Helper functions defined.

# %% [cell 12] code
#  ENVIRONMENT SIMULATION (Uncertainty & Commands)
# ============================================

def compute_time_varying_uncertainty(t, x, level='medium'):
    """
    Generates synthetic 'True' uncertainty weights (W_true) to simulate
    disturbances and unmodeled dynamics.
    
    Levels:
    - 'easy': Slowly changing drag
    - 'medium': Mass/Payload shifts
    - 'hard': Aggressive aerobatics/stall conditions
    """
    # Extract states
    pitch, pitch_dot = x[0, 0], x[1, 0]
    roll, roll_dot = x[2, 0], x[3, 0]
    
    # Initialize basic weights (same structure as compute_basis)
    # [bias, angle, rate, drag, sin, gyro]
    
    if level == 'medium':
        # Piecewise time-varying scenario (Payload shift)
        if t < 30: mass_shift = 0.0
        elif t < 35: mass_shift = (t - 30) / 5.0
        elif t < 60: mass_shift = 1.0
        elif t < 65: mass_shift = 1.0 - (t - 60) / 5.0
        else: mass_shift = 0.0
        
        coupling_gain = 0.08 + 0.12 * mass_shift
        bias_offset = 0.15 * mass_shift
        
        W_pitch = np.array([[0.1+bias_offset], [0.05], [0.02], [0.15], [0.03+0.02*mass_shift], [coupling_gain]])
        W_roll  = np.array([[0.1+bias_offset], [0.05], [0.02], [0.15], [0.03+0.02*mass_shift], [coupling_gain]])
        W_yaw   = np.array([[0.05], [0.08+0.05*mass_shift], [0.01], [0.0], [0.02], [coupling_gain]])
        
    elif level == 'hard':
        # High frequency vibrations + stall effects
        vibe = 0.02 * np.sin(15 * t)
        stall_p = 0.3 if np.abs(pitch_dot) > 0.35 else 0.0
        
        W_pitch = np.array([[0.1+vibe], [0.05], [0.02+stall_p], [0.15], [0.03], [0.08]])
        W_roll  = np.array([[0.1+vibe], [0.05], [0.02], [0.15], [0.03], [0.08]])
        W_yaw   = np.array([[0.05], [0.08], [0.01], [0.0], [0.02], [0.06]])
        
    else: # Easy
        drag = 0.1 + 0.05 * np.sin(0.2 * t)
        W_pitch = np.array([[0.1], [0.05], [0.02*drag], [0.15*drag], [0.03], [0.08]])
        W_roll  = np.array([[0.1], [0.05], [0.02*drag], [0.15*drag], [0.03], [0.07]])
        W_yaw   = np.array([[0.05], [0.08], [0.01*drag], [0.0], [0.02], [0.06]])
        
    return W_pitch, W_roll, W_yaw

def wrap_angle(angle):
    """Wrap angle to [-π, π]"""
    return (angle + np.pi) % (2 * np.pi) - np.pi

def compute_reference_trajectory(t, level='easy'):
    """
    Generate realistic time-varying reference trajectories for drone attitude control.
    
    Parameters:
    -----------
    t : float
        Current simulation time [seconds]
    level : str or int
        Difficulty level: 'easy'/'1', 'medium'/'2', 'hard'/'3', 'extreme'/'4'
        
    Returns:
    --------
    r : np.ndarray (3x1)
        Reference angles [pitch, roll, yaw] in RADIANS
        
    Physical Scenarios:
    -------------------
    Level 1 (easy): Slow stabilization and gentle transitions
        - Hover stabilization → gentle tilt → return to level
        - Step responses with long settle times
        - Typical for: GPS waypoint navigation, aerial photography
        
    Level 2 (medium): Dynamic maneuvering with coupled motions
        - Coordinated turns (simultaneous pitch/roll/yaw)
        - Rectangular flight pattern
        - Typical for: FPV racing (moderate speed), inspection tasks
        
    Level 3 (hard): Aggressive aerobatic flight
        - Fast attitude changes, flips, high-rate maneuvers
        - Continuous sinusoidal excitation (multiple frequencies)
        - Typical for: FPV racing (high speed), aerobatics, evasive maneuvers
        
    Level 4 (extreme): Chaotic/unpredictable disturbance rejection
        - Random walk + sinusoidal + step changes
        - Multi-frequency excitation with varying amplitudes
        - Typical for: Extreme turbulence, emergency recovery, stress testing
    """
    
    deg2rad = np.pi / 180.0
    
    # ========================================================================
    # LEVEL 1: SLOW STABILIZATION AND GENTLE TRANSITIONS (EASY)
    # ========================================================================
    if level in ['easy', '1', 'level1', 1]:
        # Smooth step sequence with long dwell times
        if t < 20:
            # Initial hover (level attitude)
            pitch = 0.0
            roll = 0.0
            yaw = 0.0
        elif t < 40:
            # Forward tilt (slow acceleration)
            pitch = 8.0 * deg2rad
            roll = 0.0
            yaw = 0.0
        elif t < 60:
            # Left tilt with slight yaw
            pitch = 0.0
            roll = -8.0 * deg2rad
            yaw = 10.0 * deg2rad
        elif t < 80:
            # Return to level
            pitch = 0.0
            roll = 0.0
            yaw = 0.0
        else:
            # Backward tilt
            pitch = -8.0 * deg2rad
            roll = 0.0
            yaw = 0.0
    
    # ========================================================================
    # LEVEL 2: DYNAMIC MANEUVERING - RECTANGULAR PATTERN (MEDIUM)
    # ========================================================================
    elif level in ['medium', '2', 'level2', 2]:
        # Simulates rectangular flight pattern with coordinated turns
        phase = t % 40  # 40-second cycle
        
        if phase < 8:
            # Leg 1: Forward flight (pitch forward, level roll)
            pitch = 12.0 * deg2rad
            roll = 0.0
            yaw = 0.0 * deg2rad
        elif phase < 10:
            # Turn 1: Right turn (reduce pitch, roll right, yaw right)
            transition = (phase - 8) / 2.0  # 0 → 1 over 2 seconds
            pitch = 12.0 * (1 - transition) * deg2rad
            roll = 15.0 * transition * deg2rad
            yaw = 45.0 * transition * deg2rad
        elif phase < 18:
            # Leg 2: Right strafe
            pitch = 0.0
            roll = 12.0 * deg2rad
            yaw = 90.0 * deg2rad
        elif phase < 20:
            # Turn 2: Transition to backward
            transition = (phase - 18) / 2.0
            pitch = -12.0 * transition * deg2rad
            roll = 12.0 * (1 - transition) * deg2rad
            yaw = 90.0 + 45.0 * transition * deg2rad
        elif phase < 28:
            # Leg 3: Backward flight
            pitch = -12.0 * deg2rad
            roll = 0.0
            yaw = 180.0 * deg2rad
        elif phase < 30:
            # Turn 3: Left turn
            transition = (phase - 28) / 2.0
            pitch = -12.0 * (1 - transition) * deg2rad
            roll = -15.0 * transition * deg2rad
            yaw = 180.0 + 45.0 * transition * deg2rad
        elif phase < 38:
            # Leg 4: Left strafe
            pitch = 0.0
            roll = -12.0 * deg2rad
            yaw = 270.0 * deg2rad
        else:
            # Turn 4: Return to start
            transition = (phase - 38) / 2.0
            pitch = 12.0 * transition * deg2rad
            roll = -12.0 * (1 - transition) * deg2rad
            yaw = 270.0 + 45.0 * transition * deg2rad
    
    # ========================================================================
    # LEVEL 3: AGGRESSIVE AEROBATIC FLIGHT (HARD)
    # ========================================================================
    elif level in ['hard', '3', 'level3', 3]:
        # Multi-frequency sinusoidal excitation
        # Simulates aggressive FPV racing or aerobatic maneuvers
        
        # Pitch: Fast oscillation (0.3 Hz) + slow trend (0.05 Hz)
        pitch = (15.0 * np.sin(0.3 * 2*np.pi * t) + 
                 8.0 * np.sin(0.05 * 2*np.pi * t)) * deg2rad
        
        # Roll: Different frequency (0.25 Hz) + amplitude modulation
        amplitude_mod = 1.0 + 0.3 * np.sin(0.08 * 2*np.pi * t)
        roll = 18.0 * amplitude_mod * np.sin(0.25 * 2*np.pi * t) * deg2rad
        
        # Yaw: Continuous spinning with varying rate
        yaw_rate = 30.0 + 20.0 * np.sin(0.1 * 2*np.pi * t)  # deg/s
        yaw = (yaw_rate * t) * deg2rad
        
        # Add sudden "flip" maneuvers every 15 seconds
        if int(t) % 15 == 0 and (t % 1.0) < 0.5:  # 0.5s flip window
            pitch = pitch + 30.0 * deg2rad * np.sin(10 * t)
    
    # ========================================================================
    # LEVEL 4: CHAOTIC/UNPREDICTABLE DISTURBANCE REJECTION (EXTREME)
    # ========================================================================
    elif level in ['extreme', '4', 'level4', 4]:
        # Combination of random walk, multi-frequency, and sudden disturbances
        # Simulates extreme turbulence or adversarial conditions
        
        # Pseudo-random component (deterministic but looks random)
        np.random.seed(int(t * 100) % 10000)  # Changes every 0.01s
        random_pitch = np.random.uniform(-5, 5) * deg2rad
        random_roll = np.random.uniform(-5, 5) * deg2rad
        random_yaw = np.random.uniform(-10, 10) * deg2rad
        
        # Multi-frequency sinusoidal base
        pitch_base = (12.0 * np.sin(0.4 * 2*np.pi * t) + 
                      6.0 * np.sin(0.7 * 2*np.pi * t) +
                      3.0 * np.sin(1.2 * 2*np.pi * t)) * deg2rad
        
        roll_base = (15.0 * np.sin(0.35 * 2*np.pi * t) + 
                     7.0 * np.sin(0.9 * 2*np.pi * t) +
                     4.0 * np.cos(1.5 * 2*np.pi * t)) * deg2rad
        
        yaw_base = (25.0 * np.sin(0.2 * 2*np.pi * t) +
                    15.0 * np.sin(0.5 * 2*np.pi * t)) * deg2rad
        
        # Sudden step disturbances every 10 seconds
        disturbance_pitch = 0.0
        disturbance_roll = 0.0
        if int(t) % 10 == 0 and (t % 1.0) < 1.0:
            disturbance_pitch = 20.0 * deg2rad * (1 - (t % 1.0))
            disturbance_roll = -15.0 * deg2rad * (1 - (t % 1.0))
        
        # Combine all components
        pitch = pitch_base + random_pitch + disturbance_pitch
        roll = roll_base + random_roll + disturbance_roll
        yaw = yaw_base + random_yaw
        
        # Saturation (physical limits)
        pitch = np.clip(pitch, -35 * deg2rad, 35 * deg2rad)
        roll = np.clip(roll, -35 * deg2rad, 35 * deg2rad)
        yaw = np.clip(yaw, -180 * deg2rad, 180 * deg2rad)
    
    else:
        raise ValueError(f"Invalid level '{level}'. Use 'easy', 'medium', 'hard', or 'extreme'")
    
    # Return as column vector
    return np.array([[wrap_angle(pitch)], [wrap_angle(roll)], [wrap_angle(yaw)]])

print("Environment simulation functions defined.")
# >> Environment simulation functions defined.

# %% [cell 13] markdown
# ## 6. Simulation Loop
# This is the main execution block. It initializes the system state and steps through time, updating the drone dynamics, reference model, and adaptive laws at each step.

# %% [cell 14] code
# ============================================
# INITIALIZATION
# ============================================

# 1. State Vectors [pitch, dp, roll, dr, yaw, dy]
x = np.zeros((6,1))
xm = np.zeros((6,1))
xr = np.zeros((6,1))

# 2. Adaptive Weights Estimates (What)
What_pitch = np.zeros((NUM_BASIS, 1))
What_roll = np.zeros((NUM_BASIS, 1))
What_yaw = np.zeros((NUM_BASIS, 1))

# Low-frequency filtered weights (for L1 adaptive law)
Whatf_pitch = np.zeros((NUM_BASIS, 1))
Whatf_roll = np.zeros((NUM_BASIS, 1))
Whatf_yaw = np.zeros((NUM_BASIS, 1))

# 3. Signals & Filters
r_filtered = np.zeros((3, 1))
v = np.zeros((3,1))          # Performance recovery signal
v_filtered = np.zeros((3,1)) # Filtered v
f = np.zeros((6,1))          # State predictor for performance recovery

# Previous step values (for algebraic loops & rate limiting)
un_prev = np.zeros(3)
v_prev = np.zeros((3, 1))
u_prev = np.zeros(3)

# Settling timers (for deadzone logic)
settled_time = {'pitch': 0.0, 'roll': 0.0, 'yaw': 0.0}

# 4. Data Logging containers
log = {
    't': [], 'x': [], 'xm': [], 'xr': [], 'u': [],
    'ua': [], 'un': [], 'unc_true': [], 'e': [],
    
    # Extended logging for deep analysis (consistent with original notebook)
    'What_pitch': [], 'What_roll': [], 'What_yaw': [],
    'theta_pitch': [], 'theta_roll': [], 'theta_yaw': [],
    'v': []
}

# ============================================
# MAIN SIMULATION LOOP
# ============================================

print("Starting Simulation...")

for t in np.arange(0, ft, dt):
    
    # 1. Get Command & Environment
    r = compute_reference_trajectory(t, level='hard')
    # Pre-filter reference slightly to smooth steps
    r_filtered += dt * 4.0 * (r - r_filtered)
    
    if Config.TIME_VARYING_UNCERTAINTY:
        W_true_pitch, W_true_roll, W_true_yaw = compute_time_varying_uncertainty(t, x, level='hard')
        
    # indices for pitch (0,1), roll (2,3), yaw (4,5) inside x(6x1)

    # 2. Extract Axis States & Compute Regressors
    #    Note: Coupling terms (e.g. roll_dot * yaw_dot) come from physics
    pitch, dp = x[0,0], x[1,0]
    roll, dr = x[2,0], x[3,0]
    yaw, dy = x[4,0], x[5,0]
    
    theta_base_pitch = compute_basis(1.0, pitch, dp, dr*dy)
    theta_base_roll = compute_basis(1.0, roll, dr, dp*dy)
    theta_base_yaw = compute_basis(1.0, yaw, dy, dp*dr)
    
    # Extend regressor if using Lambda compensation
    if Config.INCLUDE_CONTROL_IN_REGRESSOR:
        theta_pitch = compute_extended_regressor(theta_base_pitch, un_prev[0], v_prev[0,0])
        theta_roll = compute_extended_regressor(theta_base_roll, un_prev[1], v_prev[1,0])
        theta_yaw  = compute_extended_regressor(theta_base_yaw, un_prev[2], v_prev[2,0])
    else:
        theta_pitch, theta_roll, theta_yaw = theta_base_pitch, theta_base_roll, theta_base_yaw

    # 3. Compute Adaptive Control (ua)
    if Config.ADAPTATION_ON:
        ua_pitch = -What_pitch.T @ theta_pitch
        ua_roll = -What_roll.T @ theta_roll
        ua_yaw = -What_yaw.T @ theta_yaw
        
        # Saturation
        if Config.USE_ADAPTIVE_SATURATION:
            ua_pitch = np.clip(ua_pitch, -MAX_ADAPTIVE_TORQUE['pitch'], MAX_ADAPTIVE_TORQUE['pitch'])
            ua_roll  = np.clip(ua_roll,  -MAX_ADAPTIVE_TORQUE['roll'],  MAX_ADAPTIVE_TORQUE['roll'])
            ua_yaw   = np.clip(ua_yaw,   -MAX_ADAPTIVE_TORQUE['yaw'],   MAX_ADAPTIVE_TORQUE['yaw'])
            
        ua = np.array([ua_pitch.item(), ua_roll.item(), ua_yaw.item()])
    else:
        ua = np.zeros(3)

    # 4. Performance Recovery (v)
    if Config.PERFORMANCE_RECOVERY_ON:
        e_state = x - xm
        
        # Simple first-order filter (scalar lam for all axes)
        lam = PerfRec.LAMBDA_SCALAR
        f += dt * (-lam * (f - e_state))
        g = lam * f + (Am - lam * np.eye(6)) @ e_state
        v_raw = np.linalg.pinv(B_full) @ g
        
        if PerfRec.USE_FILTERED:
            tau_v = PerfRec.tau_v_scalar
            v_filtered += dt * (v_raw - v_filtered) / tau_v
            v = v_filtered
        else:
            v = v_raw
    else:
        v = np.zeros((3,1))

    # 5. Nominal Control (un)
    #    u_nom = -K1*x + K2*r + v
    un_feedback = (-K1 @ x).flatten()
    un_feedforward = (K2 @ r_filtered).flatten()
    un = un_feedback + un_feedforward + v.flatten()

    # 6. Total Control Input
    u = un + ua
    
    # Rate Limiting
    if Config.USE_CONTROL_RATE_LIMITING:
        du = u - u_prev
        du_max = np.array([MAX_CONTROL_RATE['pitch'], MAX_CONTROL_RATE['roll'], MAX_CONTROL_RATE['yaw']]) * dt
        u = u_prev + np.clip(du, -du_max, du_max)
    u_prev = u.copy()
    
    # Store for next step (Algebraic loop prevention)
    un_prev = un.copy()
    v_prev = v.copy()

    # 7. Update System State (Integration)
    #    Real Physics: x_dot = A*x + B*Lambda*(u + Uncertainty)
    
    # Calculate true uncertainty torque (using base basis only)
    unc_pitch = (W_true_pitch.T @ theta_base_pitch).item()
    unc_roll = (W_true_roll.T @ theta_base_roll).item()
    unc_yaw = (W_true_yaw.T @ theta_base_yaw).item()
    unc_vec = np.array([[unc_pitch], [unc_roll], [unc_yaw]])

    x += dt * (A_full @ x + B_full @ Lambda_true @ (u.reshape(-1,1) + unc_vec))
    xm += dt * (Am @ xm + Bm @ r_filtered + (B_full @ v if Config.PERFORMANCE_RECOVERY_ON else 0))
    xr += dt * (Am @ xr + Bm @ r_filtered) # Pure reference model (no input aux)
    
    # Wrap ALL Angles (not just yaw) to prevent unbounded growth
    #x[0,0] = wrap_angle(x[0,0]); x[2,0] = wrap_angle(x[2,0]); x[4,0] = wrap_angle(x[4,0])
    #xm[0,0] = wrap_angle(xm[0,0]); xm[2,0] = wrap_angle(xm[2,0]); xm[4,0] = wrap_angle(xm[4,0])
    #xr[0,0] = wrap_angle(xr[0,0]); xr[2,0] = wrap_angle(xr[2,0]); xr[4,0] = wrap_angle(xr[4,0])

    # 8. Adaptive Law Update (Weights)
    if Config.ADAPTATION_ON:
        # Tracking Errors
        e_pitch_vec = np.array([[x[0,0] - xm[0,0]], [x[1,0] - xm[1,0]]])
        e_roll_vec  = np.array([[x[2,0] - xm[2,0]], [x[3,0] - xm[3,0]]])
        e_yaw_vec   = np.array([[x[4,0] - xm[4,0]], [x[5,0] - xm[5,0]]])
        
        # Deadzone Logic
        err_degs = [np.abs(e[0]*180/np.pi).item() for e in [e_pitch_vec, e_roll_vec, e_yaw_vec]]
        deadzones = []
        
        for i, axis in enumerate(['pitch', 'roll', 'yaw']):
            if Config.USE_ADAPTIVE_DEADZONE and err_degs[i] < DEADZONE_THRESHOLD:
                settled_time[axis] += dt
                deadzones.append(0.0)
            else:
                settled_time[axis] = 0.0
                deadzones.append(1.0)
        
        # Adaptation Gain Computation (Scheduling + Forgetting)
        gammas = {}
        for i, axis in enumerate(['pitch', 'roll', 'yaw']):
             g = get_scheduled_gamma(t, GAMMA_FINAL[axis], TAU_GAMMA) if Config.USE_GAMMA_SCHEDULING else GAMMA_FINAL[axis]
             if Config.USE_EXPONENTIAL_FORGETTING:
                 g *= (MIN_GAMMA_RATIO + (1-MIN_GAMMA_RATIO) * np.exp(-settled_time[axis] / FORGETTING_TIME_CONSTANT))
             gammas[axis] = g

        # Update Laws (Pitch example shown, same for others)
        def update_weight(What, Whatf, theta, e_vec, gamma, sigma, deadzone):
            norm = (1 + theta.T @ theta).item() if Config.USE_WEIGHT_NORMALIZATION else 1.0
            grad = theta @ (e_vec.T @ P_single_axis @ B_single_axis) * deadzone
            
            if Config.USE_LOW_FREQUENCY_LEARNING:
                # L1-style: dW = Gamma * (grad - Sigma*(W - Wf))
                What += dt * gamma * (grad - sigma * (What - Whatf)) / norm
                Whatf += dt * GAM_F * (What - Whatf)
            else:
                # Standard e-mod: dW = Gamma * (grad - Sigma*W)
                What += dt * gamma * (grad - sigma * What) / norm
            return What, Whatf

        What_pitch, Whatf_pitch = update_weight(What_pitch, Whatf_pitch, theta_pitch, e_pitch_vec, gammas['pitch'], SIGMA['pitch'], deadzones[0])
        What_roll, Whatf_roll   = update_weight(What_roll,  Whatf_roll,  theta_roll,  e_roll_vec,  gammas['roll'],  SIGMA['roll'],  deadzones[1])
        What_yaw, Whatf_yaw     = update_weight(What_yaw,   Whatf_yaw,   theta_yaw,   e_yaw_vec,   gammas['yaw'],   SIGMA['yaw'],   deadzones[2])

    # 9. Logging
    log['t'].append(t)
    log['x'].append(x.flatten().copy())
    log['xm'].append(xm.flatten().copy())
    log['xr'].append(xr.flatten().copy())
    log['u'].append(u.flatten().copy())
    log['ua'].append(ua.flatten().copy())
    log['un'].append(un.flatten().copy())
    log['unc_true'].append(unc_vec.flatten().copy())
    log['e'].append((x - xm).flatten().copy())
    
    # Detailed logs
    log['What_pitch'].append(What_pitch.flatten().copy())
    log['What_roll'].append(What_roll.flatten().copy())
    log['What_yaw'].append(What_yaw.flatten().copy())
    log['theta_pitch'].append(theta_pitch.flatten().copy())
    log['theta_roll'].append(theta_roll.flatten().copy())
    log['theta_yaw'].append(theta_yaw.flatten().copy())
    log['v'].append(v.flatten().copy())

print("Simulation Completed! Processing data...")

# Convert logs to numpy arrays for plotting
for key in log:
    log[key] = np.array(log[key])

print(f"Data points recorded: {len(log['t'])}")
# >> Starting Simulation...
# >> Simulation Completed! Processing data...
# >> Data points recorded: 16667

# %% [cell 15] code
# --- Data Logging for Plotting ---
rad2deg = 180.0 / np.pi
x_rec = log['x'] * rad2deg
xm_rec = log['xm'] * rad2deg
xr_rec = log['xr'] * rad2deg
u_rec = log['u']
t_rec = log['t']
What_pitch_rec = log['What_pitch']
What_roll_rec = log['What_roll']
What_yaw_rec = log['What_yaw']
e_pitch_rec = log['e'][:, [0,1]] * rad2deg
e_roll_rec = log['e'][:, [2,3]] * rad2deg
e_yaw_rec = log['e'][:, [4,5]] * rad2deg
ua_pitch_rec = log['ua'][:, 0]
ua_roll_rec = log['ua'][:, 1]
ua_yaw_rec = log['ua'][:, 2]
unc_pitch_rec = log['unc_true'][:, 0]
unc_roll_rec = log['unc_true'][:, 1]
unc_yaw_rec = log['unc_true'][:, 2]
un_rec = log['un']
v_rec = log['v']

# %% [cell 16] code
# FIGURE : QUANTITATIVE PERFORMANCE SUMMARY TABLE
# =============================================================================
print("="*80)
print("QUANTITATIVE PERFORMANCE METRICS")
print("="*80)
print(f"\nRegressor Configuration: {'EXTENDED (with un, v) - Λ Compensation' if Config.INCLUDE_CONTROL_IN_REGRESSOR else 'BASE (uncertainty only)'}")
print(f"Number of adaptive weights per axis: {What_pitch_rec.shape[1]}")


# Compute total error magnitude for each axis
pitch_error_mag = np.sqrt(e_pitch_rec[:, 0]**2 + e_pitch_rec[:, 1]**2)
roll_error_mag = np.sqrt(e_roll_rec[:, 0]**2 + e_roll_rec[:, 1]**2)
yaw_error_mag = np.sqrt(e_yaw_rec[:, 0]**2 + e_yaw_rec[:, 1]**2)

# Calculate metrics for each axis
axes_names = ['Pitch', 'Roll', 'Yaw']
error_mags = [pitch_error_mag, roll_error_mag, yaw_error_mag]
angle_errors = [e_pitch_rec[:, 0], e_roll_rec[:, 0], e_yaw_rec[:, 0]]

for i, axis_name in enumerate(axes_names):
    print(f"\n{axis_name} Axis:")
    print(f"  Max Angle Error:        {np.max(np.abs(angle_errors[i])):.3f}°")
    print(f"  Mean Angle Error:       {np.mean(np.abs(angle_errors[i])):.3f}°")
    print(f"  Final Angle Error:      {angle_errors[i][-1]:.3f}°")
    print(f"  RMS Error:              {np.sqrt(np.mean(error_mags[i]**2)):.3f}")
    print(f"  Max Control Torque:     {np.max(np.abs(u_rec[:, i])):.3f} N·m")
    print(f"  Total Control Effort:   {np.sum(np.abs(u_rec[:, i])) * dt:.3f} N·m·s")
    
    # Find settling time (time to stay within 2° permanently)
    within_threshold = np.abs(angle_errors[i]) < 2.0
    if np.any(within_threshold):
        # Find last time it exceeds threshold
        exceed_indices = np.where(~within_threshold)[0]
        if len(exceed_indices) > 0 and exceed_indices[-1] < len(t_rec) - 100:
            settling_time = t_rec[exceed_indices[-1] + 1]
            print(f"  Settling Time (<2°):    {settling_time:.2f} s")
        else:
            print(f"  Settling Time (<2°):    Not achieved")
    else:
        print(f"  Settling Time (<2°):    Not achieved")

print("\n" + "="*80)
print("ADAPTIVE WEIGHT FINAL VALUES")
print("="*80)

# Dynamic labels based on regressor configuration
basis_names_full = ["Bias", "Angle", "Rate", "Drag", "Sin", "Gyro Coupling"]
if Config.INCLUDE_CONTROL_IN_REGRESSOR:
    basis_names_full.extend(["un (ctrl eff)", "v (perf rec)"])

num_weights = What_pitch_rec.shape[1]
print(f"\n{'Parameter':<20} {'Pitch':<12} {'Roll':<12} {'Yaw':<12}")
print("-" * 56)
for i in range(num_weights):
    param_name = basis_names_full[i] if i < len(basis_names_full) else f"Weight {i+1}"
    print(f"{param_name:<20} {What_pitch_rec[-1, i]:>11.4f} {What_roll_rec[-1, i]:>11.4f} {What_yaw_rec[-1, i]:>11.4f}")

print("\n" + "="*80)

# Print insight about control effectiveness weights if extended regressor used
if Config.INCLUDE_CONTROL_IN_REGRESSOR:
    print("\n📊 CONTROL EFFECTIVENESS ADAPTATION INSIGHT:")
    print("-" * 56)
    print("The un and v weights adapt to compensate for Λ uncertainty.")
    print(f"  W_un (pitch): {What_pitch_rec[-1, -2]:.4f} → Adapts to control gain error")
    print(f"  W_v  (pitch): {What_pitch_rec[-1, -1]:.4f} → Adapts to perf recovery effect")
    print("\nIf Λ_true ≠ Λ_nom, these weights will be non-zero.")
    print("="*80)
# >> ================================================================================
# >> QUANTITATIVE PERFORMANCE METRICS
# >> ================================================================================
# >>
# >> Regressor Configuration: EXTENDED (with un, v) - Λ Compensation
# >> Number of adaptive weights per axis: 8
# >>
# >> Pitch Axis:
# >>   Max Angle Error:        2.573°
# >>   Mean Angle Error:       0.277°
# >>   Final Angle Error:      0.077°
# >>   RMS Error:              1.792
# >>   Max Control Torque:     0.449 N·m
# >>   Total Control Effort:   10.655 N·m·s
# >>   Settling Time (<2°):    4.42 s
# >>
# >> Roll Axis:
# >>   Max Angle Error:        1.863°
# >>   Mean Angle Error:       0.249°
# >>   Final Angle Error:      -0.038°
# >> [... 39 more output lines truncated]

# %% [cell 17] markdown
# # Diagnostics

# %% [cell 18] code
# DIAGNOSTIC: Check for unexpected large values
print("=" * 80)
print("DIAGNOSTIC: Data Range Check")
print("=" * 80)

print("\n📊 ANGLE VALUES (should be reasonable - tens to hundreds of degrees):")
print(f"Pitch angle    : min={x_rec[:, 0].min():,.2f}°, max={x_rec[:, 0].max():,.2f}°")
print(f"Roll angle     : min={x_rec[:, 2].min():,.2f}°, max={x_rec[:, 2].max():,.2f}°")
print(f"Yaw angle      : min={x_rec[:, 4].min():,.2f}°, max={x_rec[:, 4].max():,.2f}°")

print("\n📊 ANGULAR RATE VALUES (should be reasonable - typically < 500°/s):")
print(f"Pitch rate     : min={x_rec[:, 1].min():,.2f}°/s, max={x_rec[:, 1].max():,.2f}°/s")
print(f"Roll rate      : min={x_rec[:, 3].min():,.2f}°/s, max={x_rec[:, 3].max():,.2f}°/s")
print(f"Yaw rate       : min={x_rec[:, 5].min():,.2f}°/s, max={x_rec[:, 5].max():,.2f}°/s")

print("\n📊 REFERENCE MODEL ANGLE VALUES:")
print(f"Ref Pitch angle: min={xm_rec[:, 0].min():,.2f}°, max={xm_rec[:, 0].max():,.2f}°")
print(f"Ref Roll angle : min={xm_rec[:, 2].min():,.2f}°, max={xm_rec[:, 2].max():,.2f}°")
print(f"Ref Yaw angle  : min={xm_rec[:, 4].min():,.2f}°, max={xm_rec[:, 4].max():,.2f}°")

print("\n📊 REFERENCE MODEL RATE VALUES:")
print(f"Ref Pitch rate : min={xm_rec[:, 1].min():,.2f}°/s, max={xm_rec[:, 1].max():,.2f}°/s")
print(f"Ref Roll rate  : min={xm_rec[:, 3].min():,.2f}°/s, max={xm_rec[:, 3].max():,.2f}°/s")
print(f"Ref Yaw rate   : min={xm_rec[:, 5].min():,.2f}°/s, max={xm_rec[:, 5].max():,.2f}°/s")

print("\n" + "=" * 80)
if np.any(np.abs(x_rec) > 10000):
    print("⚠️  WARNING: Extremely large values detected (> 10,000)!")
    print("This indicates a simulation instability or numerical issue.")
elif np.any(np.abs(x_rec[:, [1,3,5]]) > 500):
    print("⚠️  CAUTION: Very high angular rates detected (> 500°/s)")
    print("This may indicate instability or overly aggressive control.")
else:
    print("✅ All values appear reasonable.")
# >> ================================================================================
# >> DIAGNOSTIC: Data Range Check
# >> ================================================================================
# >>
# >> 📊 ANGLE VALUES (should be reasonable - tens to hundreds of degrees):
# >> Pitch angle    : min=-18.27°, max=16.93°
# >> Roll angle     : min=-16.88°, max=16.69°
# >> Yaw angle      : min=-108.54°, max=162.74°
# >>
# >> 📊 ANGULAR RATE VALUES (should be reasonable - typically < 500°/s):
# >> Pitch rate     : min=-31.62°/s, max=38.51°/s
# >> Roll rate      : min=-26.84°/s, max=27.07°/s
# >> Yaw rate       : min=-172.22°/s, max=171.21°/s
# >>
# >> 📊 REFERENCE MODEL ANGLE VALUES:
# >> Ref Pitch angle: min=-18.20°, max=16.86°
# >> Ref Roll angle : min=-17.73°, max=16.73°
# >> Ref Yaw angle  : min=-108.53°, max=161.42°
# >>
# >> 📊 REFERENCE MODEL RATE VALUES:
# >> [... 6 more output lines truncated]

# %% [cell 19] code
# DIAGNOSTIC: Performance Recovery Signal (v) Analysis
# =============================================================================
import numpy as np
from scipy import signal as sig
from scipy.fft import fft, fftfreq

fig_diag, axes_diag = plt.subplots(3, 2, figsize=(16, 12))
fig_diag.suptitle('Performance Recovery Signal (v) Diagnostic', fontsize=16, fontweight='bold')

# --- Row 1: v signal time domain ---
# Plot first 500 samples to see transient oscillations clearly
n_samples = min(500, len(t_rec))

axes_diag[0, 0].plot(t_rec[:n_samples], v_rec[:n_samples, 0], 'b-', linewidth=1.5, label='v_pitch')
axes_diag[0, 0].plot(t_rec[:n_samples], v_rec[:n_samples, 1], 'g-', linewidth=1.5, label='v_roll')
axes_diag[0, 0].plot(t_rec[:n_samples], v_rec[:n_samples, 2], 'r-', linewidth=1.5, label='v_yaw')
axes_diag[0, 0].set_xlabel('Time [s]')
axes_diag[0, 0].set_ylabel('v signal')
axes_diag[0, 0].set_title('Performance Recovery Signal v (Transient)')
axes_diag[0, 0].legend()
axes_diag[0, 0].grid(True, alpha=0.3)

# Compare v vs total control u (transient)
axes_diag[0, 1].plot(t_rec[:n_samples], u_rec[:n_samples, 0], 'b-', linewidth=1.5, label='u_total (pitch)')
axes_diag[0, 1].plot(t_rec[:n_samples], v_rec[:n_samples, 0], 'r--', linewidth=1.5, label='v (pitch)')
axes_diag[0, 1].set_xlabel('Time [s]')
axes_diag[0, 1].set_ylabel('Control Signal')
axes_diag[0, 1].set_title('Total Control vs v Signal (Pitch)')
axes_diag[0, 1].legend()
axes_diag[0, 1].grid(True, alpha=0.3)

# --- Row 2: FFT Analysis to find oscillation frequency ---
# Use transient period for FFT (where oscillations are visible)
fft_samples = min(1000, len(t_rec))
v_pitch_transient = v_rec[:fft_samples, 0]

# Remove DC component
v_pitch_centered = v_pitch_transient - np.mean(v_pitch_transient)

# Compute FFT
N = len(v_pitch_centered)
yf = fft(v_pitch_centered)
xf = fftfreq(N, dt)[:N//2]
power = 2.0/N * np.abs(yf[0:N//2])

# Find dominant frequency
dominant_idx = np.argmax(power[1:]) + 1  # Skip DC
dominant_freq = xf[dominant_idx]
dominant_period = 1/dominant_freq if dominant_freq > 0 else np.inf

axes_diag[1, 0].plot(xf, power, 'b-', linewidth=1.5)
axes_diag[1, 0].axvline(x=dominant_freq, color='r', linestyle='--', linewidth=2, 
                        label=f'Dominant: {dominant_freq:.2f} Hz ({dominant_freq*2*np.pi:.2f} rad/s)')
axes_diag[1, 0].set_xlabel('Frequency [Hz]')
axes_diag[1, 0].set_ylabel('Amplitude')
axes_diag[1, 0].set_title('FFT of v_pitch (Frequency Content)')
axes_diag[1, 0].set_xlim([0, 50])  # Focus on relevant range
axes_diag[1, 0].legend()
axes_diag[1, 0].grid(True, alpha=0.3)

# Zoom in on lower frequencies
axes_diag[1, 1].plot(xf, power, 'b-', linewidth=1.5)
axes_diag[1, 1].axvline(x=dominant_freq, color='r', linestyle='--', linewidth=2)
axes_diag[1, 1].axvline(x=wn/(2*np.pi), color='g', linestyle=':', linewidth=2, 
                        label=f'Ref Model BW: {wn/(2*np.pi):.2f} Hz')
axes_diag[1, 1].set_xlabel('Frequency [Hz]')
axes_diag[1, 1].set_ylabel('Amplitude')
axes_diag[1, 1].set_title('FFT Zoomed (with Reference Model Bandwidth)')
axes_diag[1, 1].set_xlim([0, 10])
axes_diag[1, 1].legend()
axes_diag[1, 1].grid(True, alpha=0.3)

# --- Row 3: Filter design recommendation ---
# Compute suggested filter cutoff
suggested_cutoff_hz = max(2 * wn / (2*np.pi), 1.0)  # At least 2x ref model BW
suggested_tau_v = 1 / (2 * np.pi * suggested_cutoff_hz)

# Show what different tau_v values would filter
freqs = np.linspace(0.01, 50, 500)
tau_values = [0.01, 0.02, 0.05, 0.1, 0.2]

for tau in tau_values:
    # First-order filter magnitude response: |H(jω)| = 1/sqrt(1 + (ωτ)²)
    cutoff = 1/(2*np.pi*tau)
    mag = 1 / np.sqrt(1 + (2*np.pi*freqs*tau)**2)
    axes_diag[2, 0].plot(freqs, 20*np.log10(mag), linewidth=1.5, 
                         label=f'τ={tau}s (fc={cutoff:.1f}Hz)')

axes_diag[2, 0].axvline(x=dominant_freq, color='r', linestyle='--', linewidth=2, alpha=0.7,
                        label=f'Oscillation freq: {dominant_freq:.1f} Hz')
axes_diag[2, 0].axvline(x=wn/(2*np.pi), color='g', linestyle=':', linewidth=2, alpha=0.7,
                        label=f'Ref model BW: {wn/(2*np.pi):.2f} Hz')
axes_diag[2, 0].axhline(y=-3, color='k', linestyle=':', alpha=0.5)
axes_diag[2, 0].set_xlabel('Frequency [Hz]')
axes_diag[2, 0].set_ylabel('Magnitude [dB]')
axes_diag[2, 0].set_title('Low-Pass Filter Options for v')
axes_diag[2, 0].set_xlim([0, 30])
axes_diag[2, 0].set_ylim([-40, 5])
axes_diag[2, 0].legend(loc='lower left', fontsize=8)
axes_diag[2, 0].grid(True, alpha=0.3)

# Time-domain comparison: v vs un vs ua
axes_diag[2, 1].plot(t_rec[:n_samples], v_rec[:n_samples, 0], 'r-', linewidth=1.5, label='v (perf recovery)', alpha=0.8)
axes_diag[2, 1].plot(t_rec[:n_samples], un_rec[:n_samples, 0] - v_rec[:n_samples, 0], 'b-', linewidth=1.5, label='un - v (feedback+ff)', alpha=0.8)
axes_diag[2, 1].plot(t_rec[:n_samples], ua_pitch_rec[:n_samples], 'g-', linewidth=1.5, label='ua (adaptive)', alpha=0.8)
axes_diag[2, 1].set_xlabel('Time [s]')
axes_diag[2, 1].set_ylabel('Control Component')
axes_diag[2, 1].set_title('Control Signal Decomposition (Pitch)')
axes_diag[2, 1].legend()
axes_diag[2, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# =============================================================================
# PRINT FREQUENCY ANALYSIS SUMMARY
# =============================================================================
print("=" * 70)
print("FREQUENCY ANALYSIS SUMMARY")
print("=" * 70)
print(f"\n📊 Detected Oscillation Characteristics:")
print(f"   Dominant frequency:     {dominant_freq:.2f} Hz ({dominant_freq*2*np.pi:.2f} rad/s)")
print(f"   Oscillation period:     {dominant_period*1000:.1f} ms")
print(f"\n📊 Reference Model Bandwidth:")
print(f"   ωn = {wn:.2f} rad/s = {wn/(2*np.pi):.2f} Hz")
print(f"\n📊 Current Filter Setting:")
tau_v = 0.05  # Current tau_v used in simulation
print(f"   tau_v = {tau_v:.3f} s → cutoff = {1/(2*np.pi*tau_v):.2f} Hz")

# Recommendation logic
print(f"\n" + "=" * 70)
print("FILTER TUNING RECOMMENDATIONS")
print("=" * 70)

# The filter should:
# 1. Pass frequencies below reference model bandwidth (keep useful signal)
# 2. Attenuate frequencies at/above the oscillation frequency

if dominant_freq > 2 * wn/(2*np.pi):
    # Oscillations are well above ref model BW - can filter aggressively
    recommended_cutoff = 2 * wn/(2*np.pi)  # 2x reference model bandwidth
    recommended_tau = 1 / (2*np.pi*recommended_cutoff)
    print(f"\n✅ GOOD NEWS: Oscillation ({dominant_freq:.1f} Hz) >> Ref model BW ({wn/(2*np.pi):.2f} Hz)")
    print(f"   → Can filter aggressively without losing tracking performance")
    print(f"\n   RECOMMENDED: tau_v = {recommended_tau:.3f} s (cutoff = {recommended_cutoff:.1f} Hz)")
    print(f"   This will attenuate oscillations by {20*np.log10(1/np.sqrt(1+(dominant_freq/recommended_cutoff)**2)):.1f} dB")
else:
    # Oscillations are close to ref model BW - need compromise
    recommended_cutoff = (dominant_freq + wn/(2*np.pi)) / 2
    recommended_tau = 1 / (2*np.pi*recommended_cutoff)
    print(f"\n⚠️  WARNING: Oscillation ({dominant_freq:.1f} Hz) close to Ref model BW ({wn/(2*np.pi):.2f} Hz)")
    print(f"   → Filtering will affect tracking - need compromise")
    print(f"\n   RECOMMENDED: tau_v = {recommended_tau:.3f} s (cutoff = {recommended_cutoff:.1f} Hz)")

print(f"\n📋 Quick Reference - tau_v options:")
print(f"   {'tau_v':<10} {'Cutoff (Hz)':<15} {'Osc. Attenuation':<20} {'Phase lag @ ωn':<15}")
print("-" * 60)
for tau in [0.01, 0.02, 0.05, 0.1, 0.2]:
    fc = 1/(2*np.pi*tau)
    atten = 20*np.log10(1/np.sqrt(1+(dominant_freq*2*np.pi*tau)**2))
    phase_lag = np.arctan(wn*tau) * 180/np.pi
    print(f"   {tau:<10.3f} {fc:<15.1f} {atten:<20.1f} dB {phase_lag:<15.1f}°")

print("\n" + "=" * 70)

# %% [cell 20] markdown
# # Comprehensive Visualization of Adaptive Control Results
#
# This section provides detailed plots for full analysis of the adaptive controller performance.

# %% [cell 21] code
# FIGURE 1: ANGLE TRACKING PERFORMANCE (PITCH, ROLL, YAW)
# =============================================================================
fig1, axes1 = plt.subplots(3, 1, figsize=(12, 10))
fig1.suptitle('Angle Tracking Performance', fontsize=16, fontweight='bold')

# Pitch Angle
axes1[0].plot(t_rec, x_rec[:, 0], 'b-', linewidth=2, label='Actual Pitch')
axes1[0].plot(t_rec, xm_rec[:, 0], 'r--', linewidth=2, label='Reference Pitch')
axes1[0].set_ylabel('Pitch Angle [°]', fontsize=12)
axes1[0].legend(loc='best', fontsize=10)
axes1[0].grid(True, alpha=0.3)
axes1[0].set_title('Pitch Axis Tracking', fontsize=12)

# Roll Angle
axes1[1].plot(t_rec, x_rec[:, 2], 'b-', linewidth=2, label='Actual Roll')
axes1[1].plot(t_rec, xm_rec[:, 2], 'r--', linewidth=2, label='Reference Roll')
axes1[1].set_ylabel('Roll Angle [°]', fontsize=12)
axes1[1].legend(loc='best', fontsize=10)
axes1[1].grid(True, alpha=0.3)
axes1[1].set_title('Roll Axis Tracking', fontsize=12)

# Yaw Angle
axes1[2].plot(t_rec, x_rec[:, 4], 'b-', linewidth=2, label='Actual Yaw')
axes1[2].plot(t_rec, xm_rec[:, 4], 'r--', linewidth=2, label='Reference Yaw')
axes1[2].set_ylabel('Yaw Angle [°]', fontsize=12)
axes1[2].set_xlabel('Time [s]', fontsize=12)
axes1[2].legend(loc='best', fontsize=10)
axes1[2].grid(True, alpha=0.3)
axes1[2].set_title('Yaw Axis Tracking', fontsize=12)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x1000 with 3 Axes>

# %% [cell 22] code
# FIGURE 2: ANGULAR RATE TRACKING (PITCH_DOT, ROLL_DOT, YAW_DOT)
# =============================================================================
fig2, axes2 = plt.subplots(3, 1, figsize=(12, 10))
fig2.suptitle('Angular Rate Tracking Performance', fontsize=16, fontweight='bold')

# Pitch Rate
axes2[0].plot(t_rec, x_rec[:, 1], 'b-', linewidth=2, label='Actual Pitch Rate')
axes2[0].plot(t_rec, xm_rec[:, 1], 'r--', linewidth=2, label='Reference Pitch Rate')
axes2[0].set_ylabel('Pitch Rate [°/s]', fontsize=12)
axes2[0].legend(loc='best', fontsize=10)
axes2[0].grid(True, alpha=0.3)
axes2[0].set_title('Pitch Rate Tracking', fontsize=12)

# Roll Rate
axes2[1].plot(t_rec, x_rec[:, 3], 'b-', linewidth=2, label='Actual Roll Rate')
axes2[1].plot(t_rec, xm_rec[:, 3], 'r--', linewidth=2, label='Reference Roll Rate')
axes2[1].set_ylabel('Roll Rate [°/s]', fontsize=12)
axes2[1].legend(loc='best', fontsize=10)
axes2[1].grid(True, alpha=0.3)
axes2[1].set_title('Roll Rate Tracking', fontsize=12)

# Yaw Rate
axes2[2].plot(t_rec, x_rec[:, 5], 'b-', linewidth=2, label='Actual Yaw Rate')
axes2[2].plot(t_rec, xm_rec[:, 5], 'r--', linewidth=2, label='Reference Yaw Rate')
axes2[2].set_ylabel('Yaw Rate [°/s]', fontsize=12)
axes2[2].set_xlabel('Time [s]', fontsize=12)
axes2[2].legend(loc='best', fontsize=10)
axes2[2].grid(True, alpha=0.3)
axes2[2].set_title('Yaw Rate Tracking', fontsize=12)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x1000 with 3 Axes>

# %% [cell 23] code
# FIGURE 3: TRACKING ERRORS (ANGLE AND RATE ERRORS)
# =============================================================================
fig3, axes3 = plt.subplots(3, 2, figsize=(14, 10))
fig3.suptitle('Tracking Errors', fontsize=16, fontweight='bold')

# Pitch Angle Error
axes3[0, 0].plot(t_rec, e_pitch_rec[:, 0], 'r-', linewidth=2)
axes3[0, 0].set_ylabel('Pitch Angle Error [°]', fontsize=11)
axes3[0, 0].grid(True, alpha=0.3)
axes3[0, 0].set_title('Pitch Angle Error', fontsize=11)
axes3[0, 0].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Pitch Rate Error
axes3[0, 1].plot(t_rec, e_pitch_rec[:, 1], 'r-', linewidth=2)
axes3[0, 1].set_ylabel('Pitch Rate Error [°/s]', fontsize=11)
axes3[0, 1].grid(True, alpha=0.3)
axes3[0, 1].set_title('Pitch Rate Error', fontsize=11)
axes3[0, 1].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Roll Angle Error
axes3[1, 0].plot(t_rec, e_roll_rec[:, 0], 'g-', linewidth=2)
axes3[1, 0].set_ylabel('Roll Angle Error [°]', fontsize=11)
axes3[1, 0].grid(True, alpha=0.3)
axes3[1, 0].set_title('Roll Angle Error', fontsize=11)
axes3[1, 0].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Roll Rate Error
axes3[1, 1].plot(t_rec, e_roll_rec[:, 1], 'g-', linewidth=2)
axes3[1, 1].set_ylabel('Roll Rate Error [°/s]', fontsize=11)
axes3[1, 1].grid(True, alpha=0.3)
axes3[1, 1].set_title('Roll Rate Error', fontsize=11)
axes3[1, 1].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Yaw Angle Error
axes3[2, 0].plot(t_rec, e_yaw_rec[:, 0], 'b-', linewidth=2)
axes3[2, 0].set_ylabel('Yaw Angle Error [°]', fontsize=11)
axes3[2, 0].set_xlabel('Time [s]', fontsize=11)
axes3[2, 0].grid(True, alpha=0.3)
axes3[2, 0].set_title('Yaw Angle Error', fontsize=11)
axes3[2, 0].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Yaw Rate Error
axes3[2, 1].plot(t_rec, e_yaw_rec[:, 1], 'b-', linewidth=2)
axes3[2, 1].set_ylabel('Yaw Rate Error [°/s]', fontsize=11)
axes3[2, 1].set_xlabel('Time [s]', fontsize=11)
axes3[2, 1].grid(True, alpha=0.3)
axes3[2, 1].set_title('Yaw Rate Error', fontsize=11)
axes3[2, 1].axhline(y=0, color='k', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1400x1000 with 6 Axes>

# %% [cell 24] code
# FIGURE 4: CONTROL INPUTS (TORQUE COMMANDS)
# =============================================================================
fig4, axes4 = plt.subplots(3, 1, figsize=(12, 10))
fig4.suptitle('Control Torque Commands', fontsize=16, fontweight='bold')

time_i = 0
time_f = len(t_rec)

# Pitch Torque
axes4[0].plot(t_rec[time_i:time_f], u_rec[time_i:time_f, 0], 'b-', linewidth=2, label='Total Torque')
axes4[0].set_ylabel('Pitch Torque [N·m]', fontsize=12)
axes4[0].legend(loc='best', fontsize=10)
axes4[0].grid(True, alpha=0.3)
axes4[0].set_title('Pitch Control Torque', fontsize=12)

# Roll Torque
axes4[1].plot(t_rec[time_i:time_f], u_rec[time_i:time_f, 1], 'g-', linewidth=2, label='Total Torque')
axes4[1].set_ylabel('Roll Torque [N·m]', fontsize=12)
axes4[1].legend(loc='best', fontsize=10)
axes4[1].grid(True, alpha=0.3)
axes4[1].set_title('Roll Control Torque', fontsize=12)

# Yaw Torque
axes4[2].plot(t_rec[time_i:time_f], u_rec[time_i:time_f, 2], 'r-', linewidth=2, label='Total Torque')
axes4[2].set_ylabel('Yaw Torque [N·m]', fontsize=12)
axes4[2].set_xlabel('Time [s]', fontsize=12)
axes4[2].legend(loc='best', fontsize=10)
axes4[2].grid(True, alpha=0.3)
axes4[2].set_title('Yaw Control Torque', fontsize=12)

plt.tight_layout()
plt.show()
# >> NameError: name 'plt' is not defined

# %% [cell 25] code
# FIGURE 5: ADAPTIVE CONTROL CONTRIBUTION
# =============================================================================
fig5, axes5 = plt.subplots(3, 1, figsize=(12, 10))
fig5.suptitle('Adaptive Control Contribution (Uncertainty Compensation)', fontsize=16, fontweight='bold')

# Adaptive Pitch Control
axes5[0].plot(t_rec, ua_pitch_rec, 'b-', linewidth=2, label='Adaptive Control')
axes5[0].plot(t_rec, unc_pitch_rec, 'r--', linewidth=2, label='True Uncertainty')
axes5[0].plot(t_rec, ua_pitch_rec + unc_pitch_rec, 'k:', linewidth=2, label='uncertainty error compensation (should be ~0)')
axes5[0].set_ylabel('Pitch Torque [N·m]', fontsize=12)
axes5[0].legend(loc='best', fontsize=10)
axes5[0].grid(True, alpha=0.3)
axes5[0].set_title('Pitch Adaptive Control vs True Uncertainty', fontsize=12)

# Adaptive Roll Control
axes5[1].plot(t_rec, ua_roll_rec, 'g-', linewidth=2, label='Adaptive Control')
axes5[1].plot(t_rec, unc_roll_rec, 'r--', linewidth=2, label='True Uncertainty')
axes5[1].plot(t_rec, ua_roll_rec + unc_roll_rec, 'k:', linewidth=2, label='uncertainty error compensation (should be ~0)')
axes5[1].set_ylabel('Roll Torque [N·m]', fontsize=12)
axes5[1].legend(loc='best', fontsize=10)
axes5[1].grid(True, alpha=0.3)
axes5[1].set_title('Roll Adaptive Control vs True Uncertainty', fontsize=12)

# Adaptive Yaw Control
axes5[2].plot(t_rec, ua_yaw_rec, 'm-', linewidth=2, label='Adaptive Control')
axes5[2].plot(t_rec, unc_yaw_rec, 'r--', linewidth=2, label='True Uncertainty')
axes5[2].plot(t_rec, ua_yaw_rec + unc_yaw_rec, 'k:', linewidth=2, label='uncertainty error compensation (should be ~0)')
axes5[2].set_ylabel('Yaw Torque [N·m]', fontsize=12)
axes5[2].set_xlabel('Time [s]', fontsize=12)
axes5[2].legend(loc='best', fontsize=10)
axes5[2].grid(True, alpha=0.3)
axes5[2].set_title('Yaw Adaptive Control vs True Uncertainty', fontsize=12)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x1000 with 3 Axes>

# %% [cell 26] code
# FIGURE 6: ADAPTIVE WEIGHT ESTIMATES (PITCH AXIS)
# =============================================================================
fig6, ax6 = plt.subplots(figsize=(12, 7))
fig6.suptitle('Adaptive Weight Estimates - Pitch Axis', fontsize=16, fontweight='bold')

# Dynamic labels based on regressor configuration
basis_labels = ["Bias", "Angle", "Rate", "Drag", "Sin", "Gyro"]
if Config.INCLUDE_CONTROL_IN_REGRESSOR:
    basis_labels.extend(["un", "v"])

num_weights = What_pitch_rec.shape[1]
for i in range(num_weights):
    label_name = basis_labels[i] if i < len(basis_labels) else f"W{i+1}"
    ax6.plot(t_rec, What_pitch_rec[:, i], linewidth=2, label=f'W{i+1}: {label_name}')

ax6.set_xlabel('Time [s]', fontsize=12)
ax6.set_ylabel('Weight Value', fontsize=12)
ax6.legend(loc='best', fontsize=10, ncol=2)
ax6.grid(True, alpha=0.3)
ax6.set_title(f'Evolution of Adaptive Weights for Pitch Axis ({"Extended" if Config.INCLUDE_CONTROL_IN_REGRESSOR else "Base"})', fontsize=12)
plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x700 with 1 Axes>

# %% [cell 27] code
# FIGURE 7: ADAPTIVE WEIGHT ESTIMATES (ROLL AXIS)
# =============================================================================
fig7, ax7 = plt.subplots(figsize=(12, 7))
fig7.suptitle('Adaptive Weight Estimates - Roll Axis', fontsize=16, fontweight='bold')

# Dynamic labels based on regressor configuration
basis_labels = ["Bias", "Angle", "Rate", "Drag", "Sin", "Gyro"]
if Config.INCLUDE_CONTROL_IN_REGRESSOR:
    basis_labels.extend(["un", "v"])

num_weights = What_roll_rec.shape[1]
for i in range(num_weights):
    label_name = basis_labels[i] if i < len(basis_labels) else f"W{i+1}"
    ax7.plot(t_rec, What_roll_rec[:, i], linewidth=2, label=f'W{i+1}: {label_name}')

ax7.set_xlabel('Time [s]', fontsize=12)
ax7.set_ylabel('Weight Value', fontsize=12)
ax7.legend(loc='best', fontsize=10, ncol=2)
ax7.grid(True, alpha=0.3)
ax7.set_title(f'Evolution of Adaptive Weights for Roll Axis ({"Extended" if Config.INCLUDE_CONTROL_IN_REGRESSOR else "Base"})', fontsize=12)
plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x700 with 1 Axes>

# %% [cell 28] code
# FIGURE 8: ADAPTIVE WEIGHT ESTIMATES (YAW AXIS)
# =============================================================================
fig8, ax8 = plt.subplots(figsize=(12, 7))
fig8.suptitle('Adaptive Weight Estimates - Yaw Axis', fontsize=16, fontweight='bold')

# Dynamic labels based on regressor configuration
basis_labels = ["Bias", "Angle", "Rate", "Drag", "Sin", "Gyro"]
if Config.INCLUDE_CONTROL_IN_REGRESSOR:
    basis_labels.extend(["un", "v"])

num_weights = What_yaw_rec.shape[1]
for i in range(num_weights):
    label_name = basis_labels[i] if i < len(basis_labels) else f"W{i+1}"
    ax8.plot(t_rec, What_yaw_rec[:, i], linewidth=2, label=f'W{i+1}: {label_name}')

ax8.set_xlabel('Time [s]', fontsize=12)
ax8.set_ylabel('Weight Value', fontsize=12)
ax8.legend(loc='best', fontsize=10, ncol=2)
ax8.grid(True, alpha=0.3)
ax8.set_title(f'Evolution of Adaptive Weights for Yaw Axis ({"Extended" if Config.INCLUDE_CONTROL_IN_REGRESSOR else "Base"})', fontsize=12)
plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x700 with 1 Axes>

# %% [cell 29] code
# FIGURE 9: 3D TRAJECTORY VISUALIZATION
# =============================================================================
fig9 = plt.figure(figsize=(14, 10))

# 3D Actual vs Reference Trajectory
ax9a = fig9.add_subplot(221, projection='3d')
ax9a.plot(x_rec[:, 0], x_rec[:, 2], x_rec[:, 4], 'b-', linewidth=2, label='Actual')
ax9a.plot(xm_rec[:, 0], xm_rec[:, 2], xm_rec[:, 4], 'r--', linewidth=2, label='Reference')
ax9a.set_xlabel('Pitch [°]', fontsize=10)
ax9a.set_ylabel('Roll [°]', fontsize=10)
ax9a.set_zlabel('Yaw [°]', fontsize=10)
ax9a.set_title('3D Attitude Trajectory', fontsize=12)
ax9a.legend()
ax9a.grid(True, alpha=0.3)

# Pitch vs Roll
ax9b = fig9.add_subplot(222)
ax9b.plot(x_rec[:, 0], x_rec[:, 2], 'b-', linewidth=2, label='Actual')
ax9b.plot(xm_rec[:, 0], xm_rec[:, 2], 'r--', linewidth=2, label='Reference')
ax9b.set_xlabel('Pitch [°]', fontsize=11)
ax9b.set_ylabel('Roll [°]', fontsize=11)
ax9b.set_title('Pitch vs Roll', fontsize=12)
ax9b.legend()
ax9b.grid(True, alpha=0.3)

# Pitch vs Yaw
ax9c = fig9.add_subplot(223)
ax9c.plot(x_rec[:, 0], x_rec[:, 4], 'b-', linewidth=2, label='Actual')
ax9c.plot(xm_rec[:, 0], xm_rec[:, 4], 'r--', linewidth=2, label='Reference')
ax9c.set_xlabel('Pitch [°]', fontsize=11)
ax9c.set_ylabel('Yaw [°]', fontsize=11)
ax9c.set_title('Pitch vs Yaw', fontsize=12)
ax9c.legend()
ax9c.grid(True, alpha=0.3)

# Roll vs Yaw
ax9d = fig9.add_subplot(224)
ax9d.plot(x_rec[:, 2], x_rec[:, 4], 'b-', linewidth=2, label='Actual')
ax9d.plot(xm_rec[:, 2], xm_rec[:, 4], 'r--', linewidth=2, label='Reference')
ax9d.set_xlabel('Roll [°]', fontsize=11)
ax9d.set_ylabel('Yaw [°]', fontsize=11)
ax9d.set_title('Roll vs Yaw', fontsize=12)
ax9d.legend()
ax9d.grid(True, alpha=0.3)

fig9.suptitle('3D State Space Visualization', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1400x1000 with 4 Axes>

# %% [cell 30] code
# FIGURE 10: ERROR MAGNITUDE OVER TIME
# =============================================================================
fig10, ax10 = plt.subplots(figsize=(12, 6))

# Compute total error magnitude for each axis
pitch_error_mag = np.sqrt(e_pitch_rec[:, 0]**2 + e_pitch_rec[:, 1]**2)
roll_error_mag = np.sqrt(e_roll_rec[:, 0]**2 + e_roll_rec[:, 1]**2)
yaw_error_mag = np.sqrt(e_yaw_rec[:, 0]**2 + e_yaw_rec[:, 1]**2)

ax10.plot(t_rec, pitch_error_mag, 'b-', linewidth=2, label='Pitch Error Magnitude')
ax10.plot(t_rec, roll_error_mag, 'g-', linewidth=2, label='Roll Error Magnitude')
ax10.plot(t_rec, yaw_error_mag, 'r-', linewidth=2, label='Yaw Error Magnitude')
ax10.set_xlabel('Time [s]', fontsize=12)
ax10.set_ylabel('Error Magnitude', fontsize=12)
ax10.set_title('Tracking Error Magnitude Over Time', fontsize=14, fontweight='bold')
ax10.legend(loc='best', fontsize=11)
ax10.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x600 with 1 Axes>

# %% [cell 31] code
# FIGURE 11: WEIGHT CONVERGENCE COMPARISON (ALL AXES)
# =============================================================================
# Determine subplot grid based on number of weights
num_weights = What_pitch_rec.shape[1]
n_rows = (num_weights + 2) // 3  # Ceiling division for 3 columns
n_cols = min(num_weights, 3)

fig11, axes11 = plt.subplots(n_rows, n_cols, figsize=(16, 4*n_rows))
fig11.suptitle(f'Adaptive Weight Convergence - All Axes ({"Extended" if Config.INCLUDE_CONTROL_IN_REGRESSOR else "Base"} Regressor)', 
               fontsize=16, fontweight='bold')

# Dynamic labels
basis_names = ["Bias", "Angle", "Rate", "Drag", "Sin", "Gyro"]
if Config.INCLUDE_CONTROL_IN_REGRESSOR:
    basis_names.extend(["un", "v"])

# Flatten axes for easier indexing
if n_rows > 1:
    axes_flat = axes11.flatten()
else:
    axes_flat = [axes11] if num_weights == 1 else axes11

for i in range(num_weights):
    ax = axes_flat[i]
    label_name = basis_names[i] if i < len(basis_names) else f"W{i+1}"
    ax.plot(t_rec, What_pitch_rec[:, i], 'b-', linewidth=2, label='Pitch')
    ax.plot(t_rec, What_roll_rec[:, i], 'g-', linewidth=2, label='Roll')
    ax.plot(t_rec, What_yaw_rec[:, i], 'r-', linewidth=2, label='Yaw')
    ax.set_xlabel('Time [s]', fontsize=10)
    ax.set_ylabel('Weight Value', fontsize=10)
    ax.set_title(f'Weight {i+1}: {label_name}', fontsize=11)
    ax.legend(loc='best', fontsize=9)
    ax.grid(True, alpha=0.3)

# Hide unused subplots
for i in range(num_weights, len(axes_flat)):
    axes_flat[i].set_visible(False)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1600x1200 with 9 Axes>

# %% [cell 32] code
# FIGURE 12: PERFORMANCE METRICS SUMMARY
# =============================================================================
fig12, axes12 = plt.subplots(2, 2, figsize=(14, 10))
fig12.suptitle('Performance Metrics Summary', fontsize=16, fontweight='bold')

# RMS Error over time (sliding window)
window_size = 500
pitch_rms = np.array([np.sqrt(np.mean(pitch_error_mag[max(0,i-window_size):i+1]**2)) 
                      for i in range(len(pitch_error_mag))])
roll_rms = np.array([np.sqrt(np.mean(roll_error_mag[max(0,i-window_size):i+1]**2)) 
                     for i in range(len(roll_error_mag))])
yaw_rms = np.array([np.sqrt(np.mean(yaw_error_mag[max(0,i-window_size):i+1]**2)) 
                    for i in range(len(yaw_error_mag))])

axes12[0, 0].plot(t_rec, pitch_rms, 'b-', linewidth=2, label='Pitch')
axes12[0, 0].plot(t_rec, roll_rms, 'g-', linewidth=2, label='Roll')
axes12[0, 0].plot(t_rec, yaw_rms, 'r-', linewidth=2, label='Yaw')
axes12[0, 0].set_xlabel('Time [s]', fontsize=11)
axes12[0, 0].set_ylabel('RMS Error', fontsize=11)
axes12[0, 0].set_title('Rolling RMS Error', fontsize=12)
axes12[0, 0].legend(loc='best')
axes12[0, 0].grid(True, alpha=0.3)

# Control effort
pitch_effort = np.cumsum(np.abs(u_rec[:, 0])) * dt
roll_effort = np.cumsum(np.abs(u_rec[:, 1])) * dt
yaw_effort = np.cumsum(np.abs(u_rec[:, 2])) * dt

axes12[0, 1].plot(t_rec, pitch_effort, 'b-', linewidth=2, label='Pitch')
axes12[0, 1].plot(t_rec, roll_effort, 'g-', linewidth=2, label='Roll')
axes12[0, 1].plot(t_rec, yaw_effort, 'r-', linewidth=2, label='Yaw')
axes12[0, 1].set_xlabel('Time [s]', fontsize=11)
axes12[0, 1].set_ylabel('Cumulative Control Effort', fontsize=11)
axes12[0, 1].set_title('Total Control Effort', fontsize=12)
axes12[0, 1].legend(loc='best')
axes12[0, 1].grid(True, alpha=0.3)

# Settling time analysis (time to reach 2% of steady state)
axes12[1, 0].plot(t_rec, np.abs(e_pitch_rec[:, 0]), 'b-', linewidth=2, label='Pitch')
axes12[1, 0].plot(t_rec, np.abs(e_roll_rec[:, 0]), 'g-', linewidth=2, label='Roll')
axes12[1, 0].plot(t_rec, np.abs(e_yaw_rec[:, 0]), 'r-', linewidth=2, label='Yaw')
axes12[1, 0].axhline(y=2, color='k', linestyle='--', alpha=0.5, label='2° threshold')
axes12[1, 0].set_xlabel('Time [s]', fontsize=11)
axes12[1, 0].set_ylabel('Absolute Angle Error [°]', fontsize=11)
axes12[1, 0].set_title('Absolute Angle Error (Settling Analysis)', fontsize=12)
axes12[1, 0].legend(loc='best')
axes12[1, 0].grid(True, alpha=0.3)
axes12[1, 0].set_yscale('log')

# Phase plot (error vs error_dot)
axes12[1, 1].plot(e_pitch_rec[:, 0], e_pitch_rec[:, 1], 'b-', linewidth=1.5, alpha=0.7, label='Pitch')
axes12[1, 1].plot(e_roll_rec[:, 0], e_roll_rec[:, 1], 'g-', linewidth=1.5, alpha=0.7, label='Roll')
axes12[1, 1].plot(e_yaw_rec[:, 0], e_yaw_rec[:, 1], 'r-', linewidth=1.5, alpha=0.7, label='Yaw')
axes12[1, 1].plot(0, 0, 'k*', markersize=15, label='Equilibrium')
axes12[1, 1].set_xlabel('Angle Error [°]', fontsize=11)
axes12[1, 1].set_ylabel('Rate Error [°/s]', fontsize=11)
axes12[1, 1].set_title('Phase Portrait (Error Space)', fontsize=12)
axes12[1, 1].legend(loc='best')
axes12[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1400x1000 with 4 Axes>
# >> :

