# Extract of Roll_Pitch_Yaw_Adaptive_control_simulation_Feedback_Feedforward_Heuristic_auto-tune.ipynb
# Generated by ground_station/research/notebooks/extract.py; do not edit.

# %% [cell 0] markdown
# # Adaptive Control with Performance Recovery for High-Gain Systems
#
# ## Key Lessons Learned (Overflow Prevention)
#
# ### Problem Context
# When implementing **performance recovery** in MRAC for systems with high control effectiveness (Λ = diag(100, 100, 50) for drone attitude), numerical overflow can occur if parameters are not properly tuned.
#
# ---
#
# ### 1. Performance Recovery Gain (`lam`) Selection
#
# The performance recovery filter dynamics are:
# $$\dot{f} = -\lambda (f - e), \quad g = \lambda f + (A_m - \lambda I) e, \quad v = B^{\dagger} g$$
#
# **Critical Rule:** For high-gain systems, use:
# $$\lambda < \frac{\min|Re(\text{eig}(A_m))|}{\Lambda_{\max}}$$
#
# | System | Λ_max | Reference Model Bandwidth | Recommended λ |
# |--------|-------|--------------------------|---------------|
# | Mass-spring-damper | 0.2 | ~1 rad/s | 1.0 |
# | Drone attitude | 100 | ~2 rad/s | **0.1** |
#
# **Why?** The effective loop gain is λ × Λ. With λ=1 and Λ=100, the gain is 100×, causing rapid error amplification before adaptation can compensate.
#
# ---
#
# ### 2. Adaptive Regressor Structure & Control Effectiveness Compensation
#
# **Two configurations available via `INCLUDE_CONTROL_IN_REGRESSOR` flag:**
#
# #### Option A: Base Regressor Only (`INCLUDE_CONTROL_IN_REGRESSOR = False`)
# - Regressor: `θ = [bias, angle, rate, drag, sin, gyro]` (6 elements)
# - Compensates: **Matched uncertainty Δ(x)**
# - ✅ Simpler, no algebraic loop concerns
# - ❌ Cannot adapt to unknown control effectiveness Λ
#
# #### Option B: Extended Regressor (`INCLUDE_CONTROL_IN_REGRESSOR = True`)
# - Regressor: `θ_ext = [basis, un, v]` (8 elements)
# - Compensates: **Both Δ(x) AND unknown Λ**
# - Uses **previous timestep control** to avoid algebraic loop
# - ✅ Can adapt to control effectiveness uncertainty
# - ⚠️ Requires smaller `lam` and careful tuning
#
# **Theory:** If true dynamics are $\ddot{x} = \Lambda(u + \Delta)$, the extended adaptive law:
# $$u_a = -\hat{W}_\Delta^T \theta - \hat{W}_\Lambda^T [u_n; v]$$
# allows adaptation to both uncertainty structure AND control gain mismatch.
#
# ---
#
# ### 3. Bounded Basis Functions
#
# Replace unbounded terms with bounded equivalents:
# - ❌ `angle_rate**2 * sin(angle_rate)` → Can explode
# - ✅ `angle_rate * tanh(angle_rate)` → Naturally bounded
#
# ---
#
# ### 4. σ-Modification (Leakage) Guarantees
#
# The leakage term `-σŴ` in the adaptive law provides:
# 1. **Boundedness** of weights Ŵ without clipping
# 2. **Robustness** to unmodeled dynamics
# 3. **Trade-off**: Non-zero steady-state error (acceptable for robustness)
#
# Typical values: σ ∈ [0.1, 1.0] — higher for more aggressive boundedness.
#
# ---
#
# ### 5. Low-Frequency Learning (NEW - Oscillation Reduction)
#
# **Problem**: Standard σ-modification can cause high-frequency oscillations during transients.
#
# **Solution**: Use filtered weights in the leakage term:
# $$\dot{\hat{W}} = \Gamma(\text{gradient} - \sigma(\hat{W} - \hat{W}_f))$$
# $$\dot{\hat{W}}_f = \gamma_f(\hat{W} - \hat{W}_f)$$
#
# **Benefits**:
# - Reduces high-frequency content in adaptive signal
# - Maintains robustness of σ-modification
# - Theoretically sound (see Lavretsky & Wise, 2013)
# - No clipping or dead-zones
#
# **Parameters**:
# - `gamf` (γ_f): Low-frequency filter gain, typically 0.1-1.0
# - Smaller `gamf` → more filtering → smoother adaptation
#
# ---
#
# ### 6. Normalization (Optional with σ-mod)
#
# When using σ-modification, normalization `(1 + θᵀθ)` is optional but can help:
# - With normalization: Prevents large updates when θ is large
# - Without normalization: Faster adaptation but requires σ-mod for boundedness
#
# ---
#
# ### 7. Parameter Summary for This Drone System
#
# | Parameter | Value | Rationale |
# |-----------|-------|-----------|
# | `lam` | 0.1 | λ << 1.6/100 ≈ 0.016, with margin |
# | `gamma` | 5-10 | Moderate adaptation speed |
# | `sigma` | 0.5 | Strong enough for boundedness |
# | `gamf` | 0.5 | Low-frequency learning gain (if enabled) |
# | `wn` | 2.0 rad/s | Compatible with performance recovery |
# | `zeta` | 0.8 | Good damping, no overshoot |
#
# ---
#
# ### 8. Configuration Flags
#
# | Flag | Description |
# |------|-------------|
# | `PERFORMANCE_RECOVERY_ON` | Enable/disable performance recovery filter |
# | `ADAPTATION_ON` | Enable/disable adaptive control |
# | `INCLUDE_CONTROL_IN_REGRESSOR` | Include un, v in regressor for Λ compensation |
# | `USE_LOW_FREQUENCY_LEARNING` | Enable low-frequency learning (reduces oscillations) |
#
# ---
#
# ### 9. Debugging Checklist
#
# If overflow or high-frequency oscillations occur:
# 1. ☐ **Enable low-frequency learning** (`USE_LOW_FREQUENCY_LEARNING = True`)
# 2. ☐ Reduce `lam` (performance recovery gain)
# 3. ☐ Increase `sigma` (leakage gain)
# 4. ☐ Try `INCLUDE_CONTROL_IN_REGRESSOR = False` first
# 5. ☐ Check basis functions are bounded
# 6. ☐ Verify closed-loop eigenvalues are stable
# 7. ☐ Try disabling performance recovery to isolate issue
# 8. ☐ Increase `tau_gamma` for slower gamma ramp-up

# %% [cell 1] code
# 3dof Pitch,roll,yaw feadback feedforward adaptive controller for a quadcopter drone using leakage modification
import numpy as np
import control as ct
import matplotlib.pyplot as plt

# ============================================
# SYSTEM PARAMETERS (from your drone)
# ============================================

dt = 0.006  # Time step
ft = 100 # Simulation duration

# Approximate moments of inertia 
Jx = 0.01   # Roll moment of inertia [kg·m²]
Jy = 0.01   # Pitch moment of inertia [kg·m²]  
Jz = 0.02   # Yaw moment of inertia [kg·m²]

Lambda_true = np.diag([1/Jx, 1/Jy, 1/Jz])  # True inertia matrix [100, 100, 50]

# ============================================
# REFERENCE MODEL DESIGN
# ============================================
wn = 2.0 # Natural frequency [rad/s]
zeta = 0.8 # Damping ratio

Am_single_axis = np.array([[0, 1],
                    [-wn**2, -2*zeta*wn]])
Bm_single_axis = np.array([[0], 
                    [wn**2]])

Am = np.block([
    [Am_single_axis, np.zeros((2, 4))],
    [np.zeros((2,2)), Am_single_axis, np.zeros((2,2))],
    [np.zeros((2,4)), Am_single_axis]
               ])
Bm = np.block([
    [Bm_single_axis, np.zeros((2,2))],
    [np.zeros((2,1)), Bm_single_axis, np.zeros((2,1))],
    [np.zeros((2,2)), Bm_single_axis]
    ])

# ============================================
# Nominal Controller Design
# ============================================

A_single_axis = np.array([[0, 1],
                          [0, 0]])  
B_single_axis = np.array([[0], 
                          [1]])
C_single_axis = np.array([[1, 0]])

A_full = np.block([
    [A_single_axis, np.zeros((2,4))],
    [np.zeros((2,2)), A_single_axis, np.zeros((2,2))],
    [np.zeros((2,4)), A_single_axis]
])

B_full = np.block([
    [B_single_axis, np.zeros((2,2))],
    [np.zeros((2,1)), B_single_axis, np.zeros((2,1))],
    [np.zeros((2,2)), B_single_axis]
])

B_eff_pitch = B_single_axis / Jx
B_eff_roll = B_single_axis / Jy
B_eff_yaw = B_single_axis / Jz

K1_pitch = (np.linalg.pinv(B_eff_pitch) @ (A_single_axis - Am_single_axis)).flatten()
K2_pitch = (np.linalg.pinv(B_eff_pitch) @ Bm_single_axis).item()

K1_yaw = (np.linalg.pinv(B_eff_yaw) @ (A_single_axis - Am_single_axis)).flatten()
K2_yaw = (np.linalg.pinv(B_eff_yaw) @ Bm_single_axis).item()

K1_roll = (np.linalg.pinv(B_eff_roll) @ (A_single_axis - Am_single_axis)).flatten()
K2_roll = (np.linalg.pinv(B_eff_roll) @ Bm_single_axis).item()

print("Controller Gains (for u = -K1*x + K2*r):")
print(f"  Pitch/Roll: K1={K1_pitch}, K2={K2_pitch}")
print(f"  Yaw: K1={K1_yaw}, K2={K2_yaw}")

K1 = np.vstack([
    np.concatenate([K1_pitch, np.zeros(4)]),
    np.concatenate([np.zeros(2), K1_roll, np.zeros(2)]),
    np.concatenate([np.zeros(4), K1_yaw])
])
K2 = np.diag([K2_pitch, K2_roll, K2_yaw])

# Closed-loop A matrix (this is what the system actually achieves)
A_cl = A_full - B_full @ Lambda_true @ K1
eigs = np.linalg.eigvals(A_cl)
print(f"\n✓ Closed-loop eigenvalues: {eigs}")
print(f"✓ Reference model eigenvalues: {np.linalg.eigvals(Am_single_axis)}")
print(f"✓ All stable: {np.all(np.real(eigs) < 0)}")

# ============================================
# LYAPUNOV MATRIX - computed for the CLOSED-LOOP system
# ============================================
P_single_axis = ct.lyap(Am_single_axis.T, np.eye(2))
# >> Controller Gains (for u = -K1*x + K2*r):
# >>   Pitch/Roll: K1=[0.04  0.032], K2=0.04
# >>   Yaw: K1=[0.08  0.064], K2=0.08
# >>
# >> ✓ Closed-loop eigenvalues: [-1.6+1.2j -1.6-1.2j -1.6+1.2j -1.6-1.2j -1.6+1.2j -1.6-1.2j]
# >> ✓ Reference model eigenvalues: [-1.6+1.2j -1.6-1.2j]
# >> ✓ All stable: True

# %% [cell 2] markdown
# # 📘 Theoretical Guide: Choosing Adaptive Parameters
#
# Selecting adaptive control parameters balances **Tracking Performance** vs. **Robustness** (stability margin).
#
# ## 1. Adaptation Gain ($\gamma$) - "The Learning Rate"
# *   **Role**: Determines how fast the controller estimates unknown dynamics ($\dot{\hat{\theta}} = \gamma \dots$).
# *   **Theory**: Bandwidth of adaptation $\propto \sqrt{\gamma}$.
# *   **Trade-off**:
#     *   **High $\gamma$**: Rapid error convergence. Good for fast maneuvers. **Risk**: Excites high-frequency unmodeled dynamics (vibrations).
#     *   **Low $\gamma$**: Smooth, slow adaptation. Good for noise rejection. **Risk**: Poor tracking during aggressive moves.
# *   **Rule of Thumb**: $\gamma \approx \omega_{ref}^2$ (Match the reference model speed).
#
# ## 2. Performance Recovery Gain ($\lambda$) - "The Filter Bandwidth"
# *   **Role**: In L1/Filtered architectures, this sets the bandwidth of the control signal allowed to cancel uncertainties.
# *   **Theory**: $\lambda$ decouples the estimation loop (fast) from the control loop (bounded).
# *   **Rule**: $\omega_{ref} < \lambda \ll \omega_{unmodeled}$.
# *   **Trade-off**:
#     *   **High $\lambda$**: "Tight" control. Behaves like pure MRAC. **Risk**: Low phase margin.
#     *   **Low $\lambda$**: "Loose" control. High robustness to time-delays. **Risk**: Reduced ability to cancel fast disturbances.
#
# ## 3. Sigma-Modification ($\sigma$) - "The Damping"
# *   **Role**: Prevents parameter drift ("bursting") when tracking error is small or zero.
# *   **Theory**: Adds a decay term: $\dot{\hat{\theta}} = \Gamma( \dots - \sigma \hat{\theta})$.
# *   **Trade-off**:
#     *   **High $\sigma$**: Bounds parameters tightly (Safety). **Cost**: Adds steady-state error (Bias).
#     *   **Low $\sigma$**: Allows perfect cancellation. **Cost**: Parameters may drift to unsafe values if not excited.
#
# ---
#
# ## 🧭 Scenario-Based Selection Table
#
# | Scenario | "Robustness" Level | $\gamma$ (Learn) | $\lambda$ (Filter) | $\sigma$ (Damp) | Why? |
# | :--- | :--- | :--- | :--- | :--- | :--- |
# | **Racing / Aerobatics** | **LOW** | High ($10\omega_n^2$) | High ($>5\omega_n$) | Low (0.01) | Performance is king. We need to react instantly to aggressive turns. We assume the drone is stiff and clean (low noise). |
# | **Cinematography / General** | **MEDIUM** | Medium ($3\omega_n^2$) | Medium ($3\omega_n$) | Medium (0.05) | Smoothness is priority. We don't want "twitchy" micro-corrections visible in video. |
# | **Windy / Heavy Payload** | **HIGH** | Low ($1\omega_n^2$) | Low ($<2\omega_n$) | High (0.1+) | Safety is critical. High winds create noise; we don't want the adaptive controller chasing every gust (over-reacting) or amplifying noise. |

# %% [cell 3] code
# =============================================================================
# AUTOMATIC PARAMETER SELECTION BASED ON SYSTEM KNOWLEDGE
# =============================================================================

def compute_robust_adaptive_parameters(desired_robustness='high'):
    """
    Compute adaptive control parameters using principled heuristics.
    
    This is NOT arbitrary tuning - these formulas come from:
    - Lyapunov stability analysis
    - Robustness-performance trade-offs (Ioannou & Sun)
    - High-gain system stability margins (Lavretsky & Wise)
    
    Parameters:
    -----------
    Lambda_max : float
        Maximum control effectiveness (e.g., 100 for pitch/roll)
    wn : float
        Reference model natural frequency [rad/s]
    zeta : float
        Reference model damping ratio
    dt : float
        Simulation time step [s]
    desired_robustness : str
        'low'    : Fast adaptation, less robust (racing, known conditions)
        'medium' : Balanced (general purpose flight)
        'high'   : Slow adaptation, very robust (windy, uncertain conditions)
    
    Returns:
    --------
    params : dict
        Dictionary of recommended parameters
    """
    
    
    if desired_robustness == 'low':
        lam = 0.15
        gamma = 5
        sigma = 0.5
        gamf = 2
        tau_gamma = 10.0
        tau_v = 0.1
    elif desired_robustness == 'medium' :
        lam = 120
        gamma = 200
        sigma = 0.1
        gamf = 1
        tau_gamma = 35
        tau_v = 1.0
    elif desired_robustness == 'high':
        lam = 150
        gamma = 250
        sigma = 0.5
        gamf = 5
        tau_gamma = 40
        tau_v = 2
    

    params = {
        'lam': lam,
        'gamma': gamma,
        'sigma': sigma,
        'gamf': gamf,
        'tau_gamma': tau_gamma,
        'tau_v': tau_v,
        'USE_LOW_FREQUENCY_LEARNING': True,  # Always recommended
        'USE_GAMMA_SCHEDULING': True,         # Always recommended
        'USE_FILTERED_PERFORMANCE_RECOVERY': True,  # Always recommended
    }
    
    return params

# %% [cell 4] code
#  SWITCHES FOR DEBUGGING & CONFIGURATION
# ============================================
PERFORMANCE_RECOVERY_ON = True   # Set False to test without Performance Recovery
ADAPTATION_ON = True
INCLUDE_CONTROL_IN_REGRESSOR = True  # NEW FLAG: Include un, v in regressor for Λ compensation
Time_varying_unc = True
USE_NORMILIZATION = False

# NEW: Second-order filter for performance recovery (RECOMMENDED)
USE_SECOND_ORDER_PR_FILTER = False  # Enable second-order critically damped filter
zeta_pr = 1.5  # Damping ratio for PR filter: 1.0 = critical (no overshoot), 0.7 = slight overshoot

# =============================================================================
# AUTOMATIC TUNING EXECUTION
# =============================================================================

# Choose robustness level based on flight scenario
# 'low'    = Racing, clean conditions, fast response needed
# 'medium' = General purpose, moderate uncertainty
# 'high'   = Windy, high uncertainty, safety-critical

ROBUSTNESS_LEVEL = 'low'  # ← CHANGE THIS BASED ON CONDITIONS

# Compute parameters automatically
adaptive_params = compute_robust_adaptive_parameters(
    desired_robustness=ROBUSTNESS_LEVEL
)

# Apply parameters
lam = adaptive_params['lam']
gamma_final = adaptive_params['gamma']
sigma = adaptive_params['sigma']
gamf = adaptive_params['gamf']
tau_gamma = adaptive_params['tau_gamma']
tau_v = adaptive_params['tau_v']
USE_LOW_FREQUENCY_LEARNING = adaptive_params['USE_LOW_FREQUENCY_LEARNING']
USE_GAMMA_SCHEDULING = adaptive_params['USE_GAMMA_SCHEDULING']
USE_FILTERED_PERFORMANCE_RECOVERY = adaptive_params['USE_FILTERED_PERFORMANCE_RECOVERY']

# Print what was selected
print("="*80)
print(f"AUTO-TUNED PARAMETERS (Robustness: {ROBUSTNESS_LEVEL.upper()})")
print("="*80)
for key, val in adaptive_params.items():
    if isinstance(val, bool):
        print(f"  {key:<35} = {val}")
    else:
        print(f"  {key:<35} = {val:.6f}")
print("="*80)
print("\n✅ Parameters computed from system knowledge - NO manual tuning needed!")
print("   Theory: Lavretsky & Wise (2013), Ioannou & Sun (1996)")
print("="*80)

# Initialize variables based on these parameters
f = np.zeros((6,1))
v = np.zeros((3,1))
v_filtered = np.zeros((3,1))  # NEW: Filtered performance recovery signal
f_dot = np.zeros((6, 1))  # Velocity state for second-order f dynamics

# ============================================
# ADAPTIVE PARAMETERS SETUP 
# ============================================
# Base basis functions: [bias, angle, rate, drag, sin, gyro] = 6
# Extended regressor: + [un, v] = 8 total (when INCLUDE_CONTROL_IN_REGRESSOR=True)
num_basis_base = 6
num_basis = num_basis_base + 2 if INCLUDE_CONTROL_IN_REGRESSOR else num_basis_base

# Initial adaptive weights (zero)
What_pitch = np.zeros((num_basis, 1))
What_roll = np.zeros((num_basis, 1))
What_yaw = np.zeros((num_basis, 1))

# Low-frequency weight filters (for low-frequency learning)
Whatf_pitch = np.zeros((num_basis, 1))
Whatf_roll = np.zeros((num_basis, 1))
Whatf_yaw = np.zeros((num_basis, 1))
# >> ================================================================================
# >> AUTO-TUNED PARAMETERS (Robustness: LOW)
# >> ================================================================================
# >>   lam                                 = 0.150000
# >>   gamma                               = 5.000000
# >>   sigma                               = 0.500000
# >>   gamf                                = 2.000000
# >>   tau_gamma                           = 10.000000
# >>   tau_v                               = 0.100000
# >>   USE_LOW_FREQUENCY_LEARNING          = True
# >>   USE_GAMMA_SCHEDULING                = True
# >>   USE_FILTERED_PERFORMANCE_RECOVERY   = True
# >> ================================================================================
# >>
# >> ✅ Parameters computed from system knowledge - NO manual tuning needed!
# >>    Theory: Lavretsky & Wise (2013), Ioannou & Sun (1996)
# >> ================================================================================

# %% [cell 5] code
#  HELPER FUNCTIONS
# ============================================

def get_scheduled_gamma(t, gamma_final, tau):
    """
    Exponential gamma scheduling - theoretically sound approach.
    
    This is NOT clipping. Time-varying gains are well-established in 
    adaptive control theory (see Ioannou & Sun, Ch. 8).
    
    As t → ∞, gamma → gamma_final (recovers original adaptive law)
    """
    return gamma_final * (1.0 - np.exp(-t / tau))

def compute_basis(bias, angle, angle_rate, gyroscopic_coupling):
    """Base basis functions (uncertainty structure)"""
    theta = np.array([
        [bias],
        [angle],
        [angle_rate],
        [angle_rate * np.tanh(angle_rate)],
        [np.sin(angle)],
        [gyroscopic_coupling]
        ]) 
    return theta

def compute_extended_regressor(theta_base, un_axis, v_axis):
    """
    Extended regressor including control terms for Λ compensation.
    
    Theory: If true dynamics are ẍ = Λ(u + Δ), the adaptive control can be:
        ua = -Ŵ_Δᵀθ - Ŵ_Λᵀ[un; v]
    
    This allows adaptation to BOTH:
    1. Matched uncertainty Δ (via θ)
    2. Control effectiveness error (Λ - Λ_nom) (via un, v terms)
    """
    return np.vstack([theta_base, [[un_axis]], [[v_axis]]])


def compute_time_varying_uncertainty(t, x, level='easy'):
    """
    Compute time-varying uncertainty weights for drone adaptive control.
    """
    # Extract states (convert from degrees to radians if needed)
    pitch, pitch_dot = x[0, 0], x[1, 0]
    roll, roll_dot = x[2, 0], x[3, 0]
    yaw, yaw_dot = x[4, 0], x[5, 0]
    
    # ========================================================================
    # LEVEL 1: SLOWLY-VARYING AERODYNAMIC DRAG (EASY)
    # ========================================================================
    if level.lower() in ['easy', '1', 'level1']:
        # Slow sinusoidal variation - much slower than reference model
        drag_factor = 0.1 + 0.05 * np.sin(0.2 * t)
        
        W_true_pitch = np.array([
            [0.1],                      # Constant bias
            [0.05],                     # Angle coupling
            [0.02 * drag_factor],       # Rate damping (slowly varying)
            [0.15 * drag_factor],       # Quadratic drag (slowly varying)
            [0.03],                     # Nonlinear sin term
            [0.08]                      # Gyroscopic coupling
        ])
        
        W_true_roll = np.array([
            [0.1],
            [0.05],
            [0.02 * drag_factor],
            [0.15 * drag_factor],
            [0.03],
            [0.07]
        ])
        
        W_true_yaw = np.array([
            [0.05],
            [0.08],
            [0.01 * drag_factor],
            [0.0],
            [0.02],
            [0.06]
        ])
    
    # ========================================================================
    # LEVEL 2: PAYLOAD MASS SHIFT (MEDIUM)
    # ========================================================================
    elif level.lower() in ['medium', '2', 'level2']:
        # Piecewise time-varying scenario with ramps
        if t < 30:
            mass_shift = 0.0
        elif t < 35:
            mass_shift = (t - 30) / 5.0  # Ramp up over 5s
        elif t < 60:
            mass_shift = 1.0              # Sustained shift
        elif t < 65:
            mass_shift = 1.0 - (t - 60) / 5.0  # Ramp down
        else:
            mass_shift = 0.0
        
        # Varying inertial coupling (affects gyroscopic terms)
        coupling_gain = 0.08 + 0.12 * mass_shift  # 0.08 → 0.20
        
        # Varying bias (center-of-mass offset)
        bias_offset = 0.15 * mass_shift  # 0 → 0.15
        
        W_true_pitch = np.array([
            [0.1 + bias_offset],          # Bias varies with CoM
            [0.05],
            [0.02],
            [0.15],
            [0.03 + 0.02 * mass_shift],   # Nonlinearity increases
            [coupling_gain]               # Gyro coupling changes significantly
        ])
        
        W_true_roll = np.array([
            [0.1 + bias_offset],
            [0.05],
            [0.02],
            [0.15],
            [0.03 + 0.02 * mass_shift],
            [coupling_gain]
        ])
        
        W_true_yaw = np.array([
            [0.05],
            [0.08 + 0.05 * mass_shift],   # Yaw inertia changes
            [0.01],
            [0.0],
            [0.02],
            [coupling_gain]
        ])
    
    # ========================================================================
    # LEVEL 3: AGGRESSIVE MANEUVERING (HARD)
    # ========================================================================
    elif level.lower() in ['hard', '3', 'level3']:
        # 1. High-frequency vibration (rotor imbalance)
        vibe = 0.02 * np.sin(15 * t)  # 15 rad/s (~2.4 Hz)
        
        # 2. State-dependent aerodynamics (vortex ring at high rates)
        pitch_rate_abs = np.abs(pitch_dot)
        roll_rate_abs = np.abs(roll_dot)
        
        # Sudden drag increase near stall (20 deg/s threshold)
        stall_effect_pitch = 0.3 if pitch_rate_abs > 20.0 * np.pi/180 else 0.0
        stall_effect_roll = 0.3 if roll_rate_abs > 20.0 * np.pi/180 else 0.0
        
        # 3. Time-varying + state-dependent coupling
        maneuver_phase = np.sin(0.5 * t)  # Slow maneuver profile
        dynamic_coupling = 0.08 + 0.15 * np.abs(maneuver_phase) * np.tanh(pitch_rate_abs)
        
        W_true_pitch = np.array([
            [0.1 + vibe],                                  # Vibration in bias
            [0.05 + 0.03 * np.sin(0.3 * t)],              # Slow angle dependence
            [0.02 + stall_effect_pitch],                   # Sudden nonlinearity
            [0.15 * (1 + 0.5 * np.abs(maneuver_phase))],  # Varying drag
            [0.03 + 0.04 * np.abs(np.sin(pitch))],        # State-dependent sine
            [dynamic_coupling]                             # Fast + slow coupling
        ])
        
        W_true_roll = np.array([
            [0.1 + vibe * 0.8],                            # Slightly different vibe
            [0.05 + 0.03 * np.sin(0.3 * t + 1.0)],        # Phase-shifted
            [0.02 + stall_effect_roll],
            [0.15 * (1 + 0.5 * np.abs(maneuver_phase))],
            [0.03 + 0.04 * np.abs(np.sin(roll))],
            [dynamic_coupling]
        ])
        
        W_true_yaw = np.array([
            [0.05],
            [0.08 + 0.06 * np.abs(maneuver_phase)],       # Yaw authority varies
            [0.01],
            [0.0],
            [0.02],
            [dynamic_coupling * 0.7]                       # Reduced yaw coupling
        ])
    
    else:
        raise ValueError(f"Invalid level '{level}'. Use 'easy', 'medium', or 'hard'")
    
    return W_true_pitch, W_true_roll, W_true_yaw

def compute_reference_trajectory(t, level='easy'):
    """
    Generate realistic time-varying reference trajectories for drone attitude control.
    """
    
    deg2rad = np.pi / 180.0
    
    # ========================================================================
    # LEVEL 1: SLOW STABILIZATION AND GENTLE TRANSITIONS (EASY)
    # ========================================================================
    if level in ['easy', '1', 'level1', 1]:
        # Smooth step sequence with long dwell times
        if t < 20:
            # Initial hover (level attitude)
            pitch = 0.0
            roll = 0.0
            yaw = 0.0
        elif t < 40:
            # Forward tilt (slow acceleration)
            pitch = 8.0 * deg2rad
            roll = 0.0
            yaw = 0.0
        elif t < 60:
            # Left tilt with slight yaw
            pitch = 0.0
            roll = -8.0 * deg2rad
            yaw = 10.0 * deg2rad
        elif t < 80:
            # Return to level
            pitch = 0.0
            roll = 0.0
            yaw = 0.0
        else:
            # Backward tilt
            pitch = -8.0 * deg2rad
            roll = 0.0
            yaw = 0.0
    
    # ========================================================================
    # LEVEL 2: DYNAMIC MANEUVERING - RECTANGULAR PATTERN (MEDIUM)
    # ========================================================================
    elif level in ['medium', '2', 'level2', 2]:
        # Simulates rectangular flight pattern with coordinated turns
        phase = t % 40  # 40-second cycle
        
        if phase < 8:
            # Leg 1: Forward flight (pitch forward, level roll)
            pitch = 12.0 * deg2rad
            roll = 0.0
            yaw = 0.0 * deg2rad
        elif phase < 10:
            # Turn 1: Right turn (reduce pitch, roll right, yaw right)
            transition = (phase - 8) / 2.0  # 0 → 1 over 2 seconds
            pitch = 12.0 * (1 - transition) * deg2rad
            roll = 15.0 * transition * deg2rad
            yaw = 45.0 * transition * deg2rad
        elif phase < 18:
            # Leg 2: Right strafe
            pitch = 0.0
            roll = 12.0 * deg2rad
            yaw = 90.0 * deg2rad
        elif phase < 20:
            # Turn 2: Transition to backward
            transition = (phase - 18) / 2.0
            pitch = -12.0 * transition * deg2rad
            roll = 12.0 * (1 - transition) * deg2rad
            yaw = 90.0 + 45.0 * transition * deg2rad
        elif phase < 28:
            # Leg 3: Backward flight
            pitch = -12.0 * deg2rad
            roll = 0.0
            yaw = 180.0 * deg2rad
        elif phase < 30:
            # Turn 3: Left turn
            transition = (phase - 28) / 2.0
            pitch = -12.0 * (1 - transition) * deg2rad
            roll = -15.0 * transition * deg2rad
            yaw = 180.0 + 45.0 * transition * deg2rad
        elif phase < 38:
            # Leg 4: Left strafe
            pitch = 0.0
            roll = -12.0 * deg2rad
            yaw = 270.0 * deg2rad
        else:
            # Turn 4: Return to start
            transition = (phase - 38) / 2.0
            pitch = 12.0 * transition * deg2rad
            roll = -12.0 * (1 - transition) * deg2rad
            yaw = 270.0 + 45.0 * transition * deg2rad
    
    # ========================================================================
    # LEVEL 3: AGGRESSIVE AEROBATIC FLIGHT (HARD)
    # ========================================================================
    elif level in ['hard', '3', 'level3', 3]:
        # Multi-frequency sinusoidal excitation
        # Simulates aggressive FPV racing or aerobatic maneuvers
        
        # Pitch: Fast oscillation (0.3 Hz) + slow trend (0.05 Hz)
        pitch = (15.0 * np.sin(0.3 * 2*np.pi * t) + 
                 8.0 * np.sin(0.05 * 2*np.pi * t)) * deg2rad
        
        # Roll: Different frequency (0.25 Hz) + amplitude modulation
        amplitude_mod = 1.0 + 0.3 * np.sin(0.08 * 2*np.pi * t)
        roll = 18.0 * amplitude_mod * np.sin(0.25 * 2*np.pi * t) * deg2rad
        
        # Yaw: Continuous spinning with varying rate
        yaw_rate = 30.0 + 20.0 * np.sin(0.1 * 2*np.pi * t)  # deg/s
        yaw = (yaw_rate * t) * deg2rad
        
        # Add sudden "flip" maneuvers every 15 seconds
        if int(t) % 15 == 0 and (t % 1.0) < 0.5:  # 0.5s flip window
            pitch = pitch + 30.0 * deg2rad * np.sin(10 * t)
    
    # ========================================================================
    # LEVEL 4: CHAOTIC/UNPREDICTABLE DISTURBANCE REJECTION (EXTREME)
    # ========================================================================
    elif level in ['extreme', '4', 'level4', 4]:
        # Combination of random walk, multi-frequency, and sudden disturbances
        # Simulates extreme turbulence or adversarial conditions
        
        # Pseudo-random component (deterministic but looks random)
        np.random.seed(int(t * 100) % 10000)  # Changes every 0.01s
        random_pitch = np.random.uniform(-5, 5) * deg2rad
        random_roll = np.random.uniform(-5, 5) * deg2rad
        random_yaw = np.random.uniform(-10, 10) * deg2rad
        
        # Multi-frequency sinusoidal base
        pitch_base = (12.0 * np.sin(0.4 * 2*np.pi * t) + 
                      6.0 * np.sin(0.7 * 2*np.pi * t) +
                      3.0 * np.sin(1.2 * 2*np.pi * t)) * deg2rad
        
        roll_base = (15.0 * np.sin(0.35 * 2*np.pi * t) + 
                     7.0 * np.sin(0.9 * 2*np.pi * t) +
                     4.0 * np.cos(1.5 * 2*np.pi * t)) * deg2rad
        
        yaw_base = (25.0 * np.sin(0.2 * 2*np.pi * t) +
                    15.0 * np.sin(0.5 * 2*np.pi * t)) * deg2rad
        
        # Sudden step disturbances every 10 seconds
        disturbance_pitch = 0.0
        disturbance_roll = 0.0
        if int(t) % 10 == 0 and (t % 1.0) < 1.0:
            disturbance_pitch = 20.0 * deg2rad * (1 - (t % 1.0))
            disturbance_roll = -15.0 * deg2rad * (1 - (t % 1.0))
        
        # Combine all components
        pitch = pitch_base + random_pitch + disturbance_pitch
        roll = roll_base + random_roll + disturbance_roll
        yaw = yaw_base + random_yaw
        
        # Saturation (physical limits)
        pitch = np.clip(pitch, -35 * deg2rad, 35 * deg2rad)
        roll = np.clip(roll, -35 * deg2rad, 35 * deg2rad)
        yaw = np.clip(yaw, -180 * deg2rad, 180 * deg2rad)
    
    else:
        raise ValueError(f"Invalid level '{level}'. Use 'easy', 'medium', 'hard', or 'extreme'")
    
    # Return as column vector
    return np.array([[pitch], [roll], [yaw]])

# %% [cell 6] code
# SIMULATION INITIALIZATION
# ============================================
x = np.zeros((6,1))
xm = np.zeros((6,1))
xr = np.zeros((6,1))

# True uncertainty weights (only for base basis - not control terms)
if not Time_varying_unc: 
    W_true_pitch = np.array([[0.1], [0.05], [0.02], [0.15], [0.03], [0.08]])
    W_true_roll = np.array([[0.1], [0.05], [0.02], [0.15], [0.03], [0.07]])
    W_true_yaw = np.array([[0.05], [0.08], [0.01], [0.0], [0.02], [0.06]])

x_rec, xm_rec, xr_rec, u_rec, t_rec = [], [], [], [], []
What_pitch_rec, What_roll_rec, What_yaw_rec = [], [], []
Whatf_pitch_rec, Whatf_roll_rec, Whatf_yaw_rec = [], [], []
theta_pitch_rec, theta_roll_rec, theta_yaw_rec = [], [], []
e_pitch_rec, e_roll_rec, e_yaw_rec = [], [], []
ua_pitch_rec, ua_roll_rec, ua_yaw_rec = [], [], []
unc_pitch_rec, unc_roll_rec, unc_yaw_rec = [], [], []
v_rec = []
un_rec = []

r_filtered = np.zeros((3, 1))

# Previous step control for regressor (to avoid algebraic loop)
un_prev = np.zeros(3)
v_prev = np.zeros((3, 1))

# ============================================
# MAIN SIMULATION LOOP
# ============================================

for t in np.arange(0, ft, dt):

    r = compute_reference_trajectory(t, level='medium')

    r_filtered = r_filtered + dt * 4.0 * (r - r_filtered)

    if Time_varying_unc :
            W_true_pitch, W_true_roll, W_true_yaw = compute_time_varying_uncertainty(
            t, x, level='easy')

    # ----- EXTRACT STATES -----
    pitch, pitch_dot = x[0, 0], x[1, 0]
    roll, roll_dot = x[2, 0], x[3, 0]
    yaw, yaw_dot = x[4, 0], x[5, 0]

    # ----- COMPUTE BASIS FUNCTIONS -----
    theta_pitch_base = compute_basis(1.0, pitch, pitch_dot, roll_dot * yaw_dot)
    theta_roll_base = compute_basis(1.0, roll, roll_dot, pitch_dot * yaw_dot)
    theta_yaw_base = compute_basis(1.0, yaw, yaw_dot, pitch_dot * roll_dot)

    # ----- PERFORMANCE RECOVERY -----
    if PERFORMANCE_RECOVERY_ON:
        e_state = x - xm
        
        if USE_SECOND_ORDER_PR_FILTER:
            # =====================================================
            # SECOND-ORDER CRITICALLY DAMPED FILTER (RECOMMENDED)
            # =====================================================
            # Dynamics: f̈ + 2ζλḟ + λ²f = λ²e
            # 
            # This provides:
            # - Controllable damping (ζ) independent of speed (λ)
            # - No overshoot when ζ ≥ 1.0
            # - Faster settling than first-order with same λ
            # =====================================================
            
            f_ddot = lam**2 * (e_state - f) - 2 * zeta_pr * lam * f_dot
            f_dot = f_dot + dt * f_ddot
            f = f + dt * f_dot
            
            # Compute v from filtered f
            g = lam * f + (Am - lam * np.eye(6)) @ e_state
            v = np.linalg.pinv(B_full) @ g
            
        else:
            # Original first-order filter
            f = f + dt * (-lam * (f - e_state))
            g = lam * f + (Am - lam * np.eye(6)) @ e_state
            v_raw = np.linalg.pinv(B_full) @ g
            
            if USE_FILTERED_PERFORMANCE_RECOVERY:
                # Optional additional low-pass filter on v
                v_filtered = v_filtered + dt * (v_raw - v_filtered) / tau_v
                v = v_filtered
            else:
                v = v_raw
    else:
        v = np.zeros((3, 1))

    # ----- BUILD REGRESSORS (use previous control to avoid algebraic loop) -----
    if INCLUDE_CONTROL_IN_REGRESSOR:
        # Extended regressor with control terms
        theta_pitch = compute_extended_regressor(theta_pitch_base, un_prev[0], v_prev[0, 0])
        theta_roll = compute_extended_regressor(theta_roll_base, un_prev[1], v_prev[1, 0])
        theta_yaw = compute_extended_regressor(theta_yaw_base, un_prev[2], v_prev[2, 0])
    else:
        # Base regressor only
        theta_pitch = theta_pitch_base
        theta_roll = theta_roll_base
        theta_yaw = theta_yaw_base

    # ----- ADAPTIVE CONTROL -----
    if ADAPTATION_ON:
        ua_pitch = -What_pitch.T @ theta_pitch
        ua_roll = -What_roll.T @ theta_roll
        ua_yaw = -What_yaw.T @ theta_yaw
        ua = np.array([ua_pitch.item(), ua_roll.item(), ua_yaw.item()])
    else:
        ua = np.zeros(3)
        ua_pitch = np.array([[0.0]])
        ua_roll = np.array([[0.0]])
        ua_yaw = np.array([[0.0]])

    # ----- NOMINAL CONTROL -----
    un_feedback = (-K1 @ x).flatten()
    un_feedforward = (K2 @ r_filtered).flatten()
    un = un_feedback + un_feedforward + v.flatten()

    # ----- TOTAL CONTROL -----
    u = un + ua

    # ----- STORE CURRENT CONTROL FOR NEXT STEP REGRESSOR -----
    un_prev = un.copy()
    v_prev = v.copy()

    # ----- REFERENCE MODEL UPDATE -----
    if PERFORMANCE_RECOVERY_ON:
        xm = xm + dt * (Am @ xm + Bm @ r_filtered + B_full @ v)
    else:
        xm = xm + dt * (Am @ xm + Bm @ r_filtered)
    xr = xr + dt * (Am @ xr + Bm @ r_filtered)

    # ----- TRACKING ERRORS -----
    e_pitch = np.array([[x[0,0] - xm[0,0]], [x[1,0] - xm[1,0]]])
    e_roll = np.array([[x[2,0] - xm[2,0]], [x[3,0] - xm[3,0]]])
    e_yaw = np.array([[x[4,0] - xm[4,0]], [x[5,0] - xm[5,0]]])

    # ----- ADAPTIVE LAW -----
    if ADAPTATION_ON:
        if USE_NORMILIZATION :
            norm_pitch = 1.0 + (theta_pitch.T @ theta_pitch).item()
            norm_roll = 1.0 + (theta_roll.T @ theta_roll).item()
            norm_yaw = 1.0 + (theta_yaw.T @ theta_yaw).item()
        else :
            norm_pitch = 1.0
            norm_roll = 1.0
            norm_yaw = 1.0
        
        grad_pitch = theta_pitch @ (e_pitch.T @ P_single_axis @ B_single_axis)
        grad_roll = theta_roll @ (e_roll.T @ P_single_axis @ B_single_axis)
        grad_yaw = theta_yaw @ (e_yaw.T @ P_single_axis @ B_single_axis)

        
        if USE_GAMMA_SCHEDULING:
            gamma = get_scheduled_gamma(t, gamma_final, tau_gamma)
        else:
            gamma = gamma_final

        if USE_LOW_FREQUENCY_LEARNING:
            # Low-frequency learning: σ-mod with filtered weights
            # ẆHat = γ(grad - σ(Ŵ - Ŵf)) / norm
            # Ẇf = γf(Ŵ - Ŵf)
            What_pitch = What_pitch + dt * gamma * (grad_pitch - sigma * (What_pitch - Whatf_pitch)) #/ norm_pitch
            What_roll = What_roll + dt * gamma * (grad_roll - sigma * (What_roll - Whatf_roll)) #/ norm_roll
            What_yaw = What_yaw + dt * gamma * (grad_yaw - sigma * (What_yaw - Whatf_yaw)) #/ norm_yaw
            
            # Update low-frequency weight filters
            Whatf_pitch = Whatf_pitch + dt * gamf * (What_pitch - Whatf_pitch)
            Whatf_roll = Whatf_roll + dt * gamf * (What_roll - Whatf_roll)
            Whatf_yaw = Whatf_yaw + dt * gamf * (What_yaw - Whatf_yaw)
        else:
            # Standard σ-modification (leakage to zero)
            What_pitch = What_pitch + dt * gamma * (grad_pitch - sigma * What_pitch) / norm_pitch
            What_roll = What_roll + dt * gamma * (grad_roll - sigma * What_roll) / norm_roll
            What_yaw = What_yaw + dt * gamma * (grad_yaw - sigma * What_yaw) / norm_yaw

    # ----- SYSTEM DYNAMICS -----
    # True uncertainty uses ONLY base basis (the uncertainty doesn't depend on control)
    unc_pitch = (W_true_pitch.T @ theta_pitch_base).item()
    unc_roll = (W_true_roll.T @ theta_roll_base).item()
    unc_yaw = (W_true_yaw.T @ theta_yaw_base).item()
    
    unc_vec = np.array([[unc_pitch], [unc_roll], [unc_yaw]])
    
    x = x + dt * (A_full @ x + B_full @ Lambda_true @ (u.reshape(-1,1) + unc_vec))

    # ----- RECORD DATA -----
    x_rec.append(x.flatten() * 180/np.pi)
    xm_rec.append(xm.flatten() * 180/np.pi)
    xr_rec.append(xr.flatten() * 180/np.pi)
    e_pitch_rec.append(e_pitch.flatten() * 180/np.pi)
    e_roll_rec.append(e_roll.flatten() * 180/np.pi)
    e_yaw_rec.append(e_yaw.flatten() * 180/np.pi)
    u_rec.append(u.flatten())
    t_rec.append(t)
    What_pitch_rec.append(What_pitch.flatten())
    What_roll_rec.append(What_roll.flatten())
    What_yaw_rec.append(What_yaw.flatten())
    theta_pitch_rec.append(theta_pitch.flatten())
    theta_roll_rec.append(theta_roll.flatten())
    theta_yaw_rec.append(theta_yaw.flatten())
    ua_pitch_rec.append(ua_pitch.item() if hasattr(ua_pitch, 'item') else ua_pitch)
    ua_roll_rec.append(ua_roll.item() if hasattr(ua_roll, 'item') else ua_roll)
    ua_yaw_rec.append(ua_yaw.item() if hasattr(ua_yaw, 'item') else ua_yaw)
    unc_pitch_rec.append(unc_pitch)
    unc_roll_rec.append(unc_roll)
    unc_yaw_rec.append(unc_yaw)
    v_rec.append(v.flatten())
    un_rec.append(un.flatten())

    if USE_LOW_FREQUENCY_LEARNING:
        Whatf_pitch_rec.append(Whatf_pitch.flatten())
        Whatf_roll_rec.append(Whatf_roll.flatten())
        Whatf_yaw_rec.append(Whatf_yaw.flatten())

print("✅ Simulation completed!")
print(f"Final time: {t:.2f}s")
print(f"Performance Recovery: {'ON' if PERFORMANCE_RECOVERY_ON else 'OFF'}")
print(f"Adaptation: {'ON' if ADAPTATION_ON else 'OFF'}")
print(f"Low-Frequency Learning: {'ON (γf=' + str(gamf) + ')' if USE_LOW_FREQUENCY_LEARNING else 'OFF (standard σ-mod)'}")
print(f"Control in Regressor: {'ON (Λ compensation enabled)' if INCLUDE_CONTROL_IN_REGRESSOR else 'OFF (base uncertainty only)'}")
print(f"Regressor size: {num_basis} elements")
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_2396\1354193109.py:143: RuntimeWarning: overflow encountered in matmul
# >>   norm_pitch = 1.0 + (theta_pitch.T @ theta_pitch).item()
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_2396\1354193109.py:144: RuntimeWarning: overflow encountered in matmul
# >>   norm_roll = 1.0 + (theta_roll.T @ theta_roll).item()
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_2396\1354193109.py:145: RuntimeWarning: overflow encountered in matmul
# >>   norm_yaw = 1.0 + (theta_yaw.T @ theta_yaw).item()
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_2396\1354193109.py:147: RuntimeWarning: overflow encountered in matmul
# >>   grad_pitch = theta_pitch @ (e_pitch.T @ P_single_axis @ B_single_axis)
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_2396\1354193109.py:148: RuntimeWarning: overflow encountered in matmul
# >>   grad_roll = theta_roll @ (e_roll.T @ P_single_axis @ B_single_axis)
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_2396\1354193109.py:149: RuntimeWarning: overflow encountered in matmul
# >>   grad_yaw = theta_yaw @ (e_yaw.T @ P_single_axis @ B_single_axis)
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_2396\1354193109.py:161: RuntimeWarning: invalid value encountered in divide
# >>   What_pitch = What_pitch + dt * gamma * (grad_pitch - sigma * (What_pitch - Whatf_pitch)) / norm_pitch
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_2396\1354193109.py:162: RuntimeWarning: invalid value encountered in divide
# >>   What_roll = What_roll + dt * gamma * (grad_roll - sigma * (What_roll - Whatf_roll)) / norm_roll
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_2396\1354193109.py:163: RuntimeWarning: invalid value encountered in divide
# >>   What_yaw = What_yaw + dt * gamma * (grad_yaw - sigma * (What_yaw - Whatf_yaw)) / norm_yaw
# >> C:\Users\Acer\AppData\Local\Temp\ipykernel_2396\1354193109.py:50: RuntimeWarning: overflow encountered in scalar multiply
# >>   theta_pitch_base = compute_basis(1.0, pitch, pitch_dot, roll_dot * yaw_dot)
# >> [... 5 more output lines truncated]

# %% [cell 7] code
# =============================================================================
# ENHANCED ADAPTIVE CONTROLLER DIAGNOSTICS & THEORETICAL ROOT CAUSE ANALYSIS
# =============================================================================

import numpy as np
from scipy import signal

def diagnose_adaptive_controller(t_rec, x_rec, xm_rec, u_rec, ua_pitch_rec, 
                                  ua_roll_rec, ua_yaw_rec, What_pitch_rec, 
                                  What_roll_rec, What_yaw_rec, e_pitch_rec, 
                                  e_roll_rec, e_yaw_rec, v_rec, 
                                  wn=None, zeta=None, lam=None, gamma=None, 
                                  sigma=None, tau_v=None):
    """
    🔬 THEORY-DRIVEN DIAGNOSTICS for Adaptive Controller Tuning
    
    This function provides ROOT CAUSE ANALYSIS by connecting observed symptoms 
    to fundamental theoretical properties:
    
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    THEORETICAL FOUNDATION:
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    1. REFERENCE MODEL (Desired Dynamics):
       ẍ_m + 2ζω_n ẋ_m + ω_n² x_m = ω_n² r
       
       → ω_n sets the SPEED of response (settling time ≈ 4/(ζω_n))
       → ζ sets the DAMPING (overshoot, oscillation)
       → This is YOUR TARGET - what you WANT the system to do
    
    2. ADAPTIVE LAW (Parameter Estimation):
       Ẇ = Γ[Φe^T P B - σW] / (1 + Φ^T Φ)
       
       → Γ (gamma) sets LEARNING RATE - how fast we estimate uncertainties
       → σ (sigma) adds DAMPING to prevent parameter drift/bursting
       → Trade-off: Fast learning (high Γ) ↔ Noise rejection (low Γ)
    
    3. PERFORMANCE RECOVERY FILTER (L1/Filtered Adaptive Control):
       v̇ = (1/τ_v)(v_desired - v)   [First-order]
       OR
       v̈ + 2ζ_pr λ v̇ + λ² v = λ² v_desired   [Second-order]
       
       ⚠️ CRITICAL: τ_v (or 1/λ) determines the bandwidth of the filter
       
       → τ_v TOO SMALL (high bandwidth): 
          • Filter does nothing → No separation between estimation & control
          • High-frequency noise/adaptation passes through → OSCILLATIONS
          • Can amplify unmodeled dynamics → INSTABILITY/OVERFLOW
       
       → τ_v TOO LARGE (low bandwidth): 
          • Over-filtering → Sluggish response, can't cancel fast disturbances
          • Large phase lag → Reduces stability margins
       
       → RULE: τ_v should filter OUT frequencies above ω_n (reference model)
                but PASS frequencies below ω_n
                Suggested: τ_v ≈ 0.5 to 2.0 seconds (cutoff ≈ 0.5-2 rad/s)
    
    4. FREQUENCY SEPARATION PRINCIPLE:
       For stability and good performance:
       
           ω_adaptation  >>  ω_reference  >>  ω_filter_cutoff  >>  0
           (fast learn)      (desired)        (v smoothing)
       
       Example: Γ=200 → bandwidth ≈√200≈14 rad/s
                ω_n=2 rad/s → reference bandwidth
                1/τ_v=0.5 rad/s (τ_v=2s) → filter cutoff
    
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    Parameters:
    -----------
    ... (data arrays from simulation)
    wn : float - Reference model natural frequency [rad/s]
    zeta : float - Reference model damping ratio
    lam : float - Performance recovery bandwidth [rad/s] (if using 2nd-order)
    gamma : float - Final adaptation gain (learning rate)
    sigma : float - Sigma-modification gain (leakage)
    tau_v : float - Time constant for v filter [s] (if using 1st-order)
    
    Returns:
    --------
    diagnostics : dict - ROOT CAUSE analysis with targeted solutions
    """
    
    # Convert lists to arrays
    t = np.array(t_rec)
    x = np.array(x_rec)
    xm = np.array(xm_rec)
    u = np.array(u_rec)
    ua_pitch = np.array(ua_pitch_rec)
    ua_roll = np.array(ua_roll_rec)
    ua_yaw = np.array(ua_yaw_rec)
    What_pitch = np.array(What_pitch_rec)
    What_roll = np.array(What_roll_rec)
    What_yaw = np.array(What_yaw_rec)
    e_pitch = np.array(e_pitch_rec)
    e_roll = np.array(e_roll_rec)
    e_yaw = np.array(e_yaw_rec)
    v = np.array(v_rec)
    
    dt = np.mean(np.diff(t))
    
    diagnostics = {
        'issues': [],
        'recommendations': [],
        'metrics': {},
        'severity': 'HEALTHY'  # HEALTHY, WARNING, CRITICAL
    }
    
    # =========================================================================
    # 1. CHECK FOR NUMERICAL OVERFLOW/INSTABILITY
    # =========================================================================
    max_u = np.max(np.abs(u))
    max_ua = np.max([np.max(np.abs(ua_pitch)), np.max(np.abs(ua_roll)), np.max(np.abs(ua_yaw))])
    max_weight = np.max([np.max(np.abs(What_pitch)), np.max(np.abs(What_roll)), np.max(np.abs(What_yaw))])
    
    diagnostics['metrics']['max_control'] = max_u
    diagnostics['metrics']['max_adaptive_control'] = max_ua
    diagnostics['metrics']['max_weight'] = max_weight
    
    if max_u > 1e6 or np.any(np.isnan(u)) or np.any(np.isinf(u)):
        diagnostics['issues'].append("🚨 NUMERICAL OVERFLOW DETECTED in control signal u")
        diagnostics['recommendations'].append(
            "CRITICAL: Reduce γ (gamma) by 50-90%. Current adaptation is TOO FAST causing instability."
        )
        diagnostics['recommendations'].append(
            "CRITICAL: Increase σ (sigma) by 5-10x to add more damping (leakage)."
        )
        diagnostics['severity'] = 'CRITICAL'
    
    elif max_u > 1e3:
        diagnostics['issues'].append("⚠️ Very large control signals (>1000)")
        diagnostics['recommendations'].append(
            "WARNING: Reduce γ by 30-50%. High gains are amplifying noise or uncertainty."
        )
        diagnostics['severity'] = max(diagnostics['severity'], 'WARNING', key=['HEALTHY', 'WARNING', 'CRITICAL'].index)
    
    if max_weight > 1e3:
        diagnostics['issues'].append("⚠️ Adaptive weights growing unbounded")
        diagnostics['recommendations'].append(
            "Increase σ (sigma-modification) by 2-5x. Parameters are drifting."
        )
        diagnostics['recommendations'].append(
            "Check if regressor is persistently exciting (PE). Lack of PE causes drift."
        )
        diagnostics['severity'] = max(diagnostics['severity'], 'WARNING', key=['HEALTHY', 'WARNING', 'CRITICAL'].index)
    
    # =========================================================================
    # 2. TRACKING ERROR ANALYSIS
    # =========================================================================
    # Compute RMS tracking errors (degrees)
    e_pitch_rms = np.sqrt(np.mean(e_pitch[:, 0]**2))
    e_roll_rms = np.sqrt(np.mean(e_roll[:, 0]**2))
    e_yaw_rms = np.sqrt(np.mean(e_yaw[:, 0]**2))
    
    # Peak errors
    e_pitch_peak = np.max(np.abs(e_pitch[:, 0]))
    e_roll_peak = np.max(np.abs(e_roll[:, 0]))
    e_yaw_peak = np.max(np.abs(e_yaw[:, 0]))
    
    diagnostics['metrics']['rms_error_pitch'] = e_pitch_rms
    diagnostics['metrics']['rms_error_roll'] = e_roll_rms
    diagnostics['metrics']['rms_error_yaw'] = e_yaw_rms
    diagnostics['metrics']['peak_error_pitch'] = e_pitch_peak
    diagnostics['metrics']['peak_error_roll'] = e_roll_peak
    diagnostics['metrics']['peak_error_yaw'] = e_yaw_peak
    
    # Thresholds (degrees)
    POOR_RMS_THRESHOLD = 5.0  # degrees
    POOR_PEAK_THRESHOLD = 15.0  # degrees
    
    if e_pitch_rms > POOR_RMS_THRESHOLD or e_roll_rms > POOR_RMS_THRESHOLD:
        diagnostics['issues'].append(f"⚠️ Poor RMS tracking (Pitch: {e_pitch_rms:.2f}°, Roll: {e_roll_rms:.2f}°)")
        diagnostics['recommendations'].append(
            "Increase γ (gamma) by 50-100% for faster adaptation."
        )
        diagnostics['recommendations'].append(
            "Increase λ (lambda) by 20-50% to allow more aggressive cancellation."
        )
        diagnostics['severity'] = max(diagnostics['severity'], 'WARNING', key=['HEALTHY', 'WARNING', 'CRITICAL'].index)
    
    if e_pitch_peak > POOR_PEAK_THRESHOLD or e_roll_peak > POOR_PEAK_THRESHOLD:
        diagnostics['issues'].append(f"⚠️ Large transient errors (Pitch: {e_pitch_peak:.2f}°, Roll: {e_roll_peak:.2f}°)")
        diagnostics['recommendations'].append(
            "Enable or decrease tau_gamma (gamma scheduling) to allow faster initial adaptation."
        )
    
    # =========================================================================
    # 3. HIGH-FREQUENCY OSCILLATION DETECTION
    # =========================================================================
    # Compute power spectral density of control signal
    def detect_oscillations(signal_data, dt, axis_name):
        """Detect high-frequency oscillations using FFT"""
        if len(signal_data) < 100:
            return None
        
        # Detrend
        signal_detrended = signal_data - np.mean(signal_data)
        
        # FFT
        freqs, psd = signal.welch(signal_detrended, fs=1/dt, nperseg=min(512, len(signal_data)//4))
        
        # Find dominant frequency
        idx_max = np.argmax(psd[1:]) + 1  # Skip DC component
        dominant_freq = freqs[idx_max]
        dominant_power = psd[idx_max]
        
        # High-frequency threshold (above reference model bandwidth)
        hf_threshold = 5.0  # Hz (adjust based on wn)
        
        if dominant_freq > hf_threshold and dominant_power > 0.1 * np.max(psd):
            return {
                'freq': dominant_freq,
                'power': dominant_power,
                'axis': axis_name
            }
        return None
    
    osc_pitch = detect_oscillations(ua_pitch, dt, 'Pitch')
    osc_roll = detect_oscillations(ua_roll, dt, 'Roll')
    osc_yaw = detect_oscillations(ua_yaw, dt, 'Yaw')
    
    oscillations = [osc for osc in [osc_pitch, osc_roll, osc_yaw] if osc is not None]
    
    if oscillations:
        for osc in oscillations:
            diagnostics['issues'].append(
                f"⚠️ High-frequency oscillation detected in {osc['axis']} adaptive control: {osc['freq']:.2f} Hz"
            )
        diagnostics['recommendations'].append(
            "Reduce γ (gamma) by 30-50% to reduce high-frequency gain."
        )
        diagnostics['recommendations'].append(
            "Enable/Increase τ_v (tau_v) to add low-pass filtering on performance recovery."
        )
        diagnostics['recommendations'].append(
            "Enable LOW_FREQUENCY_LEARNING with γ_f ≈ 0.05*γ to suppress HF adaptation."
        )
        diagnostics['severity'] = max(diagnostics['severity'], 'WARNING', key=['HEALTHY', 'WARNING', 'CRITICAL'].index)
    
    # =========================================================================
    # 4. PARAMETER DRIFT DETECTION
    # =========================================================================
    def detect_drift(weights, axis_name):
        """Check if weights are monotonically growing (drift)"""
        # Compute trend (linear regression slope)
        t_norm = np.linspace(0, 1, len(weights))
        for i in range(weights.shape[1]):
            slope = np.polyfit(t_norm, weights[:, i], 1)[0]
            if abs(slope) > 10.0:  # Arbitrary threshold
                return True, i, slope
        return False, None, None
    
    drift_pitch, idx_p, slope_p = detect_drift(What_pitch, 'Pitch')
    drift_roll, idx_r, slope_r = detect_drift(What_roll, 'Roll')
    drift_yaw, idx_y, slope_y = detect_drift(What_yaw, 'Yaw')
    
    if drift_pitch or drift_roll or drift_yaw:
        diagnostics['issues'].append("⚠️ Parameter drift detected (weights growing without bound)")
        diagnostics['recommendations'].append(
            "Increase σ (sigma) by 2-5x to add more leakage/damping."
        )
        diagnostics['recommendations'].append(
            "Check persistent excitation: Is the reference trajectory rich enough?"
        )
        diagnostics['severity'] = max(diagnostics['severity'], 'WARNING', key=['HEALTHY', 'WARNING', 'CRITICAL'].index)
    
    # =========================================================================
    # 5. ADAPTATION SPEED ANALYSIS
    # =========================================================================
    # Check how long it takes for weights to converge (settle within 5% of final value)
    def settling_time(weights, threshold=0.05):
        """Estimate settling time for weight convergence"""
        final_vals = weights[-1000:].mean(axis=0)  # Average last part
        for i, final_val in enumerate(final_vals):
            if abs(final_val) < 0.01:  # Skip near-zero weights
                continue
            settling_idx = None
            for j in range(len(weights)):
                if abs(weights[j, i] - final_val) / (abs(final_val) + 1e-6) < threshold:
                    settling_idx = j
                    break
            if settling_idx and settling_idx > len(weights) * 0.5:  # Settles in 2nd half
                return settling_idx * dt, i
        return None, None
    
    ts_pitch, idx_slow_p = settling_time(What_pitch)
    ts_roll, idx_slow_r = settling_time(What_roll)
    
    if ts_pitch and ts_pitch > t[-1] * 0.7:
        diagnostics['issues'].append(f"⚠️ Slow adaptation: Weights settle after {ts_pitch:.1f}s (>70% of simulation)")
        diagnostics['recommendations'].append(
            "Increase γ (gamma) by 50-100% for faster convergence."
        )
        diagnostics['recommendations'].append(
            "Decrease tau_gamma (if using scheduling) to ramp up faster."
        )
    
    # =========================================================================
    # 6. PERFORMANCE RECOVERY ANALYSIS
    # =========================================================================
    v_norm = np.linalg.norm(v, axis=1)
    v_max = np.max(v_norm)
    v_rms = np.sqrt(np.mean(v_norm**2))
    
    diagnostics['metrics']['v_max'] = v_max
    diagnostics['metrics']['v_rms'] = v_rms
    
    if v_max > 100:
        diagnostics['issues'].append(f"⚠️ Very large performance recovery signal (max: {v_max:.1f})")
        diagnostics['recommendations'].append(
            "Reduce λ (lambda) by 30-50%. High PR gain is injecting excessive control."
        )
        diagnostics['severity'] = max(diagnostics['severity'], 'WARNING', key=['HEALTHY', 'WARNING', 'CRITICAL'].index)
    
    # =========================================================================
    # 7. CONTROL SATURATION CHECK
    # =========================================================================
    # Check if control is frequently saturating (clipping)
    # Assume reasonable limits: ±200 for attitude control
    SATURATION_LIMIT = 200
    saturation_rate = np.mean(np.abs(u) > SATURATION_LIMIT * 0.9)
    
    diagnostics['metrics']['saturation_rate'] = saturation_rate * 100  # Percent
    
    if saturation_rate > 0.1:  # >10% of time saturated
        diagnostics['issues'].append(f"⚠️ Control saturation detected {saturation_rate*100:.1f}% of time")
        diagnostics['recommendations'].append(
            "Reduce λ (lambda) and γ (gamma) by 20-40% to prevent windup."
        )
        diagnostics['recommendations'].append(
            "Add anti-windup logic to adaptive law (project weights)."
        )
    
    # =========================================================================
    # SUMMARY
    # =========================================================================
    if not diagnostics['issues']:
        diagnostics['issues'].append("✅ No major issues detected!")
        diagnostics['recommendations'].append("Controller is well-tuned for this scenario.")
    
    return diagnostics


# =============================================================================
# RUN DIAGNOSTICS
# =============================================================================

print("\n" + "="*80)
print("🔍 RUNNING AUTOMATED DIAGNOSTICS...")
print("="*80 + "\n")

diag = diagnose_adaptive_controller(
    t_rec, x_rec, xm_rec, u_rec, 
    ua_pitch_rec, ua_roll_rec, ua_yaw_rec,
    What_pitch_rec, What_roll_rec, What_yaw_rec,
    e_pitch_rec, e_roll_rec, e_yaw_rec,
    v_rec
)

# Print results
print(f"OVERALL STATUS: {diag['severity']}")
print("="*80)

print("\n📊 KEY METRICS:")
print("-"*80)
for key, val in diag['metrics'].items():
    print(f"  {key:<30} = {val:.4f}")

print("\n🔴 ISSUES DETECTED:")
print("-"*80)
for issue in diag['issues']:
    print(f"  {issue}")

print("\n💡 TUNING RECOMMENDATIONS:")
print("-"*80)
for i, rec in enumerate(diag['recommendations'], 1):
    print(f"  {i}. {rec}")

print("\n" + "="*80)
print("📝 ACTION ITEMS (Priority Order):")
print("="*80)

# Prioritize recommendations
if diag['severity'] == 'CRITICAL':
    print("\n🚨 CRITICAL: Fix these IMMEDIATELY before re-running:")
    for rec in diag['recommendations'][:3]:  # Top 3
        print(f"   • {rec}")
elif diag['severity'] == 'WARNING':
    print("\n⚠️  WARNINGS: Consider these adjustments for better performance:")
    for rec in diag['recommendations'][:5]:
        print(f"   • {rec}")
else:
    print("\n✅ System is performing well! No urgent changes needed.")

print("\n" + "="*80)
# >>
# >> ================================================================================
# >> 🔍 RUNNING AUTOMATED DIAGNOSTICS...
# >> ================================================================================
# >>
# >> OVERALL STATUS: CRITICAL
# >> ================================================================================
# >>
# >> 📊 KEY METRICS:
# >> --------------------------------------------------------------------------------
# >>   max_control                    = nan
# >>   max_adaptive_control           = nan
# >>   max_weight                     = nan
# >>   rms_error_pitch                = nan
# >>   rms_error_roll                 = nan
# >>   rms_error_yaw                  = nan
# >>   peak_error_pitch               = nan
# >>   peak_error_roll                = nan
# >>   peak_error_yaw                 = nan
# >>   v_max                          = nan
# >> [... 23 more output lines truncated]

# %% [cell 8] code
# Convert lists to numpy arrays for easier plotting
x_rec = np.array(x_rec)
xr_rec = np.array(xr_rec)
xm_rec = np.array(xm_rec)
u_rec = np.array(u_rec)
t_rec = np.array(t_rec)
What_pitch_rec = np.array(What_pitch_rec)
What_roll_rec = np.array(What_roll_rec)
What_yaw_rec = np.array(What_yaw_rec)
e_pitch_rec = np.array(e_pitch_rec)
e_roll_rec = np.array(e_roll_rec)
e_yaw_rec = np.array(e_yaw_rec)
ua_pitch_rec = np.array(ua_pitch_rec)  # Now 1D array of scalars
ua_roll_rec = np.array(ua_roll_rec)    # Now 1D array of scalars
ua_yaw_rec = np.array(ua_yaw_rec)      # Now 1D array of scalars
unc_pitch_rec = np.array(unc_pitch_rec)
unc_roll_rec = np.array(unc_roll_rec)
unc_yaw_rec = np.array(unc_yaw_rec)
un_rec = np.array(un_rec)
v_rec = np.array(v_rec)

print("Simulation completed successfully!")
print(f"Final tracking error - Pitch: {e_pitch_rec[-1, 0]:.3f}°, Roll: {e_roll_rec[-1, 0]:.3f}°, Yaw: {e_yaw_rec[-1, 0]:.3f}°")
print(f"\nRegressor Configuration: {'Extended (with un, v)' if INCLUDE_CONTROL_IN_REGRESSOR else 'Base only'}")
print(f"Weight vector size: {What_pitch_rec.shape[1]}")
# >> Simulation completed successfully!
# >> Final tracking error - Pitch: -0.011°, Roll: 0.007°, Yaw: -0.883°
# >>
# >> Regressor Configuration: Extended (with un, v)
# >> Weight vector size: 8

# %% [cell 9] code
# =============================================================================
# DIAGNOSTIC: Performance Recovery Signal (v) Analysis
# =============================================================================
import numpy as np
from scipy import signal as sig
from scipy.fft import fft, fftfreq

fig_diag, axes_diag = plt.subplots(3, 2, figsize=(16, 12))
fig_diag.suptitle('Performance Recovery Signal (v) Diagnostic', fontsize=16, fontweight='bold')

# --- Row 1: v signal time domain ---
# Plot first 500 samples to see transient oscillations clearly
n_samples = min(500, len(t_rec))

axes_diag[0, 0].plot(t_rec[:n_samples], v_rec[:n_samples, 0], 'b-', linewidth=1.5, label='v_pitch')
axes_diag[0, 0].plot(t_rec[:n_samples], v_rec[:n_samples, 1], 'g-', linewidth=1.5, label='v_roll')
axes_diag[0, 0].plot(t_rec[:n_samples], v_rec[:n_samples, 2], 'r-', linewidth=1.5, label='v_yaw')
axes_diag[0, 0].set_xlabel('Time [s]')
axes_diag[0, 0].set_ylabel('v signal')
axes_diag[0, 0].set_title('Performance Recovery Signal v (Transient)')
axes_diag[0, 0].legend()
axes_diag[0, 0].grid(True, alpha=0.3)

# Compare v vs total control u (transient)
axes_diag[0, 1].plot(t_rec[:n_samples], u_rec[:n_samples, 0], 'b-', linewidth=1.5, label='u_total (pitch)')
axes_diag[0, 1].plot(t_rec[:n_samples], v_rec[:n_samples, 0], 'r--', linewidth=1.5, label='v (pitch)')
axes_diag[0, 1].set_xlabel('Time [s]')
axes_diag[0, 1].set_ylabel('Control Signal')
axes_diag[0, 1].set_title('Total Control vs v Signal (Pitch)')
axes_diag[0, 1].legend()
axes_diag[0, 1].grid(True, alpha=0.3)

# --- Row 2: FFT Analysis to find oscillation frequency ---
# Use transient period for FFT (where oscillations are visible)
fft_samples = min(1000, len(t_rec))
v_pitch_transient = v_rec[:fft_samples, 0]

# Remove DC component
v_pitch_centered = v_pitch_transient - np.mean(v_pitch_transient)

# Compute FFT
N = len(v_pitch_centered)
yf = fft(v_pitch_centered)
xf = fftfreq(N, dt)[:N//2]
power = 2.0/N * np.abs(yf[0:N//2])

# Find dominant frequency
dominant_idx = np.argmax(power[1:]) + 1  # Skip DC
dominant_freq = xf[dominant_idx]
dominant_period = 1/dominant_freq if dominant_freq > 0 else np.inf

axes_diag[1, 0].plot(xf, power, 'b-', linewidth=1.5)
axes_diag[1, 0].axvline(x=dominant_freq, color='r', linestyle='--', linewidth=2, 
                        label=f'Dominant: {dominant_freq:.2f} Hz ({dominant_freq*2*np.pi:.2f} rad/s)')
axes_diag[1, 0].set_xlabel('Frequency [Hz]')
axes_diag[1, 0].set_ylabel('Amplitude')
axes_diag[1, 0].set_title('FFT of v_pitch (Frequency Content)')
axes_diag[1, 0].set_xlim([0, 50])  # Focus on relevant range
axes_diag[1, 0].legend()
axes_diag[1, 0].grid(True, alpha=0.3)

# Zoom in on lower frequencies
axes_diag[1, 1].plot(xf, power, 'b-', linewidth=1.5)
axes_diag[1, 1].axvline(x=dominant_freq, color='r', linestyle='--', linewidth=2)
axes_diag[1, 1].axvline(x=wn/(2*np.pi), color='g', linestyle=':', linewidth=2, 
                        label=f'Ref Model BW: {wn/(2*np.pi):.2f} Hz')
axes_diag[1, 1].set_xlabel('Frequency [Hz]')
axes_diag[1, 1].set_ylabel('Amplitude')
axes_diag[1, 1].set_title('FFT Zoomed (with Reference Model Bandwidth)')
axes_diag[1, 1].set_xlim([0, 10])
axes_diag[1, 1].legend()
axes_diag[1, 1].grid(True, alpha=0.3)

# --- Row 3: Filter design recommendation ---
# Compute suggested filter cutoff
suggested_cutoff_hz = max(2 * wn / (2*np.pi), 1.0)  # At least 2x ref model BW
suggested_tau_v = 1 / (2 * np.pi * suggested_cutoff_hz)

# Show what different tau_v values would filter
freqs = np.linspace(0.01, 50, 500)
tau_values = [0.01, 0.02, 0.05, 0.1, 0.2]

for tau in tau_values:
    # First-order filter magnitude response: |H(jω)| = 1/sqrt(1 + (ωτ)²)
    cutoff = 1/(2*np.pi*tau)
    mag = 1 / np.sqrt(1 + (2*np.pi*freqs*tau)**2)
    axes_diag[2, 0].plot(freqs, 20*np.log10(mag), linewidth=1.5, 
                         label=f'τ={tau}s (fc={cutoff:.1f}Hz)')

axes_diag[2, 0].axvline(x=dominant_freq, color='r', linestyle='--', linewidth=2, alpha=0.7,
                        label=f'Oscillation freq: {dominant_freq:.1f} Hz')
axes_diag[2, 0].axvline(x=wn/(2*np.pi), color='g', linestyle=':', linewidth=2, alpha=0.7,
                        label=f'Ref model BW: {wn/(2*np.pi):.2f} Hz')
axes_diag[2, 0].axhline(y=-3, color='k', linestyle=':', alpha=0.5)
axes_diag[2, 0].set_xlabel('Frequency [Hz]')
axes_diag[2, 0].set_ylabel('Magnitude [dB]')
axes_diag[2, 0].set_title('Low-Pass Filter Options for v')
axes_diag[2, 0].set_xlim([0, 30])
axes_diag[2, 0].set_ylim([-40, 5])
axes_diag[2, 0].legend(loc='lower left', fontsize=8)
axes_diag[2, 0].grid(True, alpha=0.3)

# Time-domain comparison: v vs un vs ua
axes_diag[2, 1].plot(t_rec[:n_samples], v_rec[:n_samples, 0], 'r-', linewidth=1.5, label='v (perf recovery)', alpha=0.8)
axes_diag[2, 1].plot(t_rec[:n_samples], un_rec[:n_samples, 0] - v_rec[:n_samples, 0], 'b-', linewidth=1.5, label='un - v (feedback+ff)', alpha=0.8)
axes_diag[2, 1].plot(t_rec[:n_samples], ua_pitch_rec[:n_samples], 'g-', linewidth=1.5, label='ua (adaptive)', alpha=0.8)
axes_diag[2, 1].set_xlabel('Time [s]')
axes_diag[2, 1].set_ylabel('Control Component')
axes_diag[2, 1].set_title('Control Signal Decomposition (Pitch)')
axes_diag[2, 1].legend()
axes_diag[2, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# =============================================================================
# PRINT FREQUENCY ANALYSIS SUMMARY
# =============================================================================
print("=" * 70)
print("FREQUENCY ANALYSIS SUMMARY")
print("=" * 70)
print(f"\n📊 Detected Oscillation Characteristics:")
print(f"   Dominant frequency:     {dominant_freq:.2f} Hz ({dominant_freq*2*np.pi:.2f} rad/s)")
print(f"   Oscillation period:     {dominant_period*1000:.1f} ms")
print(f"\n📊 Reference Model Bandwidth:")
print(f"   ωn = {wn:.2f} rad/s = {wn/(2*np.pi):.2f} Hz")
print(f"\n📊 Current Filter Setting:")
tau_v = 0.05  # Current tau_v used in simulation
print(f"   tau_v = {tau_v:.3f} s → cutoff = {1/(2*np.pi*tau_v):.2f} Hz")

# Recommendation logic
print(f"\n" + "=" * 70)
print("FILTER TUNING RECOMMENDATIONS")
print("=" * 70)

# The filter should:
# 1. Pass frequencies below reference model bandwidth (keep useful signal)
# 2. Attenuate frequencies at/above the oscillation frequency

if dominant_freq > 2 * wn/(2*np.pi):
    # Oscillations are well above ref model BW - can filter aggressively
    recommended_cutoff = 2 * wn/(2*np.pi)  # 2x reference model bandwidth
    recommended_tau = 1 / (2*np.pi*recommended_cutoff)
    print(f"\n✅ GOOD NEWS: Oscillation ({dominant_freq:.1f} Hz) >> Ref model BW ({wn/(2*np.pi):.2f} Hz)")
    print(f"   → Can filter aggressively without losing tracking performance")
    print(f"\n   RECOMMENDED: tau_v = {recommended_tau:.3f} s (cutoff = {recommended_cutoff:.1f} Hz)")
    print(f"   This will attenuate oscillations by {20*np.log10(1/np.sqrt(1+(dominant_freq/recommended_cutoff)**2)):.1f} dB")
else:
    # Oscillations are close to ref model BW - need compromise
    recommended_cutoff = (dominant_freq + wn/(2*np.pi)) / 2
    recommended_tau = 1 / (2*np.pi*recommended_cutoff)
    print(f"\n⚠️  WARNING: Oscillation ({dominant_freq:.1f} Hz) close to Ref model BW ({wn/(2*np.pi):.2f} Hz)")
    print(f"   → Filtering will affect tracking - need compromise")
    print(f"\n   RECOMMENDED: tau_v = {recommended_tau:.3f} s (cutoff = {recommended_cutoff:.1f} Hz)")

print(f"\n📋 Quick Reference - tau_v options:")
print(f"   {'tau_v':<10} {'Cutoff (Hz)':<15} {'Osc. Attenuation':<20} {'Phase lag @ ωn':<15}")
print("-" * 60)
for tau in [0.01, 0.02, 0.05, 0.1, 0.2]:
    fc = 1/(2*np.pi*tau)
    atten = 20*np.log10(1/np.sqrt(1+(dominant_freq*2*np.pi*tau)**2))
    phase_lag = np.arctan(wn*tau) * 180/np.pi
    print(f"   {tau:<10.3f} {fc:<15.1f} {atten:<20.1f} dB {phase_lag:<15.1f}°")

print("\n" + "=" * 70)
# >> [image dropped]
# >> <Figure size 1600x1200 with 6 Axes>
# >> ======================================================================
# >> FREQUENCY ANALYSIS SUMMARY
# >> ======================================================================
# >>
# >> 📊 Detected Oscillation Characteristics:
# >>    Dominant frequency:     0.17 Hz (1.05 rad/s)
# >>    Oscillation period:     6000.0 ms
# >>
# >> 📊 Reference Model Bandwidth:
# >>    ωn = 2.00 rad/s = 0.32 Hz
# >>
# >> 📊 Current Filter Setting:
# >>    tau_v = 0.050 s → cutoff = 3.18 Hz
# >>
# >> ======================================================================
# >> FILTER TUNING RECOMMENDATIONS
# >> ======================================================================
# >>
# >> [... 15 more output lines truncated]

# %% [cell 10] code
# Quick visualization of  results
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('CORRECTED Adaptive Control Results', fontsize=16, fontweight='bold')

# Angle tracking
axes[0,0].plot(t_rec, x_rec[:, 0], 'b-', linewidth=2, label='Actual Pitch')
axes[0,0].plot(t_rec, xm_rec[:, 0], 'r--', linewidth=2, label='Reference')
axes[0,0].set_ylabel('Angle [°]')
axes[0,0].set_title('Pitch Tracking')
axes[0,0].legend()
axes[0,0].grid(True, alpha=0.3)

axes[0,1].plot(t_rec, x_rec[:, 2], 'g-', linewidth=2, label='Actual Roll')
axes[0,1].plot(t_rec, xm_rec[:, 2], 'r--', linewidth=2, label='Reference')
axes[0,1].set_ylabel('Angle [°]')
axes[0,1].set_title('Roll Tracking')
axes[0,1].legend()
axes[0,1].grid(True, alpha=0.3)

# Tracking errors
axes[1,0].plot(t_rec, e_pitch_rec[:, 0], 'b-', linewidth=2, label='Pitch Error')
axes[1,0].plot(t_rec, e_roll_rec[:, 0], 'g-', linewidth=2, label='Roll Error')
axes[1,0].plot(t_rec, e_yaw_rec[:, 0], 'm-', linewidth=2, label='Yaw Error')
axes[1,0].set_xlabel('Time [s]')
axes[1,0].set_ylabel('Error [°]')
axes[1,0].set_title('Tracking Errors')
axes[1,0].legend()
axes[1,0].grid(True, alpha=0.3)
axes[1,0].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Adaptive vs True uncertainty (pitch)
axes[1,1].plot(t_rec, -np.array(ua_pitch_rec), 'b-', linewidth=2, label='Adaptive Estimate')
axes[1,1].plot(t_rec, unc_pitch_rec, 'r--', linewidth=2, label='True Uncertainty')
axes[1,1].set_xlabel('Time [s]')
axes[1,1].set_ylabel('Torque [N·m]')
axes[1,1].set_title('Pitch: Adaptive vs True Uncertainty')
axes[1,1].legend()
axes[1,1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("\n" + "="*60)
print("Note: The tracking errors are bounded but non-zero because:")
print("1. σ-modification (leakage) prevents exact uncertainty cancellation")
print("2. This is intentional for robustness - it keeps weights bounded")
print("="*60)
# >> [image dropped]
# >> <Figure size 1400x1000 with 4 Axes>
# >>
# >> ============================================================
# >> Note: The tracking errors are bounded but non-zero because:
# >> 1. σ-modification (leakage) prevents exact uncertainty cancellation
# >> 2. This is intentional for robustness - it keeps weights bounded
# >> ============================================================

# %% [cell 11] markdown
# # Comprehensive Visualization of Adaptive Control Results
#
# This section provides detailed plots for full analysis of the adaptive controller performance.

# %% [cell 12] code
# =============================================================================
# FIGURE 1: ANGLE TRACKING PERFORMANCE (PITCH, ROLL, YAW)
# =============================================================================
fig1, axes1 = plt.subplots(3, 1, figsize=(12, 10))
fig1.suptitle('Angle Tracking Performance', fontsize=16, fontweight='bold')

# Pitch Angle
axes1[0].plot(t_rec, x_rec[:, 0], 'b-', linewidth=2, label='Actual Pitch')
axes1[0].plot(t_rec, xm_rec[:, 0], 'r--', linewidth=2, label='Reference Pitch')
axes1[0].set_ylabel('Pitch Angle [°]', fontsize=12)
axes1[0].legend(loc='best', fontsize=10)
axes1[0].grid(True, alpha=0.3)
axes1[0].set_title('Pitch Axis Tracking', fontsize=12)

# Roll Angle
axes1[1].plot(t_rec, x_rec[:, 2], 'b-', linewidth=2, label='Actual Roll')
axes1[1].plot(t_rec, xm_rec[:, 2], 'r--', linewidth=2, label='Reference Roll')
axes1[1].set_ylabel('Roll Angle [°]', fontsize=12)
axes1[1].legend(loc='best', fontsize=10)
axes1[1].grid(True, alpha=0.3)
axes1[1].set_title('Roll Axis Tracking', fontsize=12)

# Yaw Angle
axes1[2].plot(t_rec, x_rec[:, 4], 'b-', linewidth=2, label='Actual Yaw')
axes1[2].plot(t_rec, xm_rec[:, 4], 'r--', linewidth=2, label='Reference Yaw')
axes1[2].set_ylabel('Yaw Angle [°]', fontsize=12)
axes1[2].set_xlabel('Time [s]', fontsize=12)
axes1[2].legend(loc='best', fontsize=10)
axes1[2].grid(True, alpha=0.3)
axes1[2].set_title('Yaw Axis Tracking', fontsize=12)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x1000 with 3 Axes>

# %% [cell 13] code
# =============================================================================
# FIGURE 2: ANGULAR RATE TRACKING (PITCH_DOT, ROLL_DOT, YAW_DOT)
# =============================================================================
fig2, axes2 = plt.subplots(3, 1, figsize=(12, 10))
fig2.suptitle('Angular Rate Tracking Performance', fontsize=16, fontweight='bold')

# Pitch Rate
axes2[0].plot(t_rec, x_rec[:, 1], 'b-', linewidth=2, label='Actual Pitch Rate')
axes2[0].plot(t_rec, xm_rec[:, 1], 'r--', linewidth=2, label='Reference Pitch Rate')
axes2[0].set_ylabel('Pitch Rate [°/s]', fontsize=12)
axes2[0].legend(loc='best', fontsize=10)
axes2[0].grid(True, alpha=0.3)
axes2[0].set_title('Pitch Rate Tracking', fontsize=12)

# Roll Rate
axes2[1].plot(t_rec, x_rec[:, 3], 'b-', linewidth=2, label='Actual Roll Rate')
axes2[1].plot(t_rec, xm_rec[:, 3], 'r--', linewidth=2, label='Reference Roll Rate')
axes2[1].set_ylabel('Roll Rate [°/s]', fontsize=12)
axes2[1].legend(loc='best', fontsize=10)
axes2[1].grid(True, alpha=0.3)
axes2[1].set_title('Roll Rate Tracking', fontsize=12)

# Yaw Rate
axes2[2].plot(t_rec, x_rec[:, 5], 'b-', linewidth=2, label='Actual Yaw Rate')
axes2[2].plot(t_rec, xm_rec[:, 5], 'r--', linewidth=2, label='Reference Yaw Rate')
axes2[2].set_ylabel('Yaw Rate [°/s]', fontsize=12)
axes2[2].set_xlabel('Time [s]', fontsize=12)
axes2[2].legend(loc='best', fontsize=10)
axes2[2].grid(True, alpha=0.3)
axes2[2].set_title('Yaw Rate Tracking', fontsize=12)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x1000 with 3 Axes>

# %% [cell 14] code
# =============================================================================
# FIGURE 3: TRACKING ERRORS (ANGLE AND RATE ERRORS)
# =============================================================================
fig3, axes3 = plt.subplots(3, 2, figsize=(14, 10))
fig3.suptitle('Tracking Errors', fontsize=16, fontweight='bold')

# Pitch Angle Error
axes3[0, 0].plot(t_rec, e_pitch_rec[:, 0], 'r-', linewidth=2)
axes3[0, 0].set_ylabel('Pitch Angle Error [°]', fontsize=11)
axes3[0, 0].grid(True, alpha=0.3)
axes3[0, 0].set_title('Pitch Angle Error', fontsize=11)
axes3[0, 0].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Pitch Rate Error
axes3[0, 1].plot(t_rec, e_pitch_rec[:, 1], 'r-', linewidth=2)
axes3[0, 1].set_ylabel('Pitch Rate Error [°/s]', fontsize=11)
axes3[0, 1].grid(True, alpha=0.3)
axes3[0, 1].set_title('Pitch Rate Error', fontsize=11)
axes3[0, 1].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Roll Angle Error
axes3[1, 0].plot(t_rec, e_roll_rec[:, 0], 'g-', linewidth=2)
axes3[1, 0].set_ylabel('Roll Angle Error [°]', fontsize=11)
axes3[1, 0].grid(True, alpha=0.3)
axes3[1, 0].set_title('Roll Angle Error', fontsize=11)
axes3[1, 0].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Roll Rate Error
axes3[1, 1].plot(t_rec, e_roll_rec[:, 1], 'g-', linewidth=2)
axes3[1, 1].set_ylabel('Roll Rate Error [°/s]', fontsize=11)
axes3[1, 1].grid(True, alpha=0.3)
axes3[1, 1].set_title('Roll Rate Error', fontsize=11)
axes3[1, 1].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Yaw Angle Error
axes3[2, 0].plot(t_rec, e_yaw_rec[:, 0], 'b-', linewidth=2)
axes3[2, 0].set_ylabel('Yaw Angle Error [°]', fontsize=11)
axes3[2, 0].set_xlabel('Time [s]', fontsize=11)
axes3[2, 0].grid(True, alpha=0.3)
axes3[2, 0].set_title('Yaw Angle Error', fontsize=11)
axes3[2, 0].axhline(y=0, color='k', linestyle='--', alpha=0.5)

# Yaw Rate Error
axes3[2, 1].plot(t_rec, e_yaw_rec[:, 1], 'b-', linewidth=2)
axes3[2, 1].set_ylabel('Yaw Rate Error [°/s]', fontsize=11)
axes3[2, 1].set_xlabel('Time [s]', fontsize=11)
axes3[2, 1].grid(True, alpha=0.3)
axes3[2, 1].set_title('Yaw Rate Error', fontsize=11)
axes3[2, 1].axhline(y=0, color='k', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1400x1000 with 6 Axes>

# %% [cell 15] code
# =============================================================================
# FIGURE 4: CONTROL INPUTS (TORQUE COMMANDS)
# =============================================================================
fig4, axes4 = plt.subplots(3, 1, figsize=(12, 10))
fig4.suptitle('Control Torque Commands', fontsize=16, fontweight='bold')

time_to_plot = min(5000, len(t_rec))

# Pitch Torque
axes4[0].plot(t_rec[:time_to_plot], u_rec[:time_to_plot, 0], 'b-', linewidth=2, label='Total Torque')
axes4[0].set_ylabel('Pitch Torque [N·m]', fontsize=12)
axes4[0].legend(loc='best', fontsize=10)
axes4[0].grid(True, alpha=0.3)
axes4[0].set_title('Pitch Control Torque', fontsize=12)

# Roll Torque
axes4[1].plot(t_rec[:time_to_plot], u_rec[:time_to_plot, 1], 'g-', linewidth=2, label='Total Torque')
axes4[1].set_ylabel('Roll Torque [N·m]', fontsize=12)
axes4[1].legend(loc='best', fontsize=10)
axes4[1].grid(True, alpha=0.3)
axes4[1].set_title('Roll Control Torque', fontsize=12)

# Yaw Torque
axes4[2].plot(t_rec[:time_to_plot], u_rec[:time_to_plot, 2], 'r-', linewidth=2, label='Total Torque')
axes4[2].set_ylabel('Yaw Torque [N·m]', fontsize=12)
axes4[2].set_xlabel('Time [s]', fontsize=12)
axes4[2].legend(loc='best', fontsize=10)
axes4[2].grid(True, alpha=0.3)
axes4[2].set_title('Yaw Control Torque', fontsize=12)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x1000 with 3 Axes>

# %% [cell 16] code
ua_pitch_rec.shape
# >> (16667,)

# %% [cell 17] code
# =============================================================================
# FIGURE 5: ADAPTIVE CONTROL CONTRIBUTION
# =============================================================================
fig5, axes5 = plt.subplots(3, 1, figsize=(12, 10))
fig5.suptitle('Adaptive Control Contribution (Uncertainty Compensation)', fontsize=16, fontweight='bold')

# Adaptive Pitch Control
axes5[0].plot(t_rec, ua_pitch_rec, 'b-', linewidth=2, label='Adaptive Control')
axes5[0].plot(t_rec, unc_pitch_rec, 'r--', linewidth=2, label='True Uncertainty')
axes5[0].plot(t_rec, ua_pitch_rec + unc_pitch_rec, 'k:', linewidth=2, label='uncertainty error compensation (should be ~0)')
axes5[0].set_ylabel('Pitch Torque [N·m]', fontsize=12)
axes5[0].legend(loc='best', fontsize=10)
axes5[0].grid(True, alpha=0.3)
axes5[0].set_title('Pitch Adaptive Control vs True Uncertainty', fontsize=12)

# Adaptive Roll Control
axes5[1].plot(t_rec, ua_roll_rec, 'g-', linewidth=2, label='Adaptive Control')
axes5[1].plot(t_rec, unc_roll_rec, 'r--', linewidth=2, label='True Uncertainty')
axes5[1].plot(t_rec, ua_roll_rec + unc_roll_rec, 'k:', linewidth=2, label='uncertainty error compensation (should be ~0)')
axes5[1].set_ylabel('Roll Torque [N·m]', fontsize=12)
axes5[1].legend(loc='best', fontsize=10)
axes5[1].grid(True, alpha=0.3)
axes5[1].set_title('Roll Adaptive Control vs True Uncertainty', fontsize=12)

# Adaptive Yaw Control
axes5[2].plot(t_rec, ua_yaw_rec, 'm-', linewidth=2, label='Adaptive Control')
axes5[2].plot(t_rec, unc_yaw_rec, 'r--', linewidth=2, label='True Uncertainty')
axes5[2].plot(t_rec, ua_yaw_rec + unc_yaw_rec, 'k:', linewidth=2, label='uncertainty error compensation (should be ~0)')
axes5[2].set_ylabel('Yaw Torque [N·m]', fontsize=12)
axes5[2].set_xlabel('Time [s]', fontsize=12)
axes5[2].legend(loc='best', fontsize=10)
axes5[2].grid(True, alpha=0.3)
axes5[2].set_title('Yaw Adaptive Control vs True Uncertainty', fontsize=12)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x1000 with 3 Axes>

# %% [cell 18] code
# =============================================================================
# FIGURE 6: ADAPTIVE WEIGHT ESTIMATES (PITCH AXIS)
# =============================================================================
fig6, ax6 = plt.subplots(figsize=(12, 7))
fig6.suptitle('Adaptive Weight Estimates - Pitch Axis', fontsize=16, fontweight='bold')

# Dynamic labels based on regressor configuration
basis_labels = ["Bias", "Angle", "Rate", "Drag", "Sin", "Gyro"]
if INCLUDE_CONTROL_IN_REGRESSOR:
    basis_labels.extend(["un", "v"])

num_weights = What_pitch_rec.shape[1]
for i in range(num_weights):
    label_name = basis_labels[i] if i < len(basis_labels) else f"W{i+1}"
    ax6.plot(t_rec, What_pitch_rec[:, i], linewidth=2, label=f'W{i+1}: {label_name}')

ax6.set_xlabel('Time [s]', fontsize=12)
ax6.set_ylabel('Weight Value', fontsize=12)
ax6.legend(loc='best', fontsize=10, ncol=2)
ax6.grid(True, alpha=0.3)
ax6.set_title(f'Evolution of Adaptive Weights for Pitch Axis ({"Extended" if INCLUDE_CONTROL_IN_REGRESSOR else "Base"})', fontsize=12)
plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x700 with 1 Axes>

# %% [cell 19] code
# =============================================================================
# FIGURE 7: ADAPTIVE WEIGHT ESTIMATES (ROLL AXIS)
# =============================================================================
fig7, ax7 = plt.subplots(figsize=(12, 7))
fig7.suptitle('Adaptive Weight Estimates - Roll Axis', fontsize=16, fontweight='bold')

# Dynamic labels based on regressor configuration
basis_labels = ["Bias", "Angle", "Rate", "Drag", "Sin", "Gyro"]
if INCLUDE_CONTROL_IN_REGRESSOR:
    basis_labels.extend(["un", "v"])

num_weights = What_roll_rec.shape[1]
for i in range(num_weights):
    label_name = basis_labels[i] if i < len(basis_labels) else f"W{i+1}"
    ax7.plot(t_rec, What_roll_rec[:, i], linewidth=2, label=f'W{i+1}: {label_name}')

ax7.set_xlabel('Time [s]', fontsize=12)
ax7.set_ylabel('Weight Value', fontsize=12)
ax7.legend(loc='best', fontsize=10, ncol=2)
ax7.grid(True, alpha=0.3)
ax7.set_title(f'Evolution of Adaptive Weights for Roll Axis ({"Extended" if INCLUDE_CONTROL_IN_REGRESSOR else "Base"})', fontsize=12)
plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x700 with 1 Axes>

# %% [cell 20] code
# =============================================================================
# FIGURE 8: ADAPTIVE WEIGHT ESTIMATES (YAW AXIS)
# =============================================================================
fig8, ax8 = plt.subplots(figsize=(12, 7))
fig8.suptitle('Adaptive Weight Estimates - Yaw Axis', fontsize=16, fontweight='bold')

# Dynamic labels based on regressor configuration
basis_labels = ["Bias", "Angle", "Rate", "Drag", "Sin", "Gyro"]
if INCLUDE_CONTROL_IN_REGRESSOR:
    basis_labels.extend(["un", "v"])

num_weights = What_yaw_rec.shape[1]
for i in range(num_weights):
    label_name = basis_labels[i] if i < len(basis_labels) else f"W{i+1}"
    ax8.plot(t_rec, What_yaw_rec[:, i], linewidth=2, label=f'W{i+1}: {label_name}')

ax8.set_xlabel('Time [s]', fontsize=12)
ax8.set_ylabel('Weight Value', fontsize=12)
ax8.legend(loc='best', fontsize=10, ncol=2)
ax8.grid(True, alpha=0.3)
ax8.set_title(f'Evolution of Adaptive Weights for Yaw Axis ({"Extended" if INCLUDE_CONTROL_IN_REGRESSOR else "Base"})', fontsize=12)
plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x700 with 1 Axes>

# %% [cell 21] code
# =============================================================================
# FIGURE 9: 3D TRAJECTORY VISUALIZATION
# =============================================================================
fig9 = plt.figure(figsize=(14, 10))

# 3D Actual vs Reference Trajectory
ax9a = fig9.add_subplot(221, projection='3d')
ax9a.plot(x_rec[:, 0], x_rec[:, 2], x_rec[:, 4], 'b-', linewidth=2, label='Actual')
ax9a.plot(xm_rec[:, 0], xm_rec[:, 2], xm_rec[:, 4], 'r--', linewidth=2, label='Reference')
ax9a.set_xlabel('Pitch [°]', fontsize=10)
ax9a.set_ylabel('Roll [°]', fontsize=10)
ax9a.set_zlabel('Yaw [°]', fontsize=10)
ax9a.set_title('3D Attitude Trajectory', fontsize=12)
ax9a.legend()
ax9a.grid(True, alpha=0.3)

# Pitch vs Roll
ax9b = fig9.add_subplot(222)
ax9b.plot(x_rec[:, 0], x_rec[:, 2], 'b-', linewidth=2, label='Actual')
ax9b.plot(xm_rec[:, 0], xm_rec[:, 2], 'r--', linewidth=2, label='Reference')
ax9b.set_xlabel('Pitch [°]', fontsize=11)
ax9b.set_ylabel('Roll [°]', fontsize=11)
ax9b.set_title('Pitch vs Roll', fontsize=12)
ax9b.legend()
ax9b.grid(True, alpha=0.3)

# Pitch vs Yaw
ax9c = fig9.add_subplot(223)
ax9c.plot(x_rec[:, 0], x_rec[:, 4], 'b-', linewidth=2, label='Actual')
ax9c.plot(xm_rec[:, 0], xm_rec[:, 4], 'r--', linewidth=2, label='Reference')
ax9c.set_xlabel('Pitch [°]', fontsize=11)
ax9c.set_ylabel('Yaw [°]', fontsize=11)
ax9c.set_title('Pitch vs Yaw', fontsize=12)
ax9c.legend()
ax9c.grid(True, alpha=0.3)

# Roll vs Yaw
ax9d = fig9.add_subplot(224)
ax9d.plot(x_rec[:, 2], x_rec[:, 4], 'b-', linewidth=2, label='Actual')
ax9d.plot(xm_rec[:, 2], xm_rec[:, 4], 'r--', linewidth=2, label='Reference')
ax9d.set_xlabel('Roll [°]', fontsize=11)
ax9d.set_ylabel('Yaw [°]', fontsize=11)
ax9d.set_title('Roll vs Yaw', fontsize=12)
ax9d.legend()
ax9d.grid(True, alpha=0.3)

fig9.suptitle('3D State Space Visualization', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1400x1000 with 4 Axes>

# %% [cell 22] code
# =============================================================================
# FIGURE 10: ERROR MAGNITUDE OVER TIME
# =============================================================================
fig10, ax10 = plt.subplots(figsize=(12, 6))

# Compute total error magnitude for each axis
pitch_error_mag = np.sqrt(e_pitch_rec[:, 0]**2 + e_pitch_rec[:, 1]**2)
roll_error_mag = np.sqrt(e_roll_rec[:, 0]**2 + e_roll_rec[:, 1]**2)
yaw_error_mag = np.sqrt(e_yaw_rec[:, 0]**2 + e_yaw_rec[:, 1]**2)

ax10.plot(t_rec, pitch_error_mag, 'b-', linewidth=2, label='Pitch Error Magnitude')
ax10.plot(t_rec, roll_error_mag, 'g-', linewidth=2, label='Roll Error Magnitude')
ax10.plot(t_rec, yaw_error_mag, 'r-', linewidth=2, label='Yaw Error Magnitude')
ax10.set_xlabel('Time [s]', fontsize=12)
ax10.set_ylabel('Error Magnitude', fontsize=12)
ax10.set_title('Tracking Error Magnitude Over Time', fontsize=14, fontweight='bold')
ax10.legend(loc='best', fontsize=11)
ax10.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1200x600 with 1 Axes>

# %% [cell 23] code
# =============================================================================
# FIGURE 11: WEIGHT CONVERGENCE COMPARISON (ALL AXES)
# =============================================================================
# Determine subplot grid based on number of weights
num_weights = What_pitch_rec.shape[1]
n_rows = (num_weights + 2) // 3  # Ceiling division for 3 columns
n_cols = min(num_weights, 3)

fig11, axes11 = plt.subplots(n_rows, n_cols, figsize=(16, 4*n_rows))
fig11.suptitle(f'Adaptive Weight Convergence - All Axes ({"Extended" if INCLUDE_CONTROL_IN_REGRESSOR else "Base"} Regressor)', 
               fontsize=16, fontweight='bold')

# Dynamic labels
basis_names = ["Bias", "Angle", "Rate", "Drag", "Sin", "Gyro"]
if INCLUDE_CONTROL_IN_REGRESSOR:
    basis_names.extend(["un", "v"])

# Flatten axes for easier indexing
if n_rows > 1:
    axes_flat = axes11.flatten()
else:
    axes_flat = [axes11] if num_weights == 1 else axes11

for i in range(num_weights):
    ax = axes_flat[i]
    label_name = basis_names[i] if i < len(basis_names) else f"W{i+1}"
    ax.plot(t_rec, What_pitch_rec[:, i], 'b-', linewidth=2, label='Pitch')
    ax.plot(t_rec, What_roll_rec[:, i], 'g-', linewidth=2, label='Roll')
    ax.plot(t_rec, What_yaw_rec[:, i], 'r-', linewidth=2, label='Yaw')
    ax.set_xlabel('Time [s]', fontsize=10)
    ax.set_ylabel('Weight Value', fontsize=10)
    ax.set_title(f'Weight {i+1}: {label_name}', fontsize=11)
    ax.legend(loc='best', fontsize=9)
    ax.grid(True, alpha=0.3)

# Hide unused subplots
for i in range(num_weights, len(axes_flat)):
    axes_flat[i].set_visible(False)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1600x1200 with 9 Axes>

# %% [cell 24] code
# =============================================================================
# FIGURE 12: PERFORMANCE METRICS SUMMARY
# =============================================================================
fig12, axes12 = plt.subplots(2, 2, figsize=(14, 10))
fig12.suptitle('Performance Metrics Summary', fontsize=16, fontweight='bold')

# RMS Error over time (sliding window)
window_size = 500
pitch_rms = np.array([np.sqrt(np.mean(pitch_error_mag[max(0,i-window_size):i+1]**2)) 
                      for i in range(len(pitch_error_mag))])
roll_rms = np.array([np.sqrt(np.mean(roll_error_mag[max(0,i-window_size):i+1]**2)) 
                     for i in range(len(roll_error_mag))])
yaw_rms = np.array([np.sqrt(np.mean(yaw_error_mag[max(0,i-window_size):i+1]**2)) 
                    for i in range(len(yaw_error_mag))])

axes12[0, 0].plot(t_rec, pitch_rms, 'b-', linewidth=2, label='Pitch')
axes12[0, 0].plot(t_rec, roll_rms, 'g-', linewidth=2, label='Roll')
axes12[0, 0].plot(t_rec, yaw_rms, 'r-', linewidth=2, label='Yaw')
axes12[0, 0].set_xlabel('Time [s]', fontsize=11)
axes12[0, 0].set_ylabel('RMS Error', fontsize=11)
axes12[0, 0].set_title('Rolling RMS Error', fontsize=12)
axes12[0, 0].legend(loc='best')
axes12[0, 0].grid(True, alpha=0.3)

# Control effort
pitch_effort = np.cumsum(np.abs(u_rec[:, 0])) * dt
roll_effort = np.cumsum(np.abs(u_rec[:, 1])) * dt
yaw_effort = np.cumsum(np.abs(u_rec[:, 2])) * dt

axes12[0, 1].plot(t_rec, pitch_effort, 'b-', linewidth=2, label='Pitch')
axes12[0, 1].plot(t_rec, roll_effort, 'g-', linewidth=2, label='Roll')
axes12[0, 1].plot(t_rec, yaw_effort, 'r-', linewidth=2, label='Yaw')
axes12[0, 1].set_xlabel('Time [s]', fontsize=11)
axes12[0, 1].set_ylabel('Cumulative Control Effort', fontsize=11)
axes12[0, 1].set_title('Total Control Effort', fontsize=12)
axes12[0, 1].legend(loc='best')
axes12[0, 1].grid(True, alpha=0.3)

# Settling time analysis (time to reach 2% of steady state)
axes12[1, 0].plot(t_rec, np.abs(e_pitch_rec[:, 0]), 'b-', linewidth=2, label='Pitch')
axes12[1, 0].plot(t_rec, np.abs(e_roll_rec[:, 0]), 'g-', linewidth=2, label='Roll')
axes12[1, 0].plot(t_rec, np.abs(e_yaw_rec[:, 0]), 'r-', linewidth=2, label='Yaw')
axes12[1, 0].axhline(y=2, color='k', linestyle='--', alpha=0.5, label='2° threshold')
axes12[1, 0].set_xlabel('Time [s]', fontsize=11)
axes12[1, 0].set_ylabel('Absolute Angle Error [°]', fontsize=11)
axes12[1, 0].set_title('Absolute Angle Error (Settling Analysis)', fontsize=12)
axes12[1, 0].legend(loc='best')
axes12[1, 0].grid(True, alpha=0.3)
axes12[1, 0].set_yscale('log')

# Phase plot (error vs error_dot)
axes12[1, 1].plot(e_pitch_rec[:, 0], e_pitch_rec[:, 1], 'b-', linewidth=1.5, alpha=0.7, label='Pitch')
axes12[1, 1].plot(e_roll_rec[:, 0], e_roll_rec[:, 1], 'g-', linewidth=1.5, alpha=0.7, label='Roll')
axes12[1, 1].plot(e_yaw_rec[:, 0], e_yaw_rec[:, 1], 'r-', linewidth=1.5, alpha=0.7, label='Yaw')
axes12[1, 1].plot(0, 0, 'k*', markersize=15, label='Equilibrium')
axes12[1, 1].set_xlabel('Angle Error [°]', fontsize=11)
axes12[1, 1].set_ylabel('Rate Error [°/s]', fontsize=11)
axes12[1, 1].set_title('Phase Portrait (Error Space)', fontsize=12)
axes12[1, 1].legend(loc='best')
axes12[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()
# >> [image dropped]
# >> <Figure size 1400x1000 with 4 Axes>

# %% [cell 25] code
# =============================================================================
# FIGURE 13: QUANTITATIVE PERFORMANCE SUMMARY TABLE
# =============================================================================
print("="*80)
print("QUANTITATIVE PERFORMANCE METRICS")
print("="*80)
print(f"\nRegressor Configuration: {'EXTENDED (with un, v) - Λ Compensation' if INCLUDE_CONTROL_IN_REGRESSOR else 'BASE (uncertainty only)'}")
print(f"Number of adaptive weights per axis: {What_pitch_rec.shape[1]}")

# Calculate metrics for each axis
axes_names = ['Pitch', 'Roll', 'Yaw']
error_mags = [pitch_error_mag, roll_error_mag, yaw_error_mag]
angle_errors = [e_pitch_rec[:, 0], e_roll_rec[:, 0], e_yaw_rec[:, 0]]

for i, axis_name in enumerate(axes_names):
    print(f"\n{axis_name} Axis:")
    print(f"  Max Angle Error:        {np.max(np.abs(angle_errors[i])):.3f}°")
    print(f"  Mean Angle Error:       {np.mean(np.abs(angle_errors[i])):.3f}°")
    print(f"  Final Angle Error:      {angle_errors[i][-1]:.3f}°")
    print(f"  RMS Error:              {np.sqrt(np.mean(error_mags[i]**2)):.3f}")
    print(f"  Max Control Torque:     {np.max(np.abs(u_rec[:, i])):.3f} N·m")
    print(f"  Total Control Effort:   {np.sum(np.abs(u_rec[:, i])) * dt:.3f} N·m·s")
    
    # Find settling time (time to stay within 2° permanently)
    within_threshold = np.abs(angle_errors[i]) < 2.0
    if np.any(within_threshold):
        # Find last time it exceeds threshold
        exceed_indices = np.where(~within_threshold)[0]
        if len(exceed_indices) > 0 and exceed_indices[-1] < len(t_rec) - 100:
            settling_time = t_rec[exceed_indices[-1] + 1]
            print(f"  Settling Time (<2°):    {settling_time:.2f} s")
        else:
            print(f"  Settling Time (<2°):    Not achieved")
    else:
        print(f"  Settling Time (<2°):    Not achieved")

print("\n" + "="*80)
print("ADAPTIVE WEIGHT FINAL VALUES")
print("="*80)

# Dynamic labels based on regressor configuration
basis_names_full = ["Bias", "Angle", "Rate", "Drag", "Sin", "Gyro Coupling"]
if INCLUDE_CONTROL_IN_REGRESSOR:
    basis_names_full.extend(["un (ctrl eff)", "v (perf rec)"])

num_weights = What_pitch_rec.shape[1]
print(f"\n{'Parameter':<20} {'Pitch':<12} {'Roll':<12} {'Yaw':<12}")
print("-" * 56)
for i in range(num_weights):
    param_name = basis_names_full[i] if i < len(basis_names_full) else f"Weight {i+1}"
    print(f"{param_name:<20} {What_pitch_rec[-1, i]:>11.4f} {What_roll_rec[-1, i]:>11.4f} {What_yaw_rec[-1, i]:>11.4f}")

print("\n" + "="*80)

# Print insight about control effectiveness weights if extended regressor used
if INCLUDE_CONTROL_IN_REGRESSOR:
    print("\n📊 CONTROL EFFECTIVENESS ADAPTATION INSIGHT:")
    print("-" * 56)
    print("The un and v weights adapt to compensate for Λ uncertainty.")
    print(f"  W_un (pitch): {What_pitch_rec[-1, -2]:.4f} → Adapts to control gain error")
    print(f"  W_v  (pitch): {What_pitch_rec[-1, -1]:.4f} → Adapts to perf recovery effect")
    print("\nIf Λ_true ≠ Λ_nom, these weights will be non-zero.")
    print("="*80)
# >> ================================================================================
# >> QUANTITATIVE PERFORMANCE METRICS
# >> ================================================================================
# >>
# >> Regressor Configuration: EXTENDED (with un, v) - Λ Compensation
# >> Number of adaptive weights per axis: 8
# >>
# >> Pitch Axis:
# >>   Max Angle Error:        1.681°
# >>   Mean Angle Error:       0.140°
# >>   Final Angle Error:      -0.027°
# >>   RMS Error:              0.434
# >>   Max Control Torque:     0.144 N·m
# >>   Total Control Effort:   10.052 N·m·s
# >>   Settling Time (<2°):    Not achieved
# >>
# >> Roll Axis:
# >>   Max Angle Error:        1.658°
# >>   Mean Angle Error:       0.136°
# >>   Final Angle Error:      -0.022°
# >> [... 39 more output lines truncated]

# %% [cell 26] markdown
# ## Visualization Guide
#
# The code above generates **13 comprehensive figures**:
# 1. **Angle Tracking** - Actual vs reference for pitch/roll/yaw
# 2. **Angular Rate Tracking** - Rate tracking performance
# 3. **Tracking Errors** - Detailed error analysis (6 subplots)
# 4. **Control Torques** - Control effort for each axis
# 5. **Adaptive Compensation** - How well adaptive control learns uncertainties
# 6-8. **Weight Evolution** - Adaptive parameter convergence for each axis (includes un, v if extended)
# 9. **3D Trajectory** - State space visualization
# 10. **Error Magnitude** - Overall error trends
# 11. **Weight Comparison** - Cross-axis weight analysis
# 12. **Performance Metrics** - RMS, control effort, phase portraits
# 13. **Quantitative Summary** - Numerical performance table
#
# ---
#
# ## Configuration Comparison Guide
#
# ### To compare Base vs Extended Regressor:
#
# 1. **Run with `INCLUDE_CONTROL_IN_REGRESSOR = False`:**
#    - 6 weights: [Bias, Angle, Rate, Drag, Sin, Gyro]
#    - Compensates only for matched uncertainty Δ(x)
#    - Simpler, more stable
#
# 2. **Run with `INCLUDE_CONTROL_IN_REGRESSOR = True`:**
#    - 8 weights: [Bias, Angle, Rate, Drag, Sin, Gyro, **un**, **v**]
#    - Compensates for BOTH Δ(x) AND control effectiveness Λ
#    - Uses previous-step control to avoid algebraic loop
#    - Better for systems with Λ uncertainty
#
# ### When un/v weights matter:
# - If `Λ_true ≈ Λ_nom`: un/v weights stay near zero
# - If `Λ_true ≠ Λ_nom`: un/v weights become significant to compensate
#
# ### Test idea:
# Change `Lambda_true` to differ from nominal (e.g., `Lambda_true = 0.8 * np.diag([1/Jx, 1/Jy, 1/Jz])`) and observe how un/v weights adapt!

