// ------------------------------------------------------------------------------
// MRAC Implementation File
// ------------------------------------------------------------------------------
// Contains the core adaptive control logic for the 4 axes of a free-flying
// quadcopter (Pitch, Roll, Yaw, Z-Axis).
// ------------------------------------------------------------------------------

#include "mrac.h"
#include "mrac_math.h"
#include <math.h>
#include "imu_update.h"

// Adaptive state lives in the CPU-only 64 KB CCM (0x10000000); USER/JX_FLY.sct places section
// MRAC_CCM there and __main still zeroes it. No DMA may read or write an object tagged MRAC_CCM.
// CYCCNT is already running: RPM_DwtInit enables it at boot. Host builds have neither.
#ifdef __CC_ARM
    #define MRAC_CCM __attribute__((section("MRAC_CCM"), zero_init))
    #define MRAC_CYC_NOW() (DWT->CYCCNT)
#else
    #define MRAC_CCM
    #define MRAC_CYC_NOW() 0U
#endif

// Global instance of the MRAC runtime states
MRAC_State_t mrac_state MRAC_CCM;
MRAC_FeatureFlags_t mrac_flags = {0};

// Global configurations for the 4 axes
MRAC_AxisConfig_t mrac_config_pitch MRAC_CCM;
MRAC_AxisConfig_t mrac_config_roll MRAC_CCM;
MRAC_AxisConfig_t mrac_config_yaw MRAC_CCM;
MRAC_AxisConfig_t mrac_config_z MRAC_CCM;

/* Simplex fallback. Defaults are inert: mode 0, variant 0, fade 1. */
MRAC_Simplex_t mrac_simplex = {0, 0, 0, 0, 0, 0, {0, 0, 0, 0}, 0, 200, 40,
                               3.14f, 3.14f, 1.0e6f, 1.0f};

// Supplied by SINS/baro-IMU fusion � wire this before flight test.

// ------------------------------------------------------------------------------
// Opt-in sigma-prior attractor (prior-D / ADR-0013 D5, D10)
// ------------------------------------------------------------------------------
// Guarded by MRAC_ENABLE_SIGMA_PRIOR. Default build is byte-identical to the
// pre-change build (sil_gate parity test enforces). When the flag is defined
// the gradient update in MRAC_UpdateAxis pulls Theta toward Theta_prior at
// rate sigma_prior. File-scope zero-init matches the existing convention.
//
// Axis-indexed storage: Theta_prior[MRAC_AXIS_*][:MAX_NUM_BASIS].
// ---------------------------------------------------------------------------
#ifdef MRAC_ENABLE_SIGMA_PRIOR
float Theta_prior[AXES][MAX_NUM_BASIS];
float sigma_prior = 0.0f;
#endif

// TODO [HW-PARAM]: identify from motor characterization
#define MOTOR_CT 0.0f




// ------------------------------------------------------------------------------
// Helper: Inverse Mixer
// ------------------------------------------------------------------------------
// Extracts the equivalent mechanical torque/thrust generated by the motors 
// purely from the current actual PWM values and Battery Voltage.
// Needed for actuator loss-of-effectiveness (LOE) estimation and 
// calculating saturation limits for hedging.
static void MRAC_InverseMixer(float current_vbatt, float pwm1, float pwm2, float pwm3, float pwm4,
                              float* u_pitch_actual, float* u_roll_actual, float* u_yaw_actual, float* u_z_actual)
{
    // TODO [HW-PARAM]: Tune c_T thrust coefficient and mixer geometry.
    // Assuming standard Quad-X configuration:
    // Thrust_i = MOTOR_CT * (pwm_i * current_vbatt)^2
    
    // float t1 = MOTOR_CT * (pwm1 * current_vbatt) * (pwm1 * current_vbatt);
    // float t2 = MOTOR_CT * (pwm2 * current_vbatt) * (pwm2 * current_vbatt);
    // float t3 = MOTOR_CT * (pwm3 * current_vbatt) * (pwm3 * current_vbatt);
    // float t4 = MOTOR_CT * (pwm4 * current_vbatt) * (pwm4 * current_vbatt);
    
    // Reverse mix for Quad-X
    // *u_pitch_actual = (t1 + t2 - t3 - t4);
    // *u_roll_actual  = (t1 - t2 + t3 - t4);
    // *u_yaw_actual   = (t1 - t2 - t3 + t4);
    // *u_z_actual     = (t1 + t2 + t3 + t4); // Total vertical thrust
    
    *u_pitch_actual = 0.0f; // Placeholder until wired
    *u_roll_actual  = 0.0f; // Placeholder until wired
    *u_yaw_actual   = 0.0f; // Placeholder until wired
    *u_z_actual     = 0.0f; // Placeholder until wired
}

// ------------------------------------------------------------------------------
// Helper: Regressor Generator (Structured Physics-Based)
// ------------------------------------------------------------------------------
// Populates the Phi vector mirroring 6DOF quadcopter physics.

static void MRAC_ProjectGradient(float grad[], const float Theta[], int num_basis,
                                 const float* limit, const float* tol, const float* lower_limit)
{
    int i;

    for (i = 0; i < num_basis; i++) {
        float upper;
        float lower;
        float band;
        float g;
        float w;
        float scale;

        upper = limit[i];
        lower = lower_limit[i];
        band = tol[i];
        g = grad[i];
        w = Theta[i];

        if (band <= 0.0f) {
            if ((w >= upper && g > 0.0f) || (w <= lower && g < 0.0f)) {
                grad[i] = 0.0f;
            }
            continue;
        }

        if (g > 0.0f) {
            if (w >= upper) {
                g = 0.0f;
            } else if (w > (upper - band)) {
                scale = (upper - w) / band;
                if (scale < 0.0f) {
                    scale = 0.0f;
                }
                g *= scale;
            }
        } else if (g < 0.0f) {
            if (w <= lower) {
                g = 0.0f;
            } else if (w < (lower + band)) {
                scale = (w - lower) / band;
                if (scale < 0.0f) {
                    scale = 0.0f;
                }
                g *= scale;
            }
        }

        grad[i] = g;
    }
}


// SINDY & RBF block generator inserted here 
#if MRAC_N_RBF > 0
float mrac_rbf_centres[MRAC_N_RBF] MRAC_CCM;
float mrac_rbf_inv_2w2[AXES] MRAC_CCM;
float mrac_rbf_inv_x_scale[AXES] MRAC_CCM;

static void MRAC_GenRBF(MRAC_Axis_e axis, const MRAC_Bus_t *bus, float *phi)
{
    float z = bus->x * mrac_rbf_inv_x_scale[axis];
    int k;
    for (k = 0; k < MRAC_N_RBF; k++) {
        float dz = z - mrac_rbf_centres[k];
        phi[k] = expf(-dz * dz * mrac_rbf_inv_2w2[axis]);
    }
}
#endif

#if MRAC_N_SINDY > 0
typedef struct {
    const char *name;
    uint8_t p_x;
    uint8_t p_absx;
    uint8_t p_u;
    uint8_t p_absu;
    uint8_t p_cross;
    uint8_t p_xm;
    MRAC_FeatureGroup_e group;
} MRAC_SindyTerm_t;

const MRAC_SindyTerm_t mrac_sindy_table[MRAC_N_SINDY] = {
#if MRAC_N_STRUCT == 0
    {"1",            0, 0, 0, 0, 0, 0, MRAC_GRP_BIAS},
    {"x",            1, 0, 0, 0, 0, 0, MRAC_GRP_RATE},
    {"cross",        0, 0, 0, 0, 1, 0, MRAC_GRP_COUPLING},
    {"u_nom",        0, 0, 1, 0, 0, 0, MRAC_GRP_CTRL},
    {"xm",           0, 0, 0, 0, 0, 1, MRAC_GRP_REF},
#endif
    {"x|x|",         1, 1, 0, 0, 0, 0, MRAC_GRP_AERO},
    {"x^3",          3, 0, 0, 0, 0, 0, MRAC_GRP_POLY},
    {"x*u_nom",      1, 0, 1, 0, 0, 0, MRAC_GRP_POLY},
    {"x*cross",      1, 0, 0, 0, 1, 0, MRAC_GRP_POLY},
    {"u_nom|u_nom|", 0, 0, 1, 1, 0, 0, MRAC_GRP_POLY},
    {"xm*x",         1, 0, 0, 0, 0, 1, MRAC_GRP_POLY}
};

typedef char MRAC_Assert_Sindy_Count[ ((int)(sizeof(mrac_sindy_table) / sizeof(mrac_sindy_table[0])) == MRAC_N_SINDY) ? 1 : -1 ];

static void MRAC_GenSindy(MRAC_Axis_e axis, const MRAC_Bus_t *bus, float *phi)
{
    int i;
    float abs_x = fabsf(bus->x);
    float abs_u = fabsf(bus->u_nom);
    for (i = 0; i < MRAC_N_SINDY; i++) {
        float val = 1.0f;
        uint8_t k;
        for (k = 0; k < mrac_sindy_table[i].p_x; k++) val *= bus->x;
        for (k = 0; k < mrac_sindy_table[i].p_absx; k++) val *= abs_x;
        for (k = 0; k < mrac_sindy_table[i].p_u; k++) val *= bus->u_nom;
        for (k = 0; k < mrac_sindy_table[i].p_absu; k++) val *= abs_u;
        for (k = 0; k < mrac_sindy_table[i].p_cross; k++) val *= bus->cross;
        for (k = 0; k < mrac_sindy_table[i].p_xm; k++) val *= bus->xm;
        phi[i] = val;
    }
    (void)axis;
}
#endif

const MRAC_FeatureDesc_t mrac_feature_desc[MRAC_N_FEATURES] = {
#if MRAC_N_STRUCT > 0
    {0, "bias",      MRAC_BLK_STRUCT, MRAC_GRP_BIAS},
    {1, "rate",      MRAC_BLK_STRUCT, MRAC_GRP_RATE},
    {2, "rate_tanh", MRAC_BLK_STRUCT, MRAC_GRP_AERO},
    {3, "cross",     MRAC_BLK_STRUCT, MRAC_GRP_COUPLING},
    {4, "u_nom",     MRAC_BLK_STRUCT, MRAC_GRP_CTRL},
    {5, "xm",        MRAC_BLK_STRUCT, MRAC_GRP_REF},
#endif
#if MRAC_N_RBF > 0
    {MRAC_N_STRUCT + 0, "rbf00", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 1
    {MRAC_N_STRUCT + 1, "rbf01", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 2
    {MRAC_N_STRUCT + 2, "rbf02", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 3
    {MRAC_N_STRUCT + 3, "rbf03", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 4
    {MRAC_N_STRUCT + 4, "rbf04", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 5
    {MRAC_N_STRUCT + 5, "rbf05", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 6
    {MRAC_N_STRUCT + 6, "rbf06", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 7
    {MRAC_N_STRUCT + 7, "rbf07", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 8
    {MRAC_N_STRUCT + 8, "rbf08", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 9
    {MRAC_N_STRUCT + 9, "rbf09", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 10
    {MRAC_N_STRUCT + 10, "rbf10", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 11
    {MRAC_N_STRUCT + 11, "rbf11", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 12
    {MRAC_N_STRUCT + 12, "rbf12", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 13
    {MRAC_N_STRUCT + 13, "rbf13", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 14
    {MRAC_N_STRUCT + 14, "rbf14", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_RBF > 15
    {MRAC_N_STRUCT + 15, "rbf15", MRAC_BLK_RBF, MRAC_GRP_RBF},
#endif
#if MRAC_N_SINDY > 0
#if MRAC_N_STRUCT == 0
    {MRAC_N_STRUCT + MRAC_N_RBF + 0, "1", MRAC_BLK_SINDY, MRAC_GRP_BIAS},
    {MRAC_N_STRUCT + MRAC_N_RBF + 1, "x", MRAC_BLK_SINDY, MRAC_GRP_RATE},
    {MRAC_N_STRUCT + MRAC_N_RBF + 2, "cross", MRAC_BLK_SINDY, MRAC_GRP_COUPLING},
    {MRAC_N_STRUCT + MRAC_N_RBF + 3, "u_nom", MRAC_BLK_SINDY, MRAC_GRP_CTRL},
    {MRAC_N_STRUCT + MRAC_N_RBF + 4, "xm", MRAC_BLK_SINDY, MRAC_GRP_REF},
    {MRAC_N_STRUCT + MRAC_N_RBF + 5, "x|x|", MRAC_BLK_SINDY, MRAC_GRP_AERO},
    {MRAC_N_STRUCT + MRAC_N_RBF + 6, "x^3", MRAC_BLK_SINDY, MRAC_GRP_POLY},
    {MRAC_N_STRUCT + MRAC_N_RBF + 7, "x*u_nom", MRAC_BLK_SINDY, MRAC_GRP_POLY},
    {MRAC_N_STRUCT + MRAC_N_RBF + 8, "x*cross", MRAC_BLK_SINDY, MRAC_GRP_POLY},
    {MRAC_N_STRUCT + MRAC_N_RBF + 9, "u_nom|u_nom|", MRAC_BLK_SINDY, MRAC_GRP_POLY},
    {MRAC_N_STRUCT + MRAC_N_RBF + 10, "xm*x", MRAC_BLK_SINDY, MRAC_GRP_POLY}
#else
    {MRAC_N_STRUCT + MRAC_N_RBF + 0, "x|x|", MRAC_BLK_SINDY, MRAC_GRP_AERO},
    {MRAC_N_STRUCT + MRAC_N_RBF + 1, "x^3", MRAC_BLK_SINDY, MRAC_GRP_POLY},
    {MRAC_N_STRUCT + MRAC_N_RBF + 2, "x*u_nom", MRAC_BLK_SINDY, MRAC_GRP_POLY},
    {MRAC_N_STRUCT + MRAC_N_RBF + 3, "x*cross", MRAC_BLK_SINDY, MRAC_GRP_POLY},
    {MRAC_N_STRUCT + MRAC_N_RBF + 4, "u_nom|u_nom|", MRAC_BLK_SINDY, MRAC_GRP_POLY},
    {MRAC_N_STRUCT + MRAC_N_RBF + 5, "xm*x", MRAC_BLK_SINDY, MRAC_GRP_POLY}
#endif
#endif
};
const uint8_t mrac_n_features = MRAC_N_FEATURES;

#if MRAC_N_STRUCT > 0
static void MRAC_GenStructured(MRAC_Axis_e axis, const MRAC_Bus_t *bus, float *phi)
{
    
    phi[0] = 1.0f;
    phi[1] = bus->x;
     
    phi[2] = bus->x * tanhf(bus->x);
#if INCLUDE_CONTROL_IN_REGRESSOR == 1
    if (axis == MRAC_AXIS_Z || axis == MRAC_AXIS_YAW) {
        phi[3] = 0.0f;
    } else {
        phi[3] = bus->cross;
    }
    phi[4] = bus->u_nom;
    phi[5] = bus->xm;
#else
    if (axis == MRAC_AXIS_Z || axis == MRAC_AXIS_YAW) {
        phi[3] = bus->u_nom;
    } else {
        phi[3] = bus->cross;
    }
#endif
}

#endif
MRAC_Bus_t mrac_bus[AXES] MRAC_CCM;

const MRAC_BlockDesc_t mrac_block_table[] = {
#if MRAC_N_STRUCT > 0
    {MRAC_BLK_STRUCT, 0, MRAC_N_STRUCT, MRAC_GenStructured},
#endif
#if MRAC_N_RBF > 0
    {MRAC_BLK_RBF, MRAC_N_STRUCT, MRAC_N_RBF, MRAC_GenRBF},
#endif
#if MRAC_N_SINDY > 0
    {MRAC_BLK_SINDY, MRAC_N_STRUCT + MRAC_N_RBF, MRAC_N_SINDY, MRAC_GenSindy},
#endif
};
#define MRAC_N_BLOCKS ((int)(sizeof(mrac_block_table) / sizeof(mrac_block_table[0])))

float mrac_g_gamma[AXES][MRAC_N_GROUPS] MRAC_CCM;
float mrac_g_sigma[AXES][MRAC_N_GROUPS] MRAC_CCM;
float mrac_g_phi[AXES][MRAC_N_GROUPS] MRAC_CCM;
float mrac_u_ff[AXES] MRAC_CCM;

MRAC_Cyc_t mrac_cyc;

static void MRAC_L2_Update(void)
{
}

static float MRAC_L3_Feedforward(MRAC_Axis_e axis, const MRAC_Bus_t *bus)
{
    (void)axis;
    (void)bus;
    return 0.0f; // consumed from stage S4
}

// Closes the cycle record of one MRAC_UpdateAxis call. t0 = entry, t1..t2 = bus fill,
// t2..t3 = block generators, t3..now = the rest. Unsigned deltas survive a CYCCNT wrap; a
// SendProf_Init CYCCNT reset inside a call gives one huge max, clear mrac_cyc.max.
static void MRAC_CycEnd(MRAC_Axis_e axis_id, uint32_t t0, uint32_t t1, uint32_t t2, uint32_t t3)
{
    uint32_t t4 = MRAC_CYC_NOW();
    MRAC_CycSet_t *last = &mrac_cyc.last[axis_id];
    MRAC_CycSet_t *max = &mrac_cyc.max[axis_id];

    last->bus    = t2 - t1;
    last->blocks = t3 - t2;
    last->law    = t4 - t3;
    last->total  = t4 - t0;
    if (last->bus    > max->bus)    max->bus    = last->bus;
    if (last->blocks > max->blocks) max->blocks = last->blocks;
    if (last->law    > max->law)    max->law    = last->law;
    if (last->total  > max->total)  max->total  = last->total;
}

// ------------------------------------------------------------------------------
// Helper: Axis Update Core

// ------------------------------------------------------------------------------
// Runs the core MRAC algorithm for a single axis.
static void MRAC_UpdateAxis(MRAC_Axis_e axis_id, MRAC_AxisState_t* state, const MRAC_AxisConfig_t* config, float cross_coupling, float r)
{
    float P = 1.0f;
    float P_e = 0.0f;
    float P_edot = 0.0f;
    float s;
    float raw_xdot;
    float Phi_sq;
    float denom;
    static float grad[MAX_NUM_BASIS] MRAC_CCM;
    float y;
    float PBe;
    float sigma_e;
    float sigma_eff;
    float sigma_lf_active;
    float raw_u_ad;
    int do_adaptation;
    int i;
    uint32_t t0, t1, t2, t3;

    t0 = MRAC_CYC_NOW();
    // 1. Update reference model dynamics (runtime-selectable via mrac_flags.ref_model_type)
    //    Adaptive-law gain: 1st-order/passthrough use the scalar heuristic P (ADR-0003);
    //    the 2nd-order case uses the FULL matrix-P state-space drive (ADR-0007, supersedes
    //    ADR-0003 for type 2) — see the s = e*Pe + e_dot*Pedot selection in step 5.
    state->r = r; // latch command for telemetry / system-ID frame
    switch (mrac_flags.ref_model_type) {
        case 2: {
            // 2nd-order: xm_ddot = wn^2 (r - xm) - 2*zeta*wn*xm_dot  (semi-implicit Euler, stable for DT*wn < 2)
            float wn  = config->ref_model_bw;
            float acc = wn * wn * (r - state->xm) - 2.0f * config->ref_model_zeta * wn * state->xm_dot;
            state->xm_dot += MRAC_DT * acc;
            state->xm     += MRAC_DT * state->xm_dot;
            // P unused for the drive here; matrix-P (Pe,Pedot) is formed in step 5.
            break;
        }
        case 1: {
            // 1st-order: xm_dot = bw*(r - xm), unity DC gain. P solves 2*Am*P = 1.
            float bw = config->ref_model_bw;
            float dx;
            if (bw < 0.1f) bw = 0.1f;   // P = 1/(2*bw): bw 0 divides by zero
            dx = bw * (r - state->xm);
            state->xm    += MRAC_DT * dx;
            state->xm_dot = dx;
            P = 1.0f / (2.0f * bw);
            break;
        }
        case 0:
        default:
            // Passthrough: instantaneous command, infinite-bandwidth reference. e = -(PID error).
            state->xm = r;
            state->xm_dot = 0.0f;
            P = 1.0f;
            break;
    }
    
    // 2. Compute tracking error (e = x - xm)
    state->e = state->x - state->xm;

    // 2b. Filtered finite-difference rate derivative -> tracking-error derivative.
    //     Drives the 2nd-order matrix-P law (e_dot); kept warm every tick (also for
    //     telemetry) even in deadzone/freeze. ADR-0007.
    raw_xdot = (state->x - state->x_prev) / MRAC_DT;
    state->xdot_f += MRAC_DT * config->wc_edot * (raw_xdot - state->xdot_f);
    state->x_prev = state->x;
    state->e_dot  = state->xdot_f - state->xm_dot;

    // 3. Compute nominal control (done externally)
    
    // 4. Generate Basis/Regressor vector (Phi)
    t1 = MRAC_CYC_NOW();
    mrac_bus[axis_id].x = state->x;
    mrac_bus[axis_id].xm = state->xm;
    mrac_bus[axis_id].xm_dot = state->xm_dot;
    mrac_bus[axis_id].e = state->e;
    mrac_bus[axis_id].e_dot = state->e_dot;
    mrac_bus[axis_id].u_nom = state->u_nom;
    mrac_bus[axis_id].cross = cross_coupling;
    mrac_bus[axis_id].r = r;
    t2 = MRAC_CYC_NOW();

    for (i = 0; i < MRAC_N_BLOCKS; i++) {
        mrac_block_table[i].generator(axis_id, &mrac_bus[axis_id], state->Phi + mrac_block_table[i].first);
    }
    t3 = MRAC_CYC_NOW();
    mrac_u_ff[axis_id] = MRAC_L3_Feedforward(axis_id, &mrac_bus[axis_id]);
    
    // 5. Update adaptive weights using Lyapunov gradient descent
    Phi_sq = MRAC_VectorNormSquare(state->Phi, MRAC_N_FEATURES);
    denom = 1.0f + Phi_sq;

    // Proceed with adaptation only if error is outside deadzone
    do_adaptation = (!mrac_flags.deadzone_on) || (fabsf(state->e) >= config->e_deadzone);

    // Hard freeze: zero adaptive output and skip updates during large error spikes
    if (mrac_flags.hard_freeze_on && config->e_freeze > 0.0f && fabsf(state->e) > config->e_freeze) {
        // Freeze pauses adaptation/output only; Theta is intentionally preserved.
        state->u_ad = 0.0f;
        MRAC_CycEnd(axis_id, t0, t1, t2, t3);
        return;
    }

    /* Simplex: freeze Theta/Whatf (never reset) while tripped or in the PID-only
     * variant; u_ad is still computed and faded at the injection point. */
    if (mrac_simplex.tripped || mrac_simplex.variant == 1) {
        do_adaptation = 0;
    }

    PBe = state->e;

    // Tanh saturation: bound effective error to +/-e_sat regardless of spike magnitude
    if (mrac_flags.tanh_saturation_on && config->e_sat > 0.0f) {
        PBe = config->e_sat * tanhf(PBe / config->e_sat);
    }

    // Lyapunov drive signal s (= e_v^T P B). Scalar heuristic for passthrough/1st-order
    // (ADR-0003); full state-space [e, e_dot]^T P [0;1] = e*Pe + e_dot*Pedot for the
    // 2nd-order matrix-P law (ADR-0007). e_dot is LPF-bounded and not separately
    // tanh-saturated in Phase 1 (e is, via PBe).
    if (mrac_flags.ref_model_type == 2) {
        float wn = config->ref_model_bw;
        float zeta = config->ref_model_zeta;
        float a0;
        float a1;
        if (wn < 0.1f) wn = 0.1f;       // a0 and a1 are denominators below
        if (zeta < 0.1f) zeta = 0.1f;
        a0 = wn * wn;
        a1 = 2.0f * zeta * wn;
        P_e    = config->ref_Q1 / (2.0f * a0);
        P_edot = (config->ref_Q1 / a0 + config->ref_Q2) / (2.0f * a1);
        s = PBe * P_e + state->e_dot * P_edot;
    } else {
        s = PBe * P;
    }

    if (mrac_flags.adaptation_on && do_adaptation) {
        sigma_e = 0.0f;
        if (mrac_flags.e_modification_on) {
            sigma_e = config->k_e * fabsf(state->e);
        }
        sigma_eff = config->sigma + sigma_e;
        sigma_lf_active = mrac_flags.l1_filtering_on ? config->sigma_lf : 0.0f;

        for (i = 0; i < MRAC_N_FEATURES; i++) {
            grad[i] = (-s * state->Phi[i]) / denom;
        }

#ifdef MRAC_ENABLE_SIGMA_PRIOR
        /* Opt-in prior attractor folded into the gradient BEFORE projection.
         * It is the gradient of (1/2)*sigma_prior*||Theta-Theta_prior||^2, so
         * projection must bound the combined gradient — otherwise a large
         * sigma_prior pushes Theta past What_limit (prior-D-fix). */
        if (sigma_prior != 0.0f) {
            for (i = 0; i < MRAC_N_FEATURES; i++) {
                grad[i] -= sigma_prior * (state->Theta[i] - Theta_prior[axis_id][i]);
            }
        }
#endif

        if (mrac_flags.projection_on) {
            MRAC_ProjectGradient(grad, state->Theta, MRAC_N_FEATURES,
                                 config->What_limit, config->What_tol, config->What_lower_limit);
        }

        for (i = 0; i < MRAC_N_FEATURES; i++) {
#if FIX_LEAKAGE_NORMALIZATION == 1
            y = config->gamma[i] * mrac_g_gamma[axis_id][mrac_feature_desc[i].group] * (grad[i]
                - sigma_lf_active * (state->Theta[i] - state->Whatf[i])
                - sigma_eff * mrac_g_sigma[axis_id][mrac_feature_desc[i].group] * state->Theta[i]
                );
#else
            y = config->gamma[i] * mrac_g_gamma[axis_id][mrac_feature_desc[i].group] * (grad[i]
                - sigma_lf_active * (state->Theta[i] - state->Whatf[i]) / denom
                - sigma_eff * mrac_g_sigma[axis_id][mrac_feature_desc[i].group] * state->Theta[i] / denom
                );
#endif

            state->Theta[i] += MRAC_DT * y;

#ifdef MRAC_ENABLE_SIGMA_PRIOR
            /* Discrete-time safeguard: the band-scaling projection cannot
             * bound a single large sigma_prior-driven step (the gradient
             * magnitude can overshoot the band in one tick), so hard-bounds
             * Theta to the projection set after the update (prior-D-fix).
             * No-op when sigma_prior=0, keeping the baseline update exact. */
            if (sigma_prior != 0.0f) {
                if (state->Theta[i] > config->What_limit[i]) {
                    state->Theta[i] = config->What_limit[i];
                } else if (state->Theta[i] < config->What_lower_limit[i]) {
                    state->Theta[i] = config->What_lower_limit[i];
                }
            }
#endif

            // L1-style low-frequency leakage: pull fast weights toward filtered copy
            if (mrac_flags.l1_filtering_on) {
                state->Whatf[i] += MRAC_DT * config->gam_f * (state->Theta[i] - state->Whatf[i]);
            }
        }
    }
    
    // 6. Compute adaptive control component (u_ad = Theta^T * Phi)
    raw_u_ad = 0.0f;
    for (i = 0; i < MRAC_N_FEATURES; i++) {
        raw_u_ad += state->Theta[i] * (state->Phi[i] * mrac_g_phi[axis_id][mrac_feature_desc[i].group]);
    }

#if ENABLE_PERFORMANCE_RECOVERY == 1
    // Apply L1-style low-pass filter to the adaptive signal
    // u_ad_dot = omega_u * (raw_u_ad - u_ad)
    state->u_ad += MRAC_DT * config->omega_u * (raw_u_ad - state->u_ad);
#else
    state->u_ad = raw_u_ad;
#endif

    if (config->u_max > 0.0f) {
        if (state->u_ad > config->u_max) {
            state->u_ad = config->u_max;
        } else if (state->u_ad < -config->u_max) {
            state->u_ad = -config->u_max;
        }
    }
    MRAC_CycEnd(axis_id, t0, t1, t2, t3);
}

void MRAC_SimplexStep(void)
{
    static uint8_t prev_trigger = 0;
    const MRAC_AxisConfig_t *configs[4];
    MRAC_AxisState_t *axes[4];
    float   sum_w2;
    float   target;
    uint8_t trigger;
    uint8_t r;
    uint8_t i;
    uint8_t a;

    configs[0] = &mrac_config_pitch; axes[0] = &mrac_state.pitch;
    configs[1] = &mrac_config_roll;  axes[1] = &mrac_state.roll;
    configs[2] = &mrac_config_yaw;   axes[2] = &mrac_state.yaw;
    configs[3] = &mrac_config_z;     axes[3] = &mrac_state.z_rate;

    r = 0;
    for (a = 0; a < 4; a++) {
        if (fabsf(axes[a]->u_ad) >= configs[a]->u_max * 0.999f) {
            if (mrac_simplex.sat_ticks[a] < 0xFFFFU) mrac_simplex.sat_ticks[a]++;
        } else {
            mrac_simplex.sat_ticks[a] = 0;
        }
        if (r == 0 && mrac_simplex.sat_ticks[a] > mrac_simplex.sat_ticks_max) r = 4;
        sum_w2 = 0.0f;
        for (i = 0; i < MRAC_N_FEATURES; i++) sum_w2 += axes[a]->Theta[i] * axes[a]->Theta[i];
        if (sqrtf(sum_w2) > mrac_simplex.w_norm_max) r = 3;
    }
    if (fabsf(imu_data.pit) > mrac_simplex.pitch_max) r = 2;
    if (fabsf(imu_data.rol) > mrac_simplex.roll_max)   r = 1;
    trigger = (uint8_t)(r != 0);

    if (mrac_simplex.mode == 0) {
        mrac_simplex.tripped     = 0;
        mrac_simplex.clear_ticks = 0;
        prev_trigger = 0;
    } else if (trigger) {
        mrac_simplex.clear_ticks = 0;
        if (mrac_simplex.mode == 1 && mrac_simplex.tripped == 0) {
            mrac_simplex.tripped = 1;
            mrac_simplex.trip_count++;
            mrac_simplex.reason = r;
        } else if (mrac_simplex.mode == 2) {
            if (prev_trigger == 0) mrac_simplex.would_trip_count++;
            mrac_simplex.reason = r;
        }
        prev_trigger = 1;
    } else {
        if (mrac_simplex.tripped) {
            mrac_simplex.clear_ticks++;
            if (mrac_simplex.clear_ticks >= mrac_simplex.hold_ticks) mrac_simplex.tripped = 0;
        }
        prev_trigger = 0;
    }

    /* Fade u_ad over ~100 ms toward 0 (tripped or PID-only) or back to 1. */
    target = (mrac_simplex.tripped || mrac_simplex.variant == 1) ? 0.0f : 1.0f;
    if (mrac_simplex.fade > target) {
        mrac_simplex.fade -= MRAC_DT / 0.1f;
        if (mrac_simplex.fade < target) mrac_simplex.fade = target;
    } else if (mrac_simplex.fade < target) {
        mrac_simplex.fade += MRAC_DT / 0.1f;
        if (mrac_simplex.fade > target) mrac_simplex.fade = target;
    }
}

// ------------------------------------------------------------------------------
// Public API Operations
// ------------------------------------------------------------------------------

#define MRAC_SET(f, p, r, y, z) \
    mrac_config_pitch.f = (p); \
    mrac_config_roll.f = (r); \
    mrac_config_yaw.f = (y); \
    mrac_config_z.f = (z)

#define MRAC_BASIS(ax, i, g, lim, t, low) \
    mrac_config_##ax.gamma[i] = (g); \
    mrac_config_##ax.What_limit[i] = (lim); \
    mrac_config_##ax.What_tol[i] = (t); \
    mrac_config_##ax.What_lower_limit[i] = (low)
#define MRAC_BLOCK_GAIN(ax, first, count, g, lim, t, low) \
    do { \
        int _i; \
        for (_i = 0; _i < (count); _i++) { \
            mrac_config_##ax.gamma[(first) + _i] = (g); \
            mrac_config_##ax.What_limit[(first) + _i] = (lim); \
            mrac_config_##ax.What_tol[(first) + _i] = (t); \
            mrac_config_##ax.What_lower_limit[(first) + _i] = (low); \
        } \
    } while (0)

#if MRAC_N_RBF > 0
/* Centre spacing on the normalised axis [-1, 1]; a single centre sits at 0 and uses spacing 2. */
#if MRAC_N_RBF > 1
    #define MRAC_RBF_SPACING (2.0f / (float)(MRAC_N_RBF - 1))
#else
    #define MRAC_RBF_SPACING 2.0f
#endif
#define MRAC_RBF_ROW(ax, scale, factor) \
    do { \
        float _w = (factor) * MRAC_RBF_SPACING; \
        mrac_rbf_inv_x_scale[MRAC_AXIS_##ax] = 1.0f / (scale); \
        mrac_rbf_inv_2w2[MRAC_AXIS_##ax] = 1.0f / (2.0f * _w * _w); \
    } while (0)
#endif

void MRAC_Init(void)
{
    int i, j;

    /* Per-axis scalars: one row per float field of MRAC_AxisConfig_t, in struct order.
     * Zeros are listed on purpose: these fields were never set before the tables existed. */
    /*       field            pitch                      roll                       yaw                        z */
    MRAC_SET(sigma_lf,        0.8f,                      0.8f,                      1.0f,                      0.0f);
    MRAC_SET(sigma,           0.01f,                     0.01f,                     0.01f,                     0.01f);
    MRAC_SET(gam_f,           16.0f,                     16.0f,                     16.0f,                     0.0f);
    MRAC_SET(omega_u,         4.0f,                      5.0f,                      4.0f,                      20.0f);
    MRAC_SET(lambda_perf,     0.0f,                      0.0f,                      0.0f,                      0.0f);
    MRAC_SET(tau_v,           0.0f,                      0.0f,                      0.0f,                      0.0f);
    MRAC_SET(u_max,           6.73863f,                  6.73863f,                  2.027f,                    13.47726f);
    MRAC_SET(mrac_to_mixer,   DEFAULT_MRAC_TO_MIXER_PR,  DEFAULT_MRAC_TO_MIXER_PR,  DEFAULT_MRAC_TO_MIXER_YAW, DEFAULT_MRAC_TO_MIXER_Z);
    MRAC_SET(J,               0.0023f,                   0.0023f,                   0.0015f,                   1.5f);
    MRAC_SET(e_deadzone,      0.05f,                     0.05f,                     0.05f,                     0.05f);
    MRAC_SET(e_freeze,        1.2f,                      1.2f,                      1.0f,                      1.2f);
    MRAC_SET(e_sat,           0.5f,                      0.5f,                      0.7f,                      0.4f);
    MRAC_SET(k_e,             0.05f,                     0.05f,                     0.05f,                     0.0f);
    MRAC_SET(ref_model_bw,    44.0f,                     44.0f,                     30.0f,                     20.0f);
    MRAC_SET(ref_model_zeta,  0.8f,                      0.8f,                      0.8f,                      0.8f);
    MRAC_SET(P_lyap,          0.0f,                      0.0f,                      0.0f,                      0.0f);
    MRAC_SET(ref_Q1,          1.0f,                      1.0f,                      1.0f,                      1.0f);
    MRAC_SET(ref_Q2,          1.0f,                      1.0f,                      1.0f,                      1.0f);
    MRAC_SET(wc_edot,         30.0f,                     30.0f,                     30.0f,                     30.0f);

    /* Basis weights: gamma = learning rate, limit/lower = weight bounds (projection),
     * tol = projection boundary layer. Yaw limit/tol = pitch/roll value * 0.6f. */
    /*         axis   i  gamma  limit        tol          lower           feature */
#if MRAC_N_STRUCT > 0
    MRAC_BASIS(pitch, 0, 1.50f, 0.15f,       0.03f,       -0.15f);     /* bias */
    MRAC_BASIS(pitch, 1, 0.20f, 0.05f,       0.01f,       0.0f);       /* rate */
    MRAC_BASIS(pitch, 2, 0.05f, 0.02f,       0.005f,      0.0f);       /* rate_tanh */
    MRAC_BASIS(pitch, 3, 0.05f, 0.05f,       0.01f,       0.0f);       /* cross */
    MRAC_BASIS(pitch, 4, 0.10f, 0.20f,       0.04f,       0.0f);       /* u_nom */
    MRAC_BASIS(pitch, 5, 0.10f, 0.15f,       0.03f,       0.0f);       /* xm */
    MRAC_BASIS(roll,  0, 1.50f, 0.15f,       0.03f,       -0.15f);     /* bias */
    MRAC_BASIS(roll,  1, 0.20f, 0.05f,       0.01f,       0.0f);       /* rate */
    MRAC_BASIS(roll,  2, 0.05f, 0.02f,       0.005f,      0.0f);       /* rate_tanh */
    MRAC_BASIS(roll,  3, 0.05f, 0.05f,       0.01f,       0.0f);       /* cross */
    MRAC_BASIS(roll,  4, 0.10f, 0.20f,       0.04f,       0.0f);       /* u_nom */
    MRAC_BASIS(roll,  5, 0.10f, 0.15f,       0.03f,       0.0f);       /* xm */
    MRAC_BASIS(yaw,   0, 1.00f, 0.15f*0.6f,  0.03f*0.6f,  -0.15f*0.6f); /* bias */
    MRAC_BASIS(yaw,   1, 0.10f, 0.05f*0.6f,  0.01f*0.6f,  0.0f);       /* rate */
    MRAC_BASIS(yaw,   2, 0.05f, 0.02f*0.6f,  0.005f*0.6f, 0.0f);       /* rate_tanh */
    MRAC_BASIS(yaw,   3, 0.05f, 0.05f*0.6f,  0.01f*0.6f,  0.0f);       /* cross */
    MRAC_BASIS(yaw,   4, 0.10f, 0.20f*0.6f,  0.04f*0.6f,  0.0f);       /* u_nom */
    MRAC_BASIS(yaw,   5, 0.10f, 0.15f*0.6f,  0.03f*0.6f,  0.0f);       /* xm */
    MRAC_BASIS(z,     0, 2.00f, 1.00f,       0.20f,       0.0f);       /* bias */
    MRAC_BASIS(z,     1, 0.50f, 0.10f,       0.02f,       0.0f);       /* rate */
    MRAC_BASIS(z,     2, 0.10f, 0.05f,       0.01f,       0.0f);       /* rate_tanh */
    MRAC_BASIS(z,     3, 0.10f, 0.05f,       0.01f,       0.0f);       /* cross */
    MRAC_BASIS(z,     4, 0.20f, 0.20f,       0.04f,       0.0f);       /* u_nom */
    MRAC_BASIS(z,     5, 0.20f, 0.20f,       0.04f,       0.0f);       /* xm */
#endif

#if MRAC_N_RBF > 0
    /* RBF block (PROVISIONAL): phi_k = exp(-(z - c_k)^2 / (2 w^2)), z = x / x_scale, centres shared by all axes.
     *           axis    x_scale  width_factor (w = factor * centre spacing) */
    MRAC_RBF_ROW(PITCH,  5.0f,    1.0f);
    MRAC_RBF_ROW(ROLL,   5.0f,    1.0f);
    MRAC_RBF_ROW(YAW,    5.0f,    1.0f);
    MRAC_RBF_ROW(Z,      2.0f,    1.0f);
    {
        int k;
        for (k = 0; k < MRAC_N_RBF; k++) {
#if MRAC_N_RBF > 1
            mrac_rbf_centres[k] = -1.0f + (float)k * MRAC_RBF_SPACING;
#else
            mrac_rbf_centres[k] = 0.0f;
#endif
        }
    }

    /* RBF block gains (PROVISIONAL), signed weights: lower = -limit.
     *              axis    first          count       gamma   limit    tol      lower */
    MRAC_BLOCK_GAIN(pitch,  MRAC_N_STRUCT, MRAC_N_RBF, 0.05f,  0.02f,   0.005f,  -0.02f);
    MRAC_BLOCK_GAIN(roll,   MRAC_N_STRUCT, MRAC_N_RBF, 0.05f,  0.02f,   0.005f,  -0.02f);
    MRAC_BLOCK_GAIN(yaw,    MRAC_N_STRUCT, MRAC_N_RBF, 0.05f,  0.012f,  0.003f,  -0.012f);
    MRAC_BLOCK_GAIN(z,      MRAC_N_STRUCT, MRAC_N_RBF, 0.10f,  0.05f,   0.01f,   -0.05f);
#endif

#if MRAC_N_SINDY > 0
    /* Library block gains (PROVISIONAL), signed weights: lower = -limit. Library signals are used unscaled.
     *              axis    first                       count         gamma   limit    tol      lower */
    MRAC_BLOCK_GAIN(pitch,  MRAC_N_STRUCT + MRAC_N_RBF, MRAC_N_SINDY, 0.05f,  0.02f,   0.005f,  -0.02f);
    MRAC_BLOCK_GAIN(roll,   MRAC_N_STRUCT + MRAC_N_RBF, MRAC_N_SINDY, 0.05f,  0.02f,   0.005f,  -0.02f);
    MRAC_BLOCK_GAIN(yaw,    MRAC_N_STRUCT + MRAC_N_RBF, MRAC_N_SINDY, 0.05f,  0.012f,  0.003f,  -0.012f);
    MRAC_BLOCK_GAIN(z,      MRAC_N_STRUCT + MRAC_N_RBF, MRAC_N_SINDY, 0.10f,  0.05f,   0.01f,   -0.05f);
#endif


    /* History and provenance (newest first)
     * 2026-09-30 S3     RBF and library block rows. ALL PROVISIONAL: never flown, not data-grounded.
     *                   x_scale (pitch/roll/yaw 5.0, z 2.0, in the unit of the axis state x) and width_factor
     *                   1.0 are placeholders chosen by the S3 worker without a recorded-range source: set
     *                   them from recorded |x| before any flight with MRAC_VARIANT != 0.
     *                   Block gains = per-axis minimum of the struct rows above (gamma, limit, tol) with
     *                   lower = -limit; yaw limit 0.012 = 0.02 x 0.6.
     * 2026-09-29 S1b    Local arrays and per-axis assignments -> MRAC_SET / MRAC_BASIS tables, bit-exact
     *                   (API/tests/run_mrac_equiv.py EQUIV OK). Yaw cells stay the products x*0.6f so they
     *                   round exactly as the old PR_Wlim[i]*0.6f did.
     * lower             Bias weight (i=0) unlocked below zero on p/r/y, symmetric with its limit, so the law
     *                   can cancel a standing torque bias (e.g. yaw reactive-torque imbalance). Every other
     *                   weight, and the z bias, keeps lower bound 0 (floored).
     * ref_Q1/Q2 wc_edot 2nd-order matrix-P law (ADR-0007), used only when ref_model_type==2 (p/r), harmless
     *                   on yaw/z. Q = I; Q1=wn would recover the old scalar gain 1/(2*wn). wc_edot = LPF
     *                   cutoff of the finite-difference rate derivative.
     * ref_model_bw      SysID 2026-06-18. Pitch: closed-loop -3dB ~44 rad/s (K~185, lag pole ~2.6Hz, delay
     *                   ~12ms, rel-degree 2), 2nd-order ref. Roll: ~44.1 rad/s, repeatable <0.3% (multisine
     *                   x7 + chirp; K~165, pole ~3.2Hz, delay ~15ms). Yaw 30: PROVISIONAL, yaw is a pure
     *                   integrator G~37/s (rel-degree 1) -> should get a first-order ref (ADR-0005); 30 is
     *                   unvalidated, needs a yaw closed-loop BW measurement before injection. Z 20: slower
     *                   translation bandwidth.
     * omega_u           Perf-recovery LPF on u_ad = p/4 of the identified lag pole (docs/sysid_results.md).
     *                   Pitch p = 16-18 rad/s -> 4.0. Roll p = 19.8 rad/s (7 runs, <0.3% spread) -> 5.0,
     *                   phase lag -18.5 deg (-82 deg at the old 30). The old 30 sat above the plant corner,
     *                   so it was inert. Yaw 4.0: no pole below the 2.2 Hz coherent band, but the same
     *                   motors/ESCs/gyro filter as roll and K~37 is ~5x weaker, so no higher than roll
     *                   (was 20, copied from roll's old number).
     * e_freeze          2026-06-16 data-grounded, passthrough max|e|: pitch 0.77, roll 0.82 -> 1.2 (was 5.0,
     *                   never fired). Yaw 1.0 kept (max|e|=1.28, still catches true outliers). Z 1.2
     *                   (max|e|=1.0; was 0 = disabled, closes the spike-protection gap).
     * e_sat             2026-06-16 ~p99 of |e|: p/r 0.5 (was 3.5, tanh stayed linear), yaw 0.7 (was 2.0),
     *                   z 0.4 ~p95-p99 (was 0 = tanh disabled on the most over-driven axis).
     * J                 kg*m^2 on p/r/y; z holds the mass in kg.
     * u_max             U_MAX_PITCH / U_MAX_ROLL / U_MAX_YAW / U_MAX_Z.
     */

    for (i = 0; i < (int)AXES; i++) {
        mrac_u_ff[i] = 0.0f;
        for (j = 0; j < MRAC_N_GROUPS; j++) {
            mrac_g_gamma[i][j] = 1.0f;
            mrac_g_sigma[i][j] = 1.0f;
            mrac_g_phi[i][j] = 1.0f;
        }
    }

    mrac_flags.adaptation_on      = ENABLE_MRAC_COMPUTATION;
    mrac_flags.projection_on      = ENABLE_PROJECTION_OPERATOR;
    mrac_flags.deadzone_on        = ENABLE_DEADZONE;
    mrac_flags.hard_freeze_on     = 1;
    mrac_flags.tanh_saturation_on = 1;
    mrac_flags.e_modification_on  = 1;
    mrac_flags.l1_filtering_on    = 0;
    mrac_flags.axis_enable_pitch  = 1;
    mrac_flags.axis_enable_roll   = 1;
    mrac_flags.axis_enable_yaw    = 1;
    // Shadow mode by default: MRAC learns and computes u_ad but motors see pure PID
    // until the operator explicitly enables injection from the dashboard (CMD 0x0F idx 10).
    mrac_flags.output_injection_on = 0;
    mrac_flags.id_frame_on        = 0;                       // high-rate system-ID frame off by default (CMD 0x0F idx 11)
    mrac_flags.of_frame_on        = 0;                       // OF calibration frame off by default (CMD 0x0F idx 12)
    mrac_flags.ref_model_type     = DEFAULT_REF_MODEL_TYPE;  // reference model type (CMD 0x13); 0 = passthrough

    MRAC_Reset();
}

void MRAC_Reset(void)
{
    int i;
    // Force reference models to snap to current plant states, reset weights.
    // Useful during mid-flight mode switches or disarms safely.
    for (i = 0; i < MAX_NUM_BASIS; i++) {
        mrac_state.pitch.Theta[i] = 0.0f;
        mrac_state.roll.Theta[i]  = 0.0f;
        mrac_state.yaw.Theta[i]   = 0.0f;
        mrac_state.z_rate.Theta[i]= 0.0f;
        mrac_state.pitch.Whatf[i] = 0.0f;
        mrac_state.roll.Whatf[i]  = 0.0f;
        mrac_state.yaw.Whatf[i]   = 0.0f;
        mrac_state.z_rate.Whatf[i]= 0.0f;
    }
    
    // Snap references to plant state (bumpless) and zero 2nd-order velocity states
    mrac_state.pitch.xm = mrac_state.pitch.x;   mrac_state.pitch.xm_dot  = 0.0f;
    mrac_state.roll.xm  = mrac_state.roll.x;    mrac_state.roll.xm_dot   = 0.0f;
    mrac_state.yaw.xm   = mrac_state.yaw.x;     mrac_state.yaw.xm_dot    = 0.0f;
    mrac_state.z_rate.xm= mrac_state.z_rate.x;  mrac_state.z_rate.xm_dot = 0.0f;

    // Zero the rate-derivative estimator (ADR-0007) so e_dot starts clean post-reset.
    mrac_state.pitch.x_prev = mrac_state.pitch.x;   mrac_state.pitch.xdot_f  = 0.0f; mrac_state.pitch.e_dot  = 0.0f;
    mrac_state.roll.x_prev  = mrac_state.roll.x;    mrac_state.roll.xdot_f   = 0.0f; mrac_state.roll.e_dot   = 0.0f;
    mrac_state.yaw.x_prev   = mrac_state.yaw.x;     mrac_state.yaw.xdot_f    = 0.0f; mrac_state.yaw.e_dot    = 0.0f;
    mrac_state.z_rate.x_prev= mrac_state.z_rate.x;  mrac_state.z_rate.xdot_f = 0.0f; mrac_state.z_rate.e_dot = 0.0f;
}

void MRAC_Control(const CtrlerTypeDef* current_state)
{
    float p_rate, q_rate, r_rate;
    float cross_pitch, cross_roll;
    float r_pitch, r_roll, r_yaw, r_z;
    uint32_t t_l2;
    

    /* Simplex fallback step — evaluate triggers and manage fade. */
    MRAC_SimplexStep();
    t_l2 = MRAC_CYC_NOW();
    MRAC_L2_Update();
    t_l2 = MRAC_CYC_NOW() - t_l2;
    mrac_cyc.l2_last = t_l2;
    if (t_l2 > mrac_cyc.l2_max) mrac_cyc.l2_max = t_l2;
    // Main execution cycle (Hooked into FreeRTOS / Tasks)
    
    // 1. Acquire current Gyro Rates (p, q, r) and Z-velocity from inner-loop cascade
    // Convert PID FB (degrees/s) to rad/s for regressor bounds alignment
    p_rate = current_state->gyroyPID.FB * 0.0174533f; // Y-axis gyro represents Pitch
    q_rate = current_state->gyroxPID.FB * 0.0174533f; // X-axis gyro represents Roll
    r_rate = current_state->gyrozPID.FB * 0.0174533f; // Z-axis gyro represents Yaw
    
    // Assign measured states
    mrac_state.pitch.x = p_rate;
    mrac_state.roll.x  = q_rate;
    mrac_state.yaw.x   = r_rate;
    mrac_state.z_rate.x = current_state->Z_ratePID.FB; // Z-axis velocity measurement from cascade
    
    // Compute cross-coupling terms
    cross_pitch = q_rate * r_rate;
    cross_roll  = p_rate * r_rate;
    
    // 2. Read current commanded targets streaming from outer loops
    // Degrees/s to Radians/s (for gyro references)
    r_pitch = current_state->gyroyPID.Des * 0.0174533f;
    r_roll  = current_state->gyroxPID.Des * 0.0174533f;
    r_yaw   = current_state->gyrozPID.Des * 0.0174533f;
    r_z     = current_state->Z_ratePID.Des; // Pull desired vertical rate directly
    
    // 3. Assign Nominal Control (U) computed by PID controllers
    // Convert from PWM/Mixer units down to physical torque/thrust SI Units 
    // to prevent regressor norm scaling explosion (1 + ||Phi||^2)
    mrac_state.pitch.u_nom  = current_state->gyroyPID.U / mrac_config_pitch.mrac_to_mixer;
    mrac_state.roll.u_nom   = current_state->gyroxPID.U / mrac_config_roll.mrac_to_mixer;
    mrac_state.yaw.u_nom    = current_state->gyrozPID.U / mrac_config_yaw.mrac_to_mixer;
    mrac_state.z_rate.u_nom = current_state->Z_ratePID.U / mrac_config_z.mrac_to_mixer;
    
    // 4. Perform inverse mixing to measure actual actuation capabilities
    // (Omitted in early dev, rely on basic limits)
    
    // 5-8. Update core MRAC algorithms for all axes
    if (mrac_flags.axis_enable_pitch) {
        MRAC_UpdateAxis(MRAC_AXIS_PITCH, &mrac_state.pitch, &mrac_config_pitch, cross_pitch, r_pitch);
    } else {
        mrac_state.pitch.u_ad = 0.0f;
    }
    if (mrac_flags.axis_enable_roll) {
        MRAC_UpdateAxis(MRAC_AXIS_ROLL,  &mrac_state.roll,  &mrac_config_roll,  cross_roll,  r_roll);
    } else {
        mrac_state.roll.u_ad = 0.0f;
    }
    if (mrac_flags.axis_enable_yaw) {
        MRAC_UpdateAxis(MRAC_AXIS_YAW,   &mrac_state.yaw,   &mrac_config_yaw,   0.0f,        r_yaw);
    } else {
        mrac_state.yaw.u_ad = 0.0f;
    }
    MRAC_UpdateAxis(MRAC_AXIS_Z,     &mrac_state.z_rate,&mrac_config_z,     0.0f,        r_z);


}

// ------------------------------------------------------------------------------
// Opt-in sigma-prior accessors (prior-D / ADR-0013 D5, D10)
// ------------------------------------------------------------------------------
// Only emitted when MRAC_ENABLE_SIGMA_PRIOR is defined. Critical-section
// protected against the 200 Hz task-context MRAC_UpdateAxis read of
// Theta_prior[axis_id][:]. The ground-station command dispatch is the
// intended writer; MRAC_Control/UpdateAxis is the reader. A single-writer /
// single-reader pair is race-free under a PRIMASK critical section.
// ---------------------------------------------------------------------------
#ifdef MRAC_ENABLE_SIGMA_PRIOR

void MRAC_SetPrior(uint8_t axis, const float *arr)
{
    uint32_t pri;
    int i;

    if (axis >= (uint8_t)AXES) {
        return;
    }
    if (arr == (const float *)0) {
        return;
    }
    pri = __get_PRIMASK();
    __disable_irq();
    for (i = 0; i < MAX_NUM_BASIS; i++) {
        Theta_prior[axis][i] = arr[i];
    }
    __set_PRIMASK(pri);
}

void MRAC_GetPrior(uint8_t axis, float *out_arr)
{
    uint32_t pri;
    int i;

    if (axis >= (uint8_t)AXES) {
        return;
    }
    if (out_arr == (float *)0) {
        return;
    }
    pri = __get_PRIMASK();
    __disable_irq();
    for (i = 0; i < MAX_NUM_BASIS; i++) {
        out_arr[i] = Theta_prior[axis][i];
    }
    __set_PRIMASK(pri);
}

#endif /* MRAC_ENABLE_SIGMA_PRIOR */
